<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BPPositionsTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('bp_positions')->insert([
            [
                'position_code' => 'ADMIN',
                'position_title' => 'Administrator',
                'dept_code' => 'ADMIN',
                'description' => 'Facility Administrator',
                'is_active' => true,
                'has_supervisor_role' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'DON',
                'position_title' => 'Director of Nursing',
                'dept_code' => 'NURS',
                'description' => 'Leads nursing department',
                'is_active' => true,
                'has_supervisor_role' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'RN',
                'position_title' => 'Registered Nurse',
                'dept_code' => 'NURS',
                'description' => 'Provides direct patient care',
                'is_active' => true,
                'has_supervisor_role' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'LPN',
                'position_title' => 'Licensed Practical Nurse',
                'dept_code' => 'NURS',
                'description' => 'Assists RNs and provides care',
                'is_active' => true,
                'has_supervisor_role' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'CNA',
                'position_title' => 'Certified Nursing Assistant',
                'dept_code' => 'NURS',
                'description' => 'Assists with daily living activities',
                'is_active' => true,
                'has_supervisor_role' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'SOCWRK',
                'position_title' => 'Social Worker',
                'dept_code' => 'SOC',
                'description' => 'Provides social services',
                'is_active' => true,
                'has_supervisor_role' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'ACTDIR',
                'position_title' => 'Activities Director',
                'dept_code' => 'ACT',
                'description' => 'Leads activities department',
                'is_active' => true,
                'has_supervisor_role' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'DIET',
                'position_title' => 'Dietitian',
                'dept_code' => 'DIET',
                'description' => 'Manages dietary needs',
                'is_active' => true,
                'has_supervisor_role' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'MAINT',
                'position_title' => 'Maintenance Supervisor',
                'dept_code' => 'MAINT',
                'description' => 'Oversees facility maintenance',
                'is_active' => true,
                'has_supervisor_role' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'ENVSV',
                'position_title' => 'Environmental Services Supervisor',
                'dept_code' => 'ENV',
                'description' => 'Supervises housekeeping/laundry',
                'is_active' => true,
                'has_supervisor_role' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'IT',
                'position_title' => 'IT Specialist',
                'dept_code' => 'IT',
                'description' => 'Manages IT systems',
                'is_active' => true,
                'has_supervisor_role' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'FIN',
                'position_title' => 'Finance Manager',
                'dept_code' => 'FIN',
                'description' => 'Manages financial operations',
                'is_active' => true,
                'has_supervisor_role' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'QA',
                'position_title' => 'Quality Assurance Coordinator',
                'dept_code' => 'QA',
                'description' => 'Ensures regulatory compliance',
                'is_active' => true,
                'has_supervisor_role' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'ADMIT',
                'position_title' => 'Admissions Coordinator',
                'dept_code' => 'ADMIT',
                'description' => 'Manages resident admissions',
                'is_active' => true,
                'has_supervisor_role' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'PHARM',
                'position_title' => 'Pharmacist',
                'dept_code' => 'PHARM',
                'description' => 'Manages pharmacy services',
                'is_active' => true,
                'has_supervisor_role' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'REHABDIR',
                'position_title' => 'Rehabilitation Director',
                'dept_code' => 'REHAB',
                'description' => 'Leads rehab department',
                'is_active' => true,
                'has_supervisor_role' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'position_code' => 'SEC',
                'position_title' => 'Security Officer',
                'dept_code' => 'SEC',
                'description' => 'Ensures facility security',
                'is_active' => true,
                'has_supervisor_role' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
