<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class ChecklistItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Remove all existing items to prevent duplicates
        DB::table('checklist_items')->truncate();
        $now = Carbon::now();
        $administratorPositionIds = [DB::table('positions')->where('title', 'Administrator')->value('id') ?? 1];
        $cnaPositionIds = [DB::table('positions')->where('title', 'Certified Nursing Assistant')->value('id') ?? 5];
        $dsdPositionIds = [DB::table('positions')->where('title', 'Director of Staff Development')->value('id') ?? 41];
        $items = [
            // PART A - APPLICANT INFORMATION
            ['name' => 'Application Form', 'section' => 'PART A', 'doc_type_id' => 1],
            ['name' => 'Applicant Disclosure', 'section' => 'PART A', 'doc_type_id' => 1],
            ['name' => 'Reference Check #1', 'section' => 'PART A', 'doc_type_id' => 1],
            ['name' => 'Reference Check #2', 'section' => 'PART A', 'doc_type_id' => 1],
            ['name' => 'Offer Letter (if applicable)', 'section' => 'PART A', 'doc_type_id' => 1],
            ['name' => 'Job Data: Hire / Rehire', 'section' => 'PART A', 'doc_type_id' => 1],
            ['name' => 'Emergency Contact Information', 'section' => 'PART A', 'doc_type_id' => 1],
            ['name' => 'Job Description', 'section' => 'PART A', 'doc_type_id' => 1],
            // PART A - IDENTIFICATIONS
            ['name' => 'I - 9', 'section' => 'PART A', 'doc_type_id' => 2],
            ['name' => 'Social Security Card - Copy', 'section' => 'PART A', 'doc_type_id' => 2],
            ["name" => "Driver's License - Copy", 'section' => 'PART A', 'doc_type_id' => 2],
            ['name' => 'Green Card or Work Permit Autho. - Copy', 'section' => 'PART A', 'doc_type_id' => 2],
            ['name' => 'Passport - Copy', 'section' => 'PART A', 'doc_type_id' => 2],
            ['name' => 'Professional License - Copy', 'section' => 'PART A', 'doc_type_id' => 2],
            // PART A - VERIFICATIONS
            ['name' => 'CPR Card (License Nurses)', 'section' => 'PART A', 'doc_type_id' => 3],
            ['name' => 'C.N.A. Certificate', 'section' => 'PART A', 'doc_type_id' => 3],
            ['name' => 'Professional License', 'section' => 'PART A', 'doc_type_id' => 3],
            ['name' => 'Background Check', 'section' => 'PART A', 'doc_type_id' => 3],
            ['name' => 'OIG Verification', 'section' => 'PART A', 'doc_type_id' => 3],
            ['name' => 'SAM Verification', 'section' => 'PART A', 'doc_type_id' => 3],
            ['name' => 'Medical Exclusion/Ineligible Provider List', 'section' => 'PART A', 'doc_type_id' => 3],
            // PART B
            ['name' => 'Abuse, Neglect and Exploitation', 'section' => 'PART B', 'doc_type_id' => 4],
            ['name' => 'Resident Rights', 'section' => 'PART B', 'doc_type_id' => 4],
            ['name' => 'Employee Handbook', 'section' => 'PART B', 'doc_type_id' => 4],
            ['name' => 'Code of Conduct', 'section' => 'PART B', 'doc_type_id' => 4],
            ['name' => 'Spoken Language', 'section' => 'PART B', 'doc_type_id' => 4],
            ['name' => 'Missed Punch Policy', 'section' => 'PART B', 'doc_type_id' => 4],
            ['name' => 'Rest and Meal Break Policy: Hydration Program', 'section' => 'PART B', 'doc_type_id' => 4],
            ['name' => 'Use of ID Badge Policy: Second meal period waiver', 'section' => 'PART B', 'doc_type_id' => 4],
            ['name' => 'Six-hour meal period waiver', 'section' => 'PART B', 'doc_type_id' => 4],
            // PART C
            ['name' => 'Facility Organizational Chart', 'section' => 'PART C', 'doc_type_id' => 4],
            ["name" => "Facility Department Heads' Information", 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Facility Floor Plan', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Facility Tour and General Orientation', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Mariner Health Savings Plan / 401K', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'W-4', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'EDD', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Direct Deposit Authorization (Voided Check)', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Orientation Time Sheet', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Medical Insurance Premium Acknowledged', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'WC - Workplace and Ergonomics Safety', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Illness and Injury Prevention Program', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Individual Safety Responsibility', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Hazard Communication Training', 'section' => 'PART C', 'doc_type_id' => 4],
            ["name" => "Notice to Employee (Labor Code Sec 2810.5)", 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Environmental Care Questionnaire', 'section' => 'PART C', 'doc_type_id' => 4],
            ['name' => 'Required State Notice Acknowledgement Form', 'section' => 'PART C', 'doc_type_id' => 4],
            // PART D
            ['name' => 'Accuracy, Notice of', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'Affirmative, Notice of', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'Blood Borne Pathogen', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'Confidentiality', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'Deficit Reduction Act', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'First Aid for Choking', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'Gait Belt Utilization', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'HIPAA & Compliance', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'Infection Control', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'No Solicitation, Distribution and Access', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'Private Duty', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'Pulmonary Tuberculosis', 'section' => 'PART D', 'doc_type_id' => 4],
            ['name' => 'Substance Abuse and Testing', 'section' => 'PART D', 'doc_type_id' => 4],
            // PART G - CNA Skills CHECKLISTS
            ['name' => 'Ambulation', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Back Rub', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Bed Bath', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Bed Making, Occupied', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Bed Making, Unoccupied', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Bed Pan, Urinal', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Bladder Management/Toileting', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Bladder Patterning/Retraining', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Body Mechanics- Gen. Rules', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Lifting and Moving', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Positioning', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Transferring', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Catheter Care', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Choking, Heimlich Maneuver', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Dementia Training', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Dialysis', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Dressing/undressing', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Emergency Procedures/Reporting', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Feeding, Special Issues', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Tray service', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Dining Program', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Feeding Tubes', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Gastric', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Jejunostomy', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Nasogastric', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Fluid Restrictions, Dot system', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Grooming', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Hand Washing', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Incontinence Care/Perineal Care', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Infection Control, waste', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Linen Handling', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Mechanical Lift', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Oral Hygiene', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Ostomy protocol review', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Oxygen, CPAP, BiPAP Tubing Care', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Tracheostomy-ADL care (CNA scope of practice)', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Pain Identification/Management', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Protective Devices', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Post-mortem care', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Range of motion', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Restraint Devices', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Scales, weighing', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Shaving', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Shower / Bathing', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Specimen Collection', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Splints/Orthosis', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Standard Precautions', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Use of Cane', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Walker', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Prosthetic devices', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Bed controls', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Wheelchair', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Vital signs', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Temperature, axilla', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Temperature, ear', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Temperature, oral', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Temperature, rectal', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Pulse Rate', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Respiratory Rate', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Blood Pressure', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Documentation:', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-RFPR', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '--Bed mobility', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '--Transfers', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '--Eating', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '--Toileting', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Meal Monitoring', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Intake/Output, measurement', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-STOP and WATCH', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-Shower Skin Sheet', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => '-RNA Form (for RNAs)', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            ['name' => 'Other:', 'section' => 'PART G', 'doc_type_id' => 5, 'position_ids' => [5]],
            // PART E - Administrator Orientation CHECKLISTS
            ['name' => 'Facility Tour', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Corporate Integrity Agreement (CIA) Training', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Mandatory Orientation Topics', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Abuse/Neglect', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Infection Control', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Hazard Communication', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Fire/Safety and Emergency Disaster Preparedness', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Review of Foundation Concepts', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Purpose, Beliefs and Values', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Organizational Structure (Divisional/Regional, Facility)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Job Description', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Super Systems Introduction', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Morning Meeting/Ambassador Rounds', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Mini/Thorough Utilization Review', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Risk Meetings', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Nursing Model/Staffing', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Reporting Mechanism for Unusual Occurrences/Reportable Events', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Job Description', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Computer/Communications Systems', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Computer software and available reports', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Voicemail', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Paging system', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--E-mail', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Electronic Risk Management Assistant (ERMA)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Omniview', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--MatrixCare/POC', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Introduction to Key Personnel', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Facility Personnel', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Department Managers', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Staff', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Medical Directors, Physicians, Consultants', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Divisional/Regional Personnel', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Executive VP of Operations (EVPO)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Chief Compliance/Risk Officer (CCO)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--VP of Clinical Operations (VPCO)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--VP of Finance (VPF)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Regional Director of Clinical Operations (RDCO)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Regional Director of Clinical Reimbursement (RDCR)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Regional VP of Operations (RVPO)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Regional Director of Patient Care Advocacy (RDPCA)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Regional Human Resources Director (RHRD)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Regional Director of AR/AP (RDARAP)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Regional Director of Marketing/Census Development (RDBD)/Regional Director of Case Management (RDCM)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Regional Director of Maintenance (RDM)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Regional Director of Payroll (RDP)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Regional Director of Workman\'s Comp. (RDWC)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--BioPacific-VP of Rehab/Regional Rehab Director', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Other Resource Personnel', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Review Of Facility\'s Phone List', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Review job descriptions of all staff reporting to the Administrator', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Review of Policy and Procedure Manuals', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Resident Care Manuals (RC 1, RC 2, RC 3)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Infection Control', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Updated Clinical Manual', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Lippincott Nursing Procedures Book', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Dietary P&P and Manual', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Operations Manuals (Ops 1, Ops 2, Ops 3, Ops 4, Ops 5)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Anderson\'s Medical Records Manual', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Omnicare Policy and Procedure Manual for Skilled Nursing', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Omnicare IV Policy and Procedure Manual', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Run for Restorative Manual', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'MDS 3.0 overview and IDT role/PPS, QM, Star Rating, QASP, PDPM', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'CMS and State Regulations Manuals', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Administrator Required Reports', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Survey Preparation Checklists Review', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Annual', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Title 22', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Life Safety Code', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-PPD/Staffing Audit', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Review of Committee and Meetings', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Risk-at least weekly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Falling Stars Program-weekly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Pharmacy/Psychotropics-monthly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Infection Control-monthly, with sub-committee at least quarterly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-QA&A/QAPI-monthly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Policy and Procedure-annually and whenever necessary', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Safety Committee-monthly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Administrative/Staff Meetings-monthly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Daily Morning Meeting with mini-UR', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Weekly thorough UR', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Restorative Nursing Program Meeting-weekly/monthly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Care Planning-Baseline within 48 hours, within 7 days of admission, at least quarterly thereafter following MDS schedule', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Resident Council-monthly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Actual Attendance of Committee and Meetings', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Governing Body', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Infection Control-monthly, with sub-committee at least quarterly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-QA&A/QAPI-monthly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Policy and Procedure-annually and whenever necessary', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Safety Committee-monthly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Administrative/Staff Meetings-monthly', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Daily Morning Meeting with mini-UR', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Weekly thorough UR', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Resident Council-monthly (if invited)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Actual Ambassador/Clinical Rounds', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Review of last annual survey findings and other survey deficiencies with plans of corrections', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Admission Process and Forms', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Business Development Strategies', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Abuse/Neglect/Exploitation Reporting and Investigation', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Grievances, Ombudsman Notification, Trauma Informed Care', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
 
            ['name' => 'Facility Assessment', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Personnel Issues', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Recruitment/Retention Strategies', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Interviews, Qualifications, Guides, Reference Checks', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Counseling and Discipline Policies', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Contracted Professional Services', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Laboratory', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Pharmacy', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Radiology', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Rehabilitation', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Respiratory', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Disposal', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Other:', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Performance Evaluations-including competency/skills check', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Worker\'s Compensation', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Fiscal Issues', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Expense Budget', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Capital Expense', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Staffing Budget', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Calculating PPDs', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Allocated PPDs', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Calculating FTEs', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Nursing Costs', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-P&L Reports (Certified and Non-Certified)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Supplies and Charges', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Reimbursement', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Medicare/PPS ', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Certified Beds', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Allocating Costs', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Medical', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Private Pay', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '--Insurance', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Payroll/Employee Benefits', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Staffing Schedules', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Master Schedule/Staffing Patterns', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Nursing Hours/PPD', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Care Assignments', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Vacation/Holidays', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Managing Unanticipated Absences', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Staff Development', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Orientation', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-In-service Education Calendar', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Professional Licenses', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-CPR', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Scheduled Exposure to Nursing Unit Experience', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Day Shift', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Afternoon Shift', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Night Shift', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => '-Weekend Shift', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            ['name' => 'Scavenger Hunt (see separate checklist)', 'section' => 'PART E', 'doc_type_id' => 16, 'position_ids' => $administratorPositionIds],
            
            // PART E - DSD Orientation CHECKLIST
            ['name' => 'IN-SERVICE EDUCATION:', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Mandatory for ALL STAFF', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Mandatory for ALL Nursing Staff', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Survey-related Topics', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Other topics as directed by Admin/DON', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'ORIENTATION OF ALL NEW EMPLOYEES', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'NEW HIRE AND ANNUAL SKILLS CHECKLISTS PER DEPARTMENT:', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Licensed Nurses (RP: DON)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Certified Nursing Assistants (RP: DSD)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Director of Nursing (RP: RDCO/Administrator)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Director of Staff Development (RP: DON/RDCO)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-MDS Coordinator (RP: RDMDSUR)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Dietary Staff (RP: Dietary Manager/RD)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Social Services Staff (RP: Administrator)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Other:', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'LICENSES, CERTIFICATIONS TRACKING', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-RN/LVN', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-CNA', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-REHAB STAFF-Secure from Bio-Pacific', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-CPR-RN/LVN and PT/OT/SLP (from Bio-Pacific)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Subacute Ventilator Care Certification (RN/LVN)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'BACKGROUND CHECK', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'ANNUAL MERIT EVALUATION', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'EMPLOYEE FILES [RP: HR Assistant]', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'I-9 FORM [RP: HR Assistant]', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'KRONOS [RP: HR Assistant]', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Time Clock Correction', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Time Request', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Leave of Absence', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'HUMAN RESOURCES [RP: HR Assistant]', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Historical Edit', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-New Hire Form', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Job Data Form', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Termination Form', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Payroll Adjustment Form', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Daily Time Correction Form', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'DAILY PPD [RP: HR Assistant]', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Licensed Nurses and Certified Nursing Assistants', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Staffing Posting', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Daily PPD Reports per CMS', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'STAFFING', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Daily Assignments', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Monthly CNA Schedules', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'WORKERS\' COMPENSATION Regional WC', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'OSHA REPORTING/LOG Regional WC', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'MODIFIED DUTY WEEKLY LOG Regional WC', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'SAFETY MEETING Regional WC', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'INFECTION CONTROL', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Rounds-Daily/Weekly', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Infection Control Surveillance Forms', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Infection Control Log', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Monthly/Quarterly Infection Control Reports', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Care Planning', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Risk Meeting', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'IMMUNIZATION LOG', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Residents\' Immunization Logs', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Employees\' Immunization Logs', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'EMPLOYEE HEALTH', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Initial TB Screening', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Annual TB Screening', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-CXR for Positive PPD + MD Clearance', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Initial Physical Exam', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Annual Physical Exam', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Annual TB Questionnaire', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Annual Flu Vaccine', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Hepatitis B Vaccine', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-CXR every 5 years or as MD ordered', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'POLICIES AND PROCEDURES', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Infection Control Manual', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Updated Surveillance Manual', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Clinical Manual', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Resident Care Manuals 1-3', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Operations Manuals 1-5', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Human Resources Manual', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Dietary Manual', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Anderson Medical Records Manual', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Lippincott Nursing Procedures Book', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Omnicare LTC Manual and IV Therapy Manual', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'RESTORATIVE NURSING PROGRAM (Facility-specific)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-RNA Weekly Meeting and Notes', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-Updating RNA Orders and Care Plans', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => '-RNA Monthly Recap', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'MatrixCare (including Point Of Care-POC)', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            ['name' => 'OTHER:', 'section' => 'PART E', 'doc_type_id' => 26, 'position_ids' => [41]],
            
            // PART E - DSD Orientation CHECKLIST

        ];

        foreach ($items as &$item) {
            if (($item['position_ids'] ?? null) === [5]) {
                $item['position_ids'] = $cnaPositionIds;
            }

            if (($item['position_ids'] ?? null) === [41]) {
                $item['position_ids'] = $dsdPositionIds;
            }
        }
        unset($item);

        $order = 1;
        foreach ($items as $item) {
            DB::table('checklist_items')->insert([
                'name' => $item['name'],
                'section' => $item['section'],
                'doc_type_id' => $item['doc_type_id'],
                'position_ids' => isset($item['position_ids']) ? json_encode($item['position_ids']) : null,
                'order' => $order,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
            $order++;
        }
    }
}
