<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ColorSchemesTableSeeder extends Seeder
{
    public function run(): void
    {
        $schemes = [
            [
                'name' => 'Amber Calm',
                'primary_color'   => '#C08C3F',
                'secondary_color' => '#D7AF79',
                'accent_color'    => '#FFF2DD',
                'neutral_dark'    => '#4A3C26',
                'neutral_light'   => '#E6D4BF',
            ],
            [
                'name' => 'Amber Horizon',
                'primary_color'   => '#FFB400',
                'secondary_color' => '#FFD166',
                'accent_color'    => '#FFF4E0',
                'neutral_dark'    => '#4A3A1E',
                'neutral_light'   => '#F9E6C7',
            ],
            [
                'name' => 'Aqua Breeze',
                'primary_color'   => '#00B8D4',
                'secondary_color' => '#4DD0E1',
                'accent_color'    => '#E0F7FA',
                'neutral_dark'    => '#004D60',
                'neutral_light'   => '#B2EBF2',
            ],
            [
                'name' => 'Berry Delight',
                'primary_color'   => '#8E44AD',
                'secondary_color' => '#9B59B6',
                'accent_color'    => '#F3E5F5',
                'neutral_dark'    => '#4A235A',
                'neutral_light'   => '#DCC6E0',
            ],
            [
                'name' => 'Blush Horizon',
                'primary_color'   => '#E57373',
                'secondary_color' => '#FFCDD2',
                'accent_color'    => '#FFE5E5',
                'neutral_dark'    => '#5D3A3A',
                'neutral_light'   => '#FAD4D4',
            ],
            [
                'name' => 'Blue Fern',
                'primary_color'   => '#547A84',
                'secondary_color' => '#7FA2AC',
                'accent_color'    => '#E4F6F9',
                'neutral_dark'    => '#28363A',
                'neutral_light'   => '#CADADD',
            ],
            [
                'name' => 'Cedar Breeze',
                'primary_color'   => '#5C8466',
                'secondary_color' => '#83A98D',
                'accent_color'    => '#E6F7EF',
                'neutral_dark'    => '#23352C',
                'neutral_light'   => '#CBDCD3',
            ],
            [
                'name' => 'Citrus Grove',
                'primary_color'   => '#F39C12',
                'secondary_color' => '#F1C40F',
                'accent_color'    => '#FEF9E7',
                'neutral_dark'    => '#7D6608',
                'neutral_light'   => '#FDEBD0',
            ],
            [
                'name' => 'Cobalt Serenity',
                'primary_color'   => '#3949AB',
                'secondary_color' => '#5C6BC0',
                'accent_color'    => '#E8EAF6',
                'neutral_dark'    => '#2C2F5A',
                'neutral_light'   => '#D1D9FF',
            ],
            [
                'name' => 'Coral Reef',
                'primary_color'   => '#FF6F61',
                'secondary_color' => '#FF8A80',
                'accent_color'    => '#FFE5E5',
                'neutral_dark'    => '#B71C1C',
                'neutral_light'   => '#FFCDD2',
            ],
            [
                'name' => 'Copper Calm',
                'primary_color'   => '#B9795A',
                'secondary_color' => '#D4A48F',
                'accent_color'    => '#F7EDE9',
                'neutral_dark'    => '#47352E',
                'neutral_light'   => '#E6D6D0',
            ],
            [
                'name' => 'Crimson Sunset',
                'primary_color'   => '#D72638',
                'secondary_color' => '#F46036',
                'accent_color'    => '#FFE5D9',
                'neutral_dark'    => '#3E1F1F',
                'neutral_light'   => '#FAD4C0',
            ],
            [
                'name' => 'Emerald Dream',
                'primary_color'   => '#2A9D8F',
                'secondary_color' => '#8AB17D',
                'accent_color'    => '#EAF4F2',
                'neutral_dark'    => '#1E3D34',
                'neutral_light'   => '#CDE5DB',
            ],
            [
                'name' => 'Forest Canopy',
                'primary_color'   => '#1B5E20',
                'secondary_color' => '#388E3C',
                'accent_color'    => '#E8F5E9',
                'neutral_dark'    => '#0D3B12',
                'neutral_light'   => '#C8E6C9',
            ],
            [
                'name' => 'Gentle Blossom',
                'primary_color'   => '#C58DA3',
                'secondary_color' => '#D9AEC0',
                'accent_color'    => '#FBEFF4',
                'neutral_dark'    => '#473B43',
                'neutral_light'   => '#E7D7DE',
            ],
            [
                'name' => 'Golden Care',
                'primary_color'   => '#D6A756',
                'secondary_color' => '#E5C78D',
                'accent_color'    => '#FAF3E3',
                'neutral_dark'    => '#4B3C27',
                'neutral_light'   => '#E9DCC8',
            ],
            [
                'name' => 'Golden Dusk',
                'primary_color'   => '#F9A825',
                'secondary_color' => '#FFD54F',
                'accent_color'    => '#FFF8E1',
                'neutral_dark'    => '#5A4A1E',
                'neutral_light'   => '#FBE9A7',
            ],
            [
                'name' => 'Lavender Rest',
                'primary_color'   => '#5B4B7A',
                'secondary_color' => '#8779A6',
                'accent_color'    => '#EEE7FF',
                'neutral_dark'    => '#2A2633',
                'neutral_light'   => '#CABFE2',
            ],
            [
                'name' => 'Lemon Zest',
                'primary_color'   => '#FDD835',
                'secondary_color' => '#FFEB3B',
                'accent_color'    => '#FFFDE7',
                'neutral_dark'    => '#F57F17',
                'neutral_light'   => '#FFF9C4',
            ],
            [
                'name' => 'Midnight Sky',
                'primary_color'   => '#283593',
                'secondary_color' => '#3949AB',
                'accent_color'    => '#E8EAF6',
                'neutral_dark'    => '#1A237E',
                'neutral_light'   => '#C5CAE9',
            ],
            [
                'name' => 'Mystic Violet',
                'primary_color'   => '#6A0572',
                'secondary_color' => '#9A4DAB',
                'accent_color'    => '#EBCDF5',
                'neutral_dark'    => '#3E023E',
                'neutral_light'   => '#D8B8E6',
            ],
            [
                'name' => 'Oceanic Depths',
                'primary_color'   => '#005377',
                'secondary_color' => '#007EA7',
                'accent_color'    => '#B3EFFF',
                'neutral_dark'    => '#002B3E',
                'neutral_light'   => '#B3D9E8',
            ],
            [
                'name' => 'Pastel Care',
                'primary_color'   => '#AD97C2',
                'secondary_color' => '#C7B9D6',
                'accent_color'    => '#F7F4FB',
                'neutral_dark'    => '#40384A',
                'neutral_light'   => '#E4DCEF',
            ],
            [
                'name' => 'Peach Blossom',
                'primary_color'   => '#F48FB1',
                'secondary_color' => '#F06292',
                'accent_color'    => '#FCE4EC',
                'neutral_dark'    => '#880E4F',
                'neutral_light'   => '#F8BBD0',
            ],
            [
                'name' => 'Ruby Glow',
                'primary_color'   => '#C62828',
                'secondary_color' => '#E53935',
                'accent_color'    => '#FFEBEE',
                'neutral_dark'    => '#B71C1C',
                'neutral_light'   => '#FFCDD2',
            ],
            [
                'name' => 'Sapphire Glow',
                'primary_color'   => '#264653',
                'secondary_color' => '#2A9D8F',
                'accent_color'    => '#E9F5F5',
                'neutral_dark'    => '#1B2B34',
                'neutral_light'   => '#C3D9D9',
            ],
            [
                'name' => 'Seafoam Serenity',
                'primary_color'   => '#26A69A',
                'secondary_color' => '#4DB6AC',
                'accent_color'    => '#E0F2F1',
                'neutral_dark'    => '#004D40',
                'neutral_light'   => '#B2DFDB',
            ],
            [
                'name' => 'Spring Meadow',
                'primary_color'   => '#4CAF50',
                'secondary_color' => '#81C784',
                'accent_color'    => '#DFFFE0',
                'neutral_dark'    => '#2E7D32',
                'neutral_light'   => '#C8E6C9',
            ],
            [
                'name' => 'Sunset Glow',
                'primary_color'   => '#FF7043',
                'secondary_color' => '#FF8A65',
                'accent_color'    => '#FBE9E7',
                'neutral_dark'    => '#BF360C',
                'neutral_light'   => '#FFCCBC',
            ],
            [
                'name' => 'Tropical Lagoon',
                'primary_color'   => '#00796B',
                'secondary_color' => '#009688',
                'accent_color'    => '#E0F2F1',
                'neutral_dark'    => '#004D40',
                'neutral_light'   => '#B2DFDB',
            ],
            [
                'name' => 'Twilight Bloom',
                'primary_color'   => '#8E24AA',
                'secondary_color' => '#BA68C8',
                'accent_color'    => '#F3E5F5',
                'neutral_dark'    => '#4A2C4F',
                'neutral_light'   => '#E1BEE7',
            ],
            [
                'name' => 'Vivid Coral Bliss',
                'primary_color'   => '#FF6F61',
                'secondary_color' => '#FF9A8B',
                'accent_color'    => '#FFDAD4',
                'neutral_dark'    => '#4A2E2A',
                'neutral_light'   => '#F5D4D0',
            ],
        ];

        DB::table('color_schemes')->insert($schemes);

    }
}
