<?php

namespace Database\Seeders;

use App\Models\EmployeeCompetencyItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeCompetencyItemsSeeder extends Seeder
{
    protected function getPositionIdsByTitles(array|string $titles): array
    {
        $titles = array_values(array_filter(array_map('trim', (array) $titles)));

        if ($titles === []) {
            return [];
        }

        return DB::table('positions')
            ->whereIn('title', $titles)
            ->orderBy('id')
            ->pluck('id')
            ->map(fn ($id) => (int) $id)
            ->all();
    }

    protected function seedCompetencySet(array $competencyItems, array $positionIds, int &$order): void
    {
        foreach ($competencyItems as $section => $items) {
            foreach ($items as $item) {
                EmployeeCompetencyItem::query()->updateOrCreate(
                    [
                        'section' => $section,
                        'item' => $item,
                        'order' => $order,
                    ],
                    [
                        'position_ids' => $positionIds,
                    ]
                );

                $order++;
            }
        }
    }

    public function run(): void
    {
        $directorOfStaffDevelopmentPositionIds = $this->getPositionIdsByTitles('Director of Staff Development');
        $dsdPositionIds = $directorOfStaffDevelopmentPositionIds !== [] ? $directorOfStaffDevelopmentPositionIds : ['global'];
        $cnaPositionIds = $this->getPositionIdsByTitles('Certified Nursing Assistant');
        $licensedNursePositionIds = $this->getPositionIdsByTitles([
            'Director of Nursing',
            'Registered Nurse',
            'Licensed Vocational Nurse',
            'Licensed Nurse',
            'Charge Nurse',
            'IP Nurse',
        ]);

        $dsdCompetencyItems = [
            'IN-SERVICE EDUCATION PROGRAM MANAGEMENT' => [
                'Annual In-Service Plan (meets **California Title 22 & CMS requirements)',
                'Mandatory Nursing In-Services (Skills, Clinical Competency)',
                'Mandatory In-Services for ALL Staff (Abuse, Infection Control, Safety, HIPAA)',
                'Survey-Driven Education',
                'Competency Validation (Return Demonstrations)',
                'Education Tracking Logs (Attendance, Make-ups)',
                'CNA 12-hour Annual In-Service Compliance',
                'Nurse Continuing Education Tracking',
            ],
            'ORIENTATION PROGRAM MANAGEMENT' => [
                'New Hire Orientation (All Departments)',
                'General Orientation (Facility Policies, Emergency Preparedness)',
                'Clinical Orientation (Nursing-specific skills validation)',
                'CNA Orientation and Preceptor Program',
                'Agency/Registry Staff Orientation',
                'Orientation Checklist Completion Monitoring',
            ],
            'SKILLS COMPETENCY PROGRAM (ALL DEPARTMENTS)' => [
                'Licensed Nurses Annual Skills',
                'CNA Skills Competency',
                'DON Competency Validation',
                'Infection Preventionist Competency',
                'MDS Coordinator Competency',
                'Dietary Staff Competency',
                'Social Services Competency',
                'Activities Competency',
                'EVS/Maintenance/Laundry',
            ],
            'LICENSES, CERTIFICATIONS TRACKING' => [
                'RN/LVN (including Registry Staff)',
                'CNA (including Registry Staff)',
                'REHAB STAFF-Secure from Bio-Pacific',
                'CPR-RN/LVN and PT/OT/SLP (from Bio-Pacific)',
                'Subacute Ventilator Care Certification (RN/LVN)',
            ],
            'HUMAN RESOURCES COORDINATION' => [
                'Background Checks Verified',
                'Annual Performance Evaluations Completed',
                'Employee Files Audit (completeness)',
                'I-9 Compliance',
                'UKG/Time Clock Correction',
                'Leave of Absence Tracking',
                'Payroll Adjustment Coordination',
            ],
            'STAFFING & PPD MONITORING' => [
                'Daily PPD Monitoring',
                'Staffing Posting Compliance',
                'CNA Schedules (monthly)',
                'Daily Assignments Reviewed',
            ],
            'WORKERS COMP & SAFETY PROGRAM' => [
                'OSHA Log Maintenance',
                'Workmen’s Compensation Tracking',
                'Modified Duty Program Monitoring',
                'Safety Committee Lead',
            ],
            'COMMITTEE PARTICIPATION' => [
                'Infection Control Committee',
                'QAPI Committee',
                'Education Reports to QAPI',
                'PIP Support (Falls, Wounds, Psychotropics)',
            ],
            'CLINICAL OVERSIGHT & EDUCATION ROUNDS' => [
                'Rounds-Daily (Monthly with IP)',
                'Direct Care Observations/On-the-spot In-services',
            ],
            'INFECTION PREVENTION SUPPORT' => [
                'Isolation/Transmission-Based Precautions Education',
                'COVID-19 protocols and reporting requirements',
                'Isolation/Transmission-Based Precautions Education',
                'Outbreak Education Response',
            ],
            'EMPLOYEE HEALTH PROGRAM' => [
                'Initial TB Screening',
                'Annual TB Screening',
                'Annual TB Questionnaire',
                'CXR for Positive PPD + MD Clearance',
                'CXR every 5 years or as MD ordered',
                'Initial Physical Exam',
                'Annual Physical Exam',
                'COVID-19 Vaccination Program',
                'Annual Flu Vaccine',
                'Hepatitis B Vaccine',
                'Childhood Diseases Immunization',
            ],
            'POLICIES AND PROCEDURES MANAGEMENT' => [
                'Emergency/Disaster, Fire Safety- RED Binders',
                'Abuse/Neglect/Grievance Binder',
                'MCN access for ALL P&Ps',
                'Lippincott Nursing Procedures Book',
                'Pharmacy LTC Manual and IV Therapy Manual',
            ],
            'RESTORATIVE NURSING PROGRAM' => [
                'RNA Weekly Meeting and Notes',
                'Updating RNA Orders and Care Plans',
                'RNA Monthly Recap',
            ],
            'EHR / MATRIXCARE COMPETENCY' => [
                'Staff Training/ Order Entry / Clinical Workflow Training',
                'Documentation Audits',
                'Dashboard Monitoring (alerts/compliance)',
            ],
            'SURVEY READINESS' => [],
        ];

        $cnaCompetencyItems = [
            'CNA SKILLS CHECKLIST' => [
                'Ambulation',
                'Back Rub',
                'Bed Bath',
                'Bed Making, Occupied',
                'Bed Making, Unoccupied',
                'Bed Pan, Urinal',
                'Bladder Management/Toileting',
                'Bladder Patterning/Retraining',
                'Body Mechanics- Gen. Rules',
                '-Lifting and Moving',
                '-Positioning',
                '-Transferring',
                'Catheter Care',
                'Choking, Heimlich Maneuver',
                'Dementia Training',
                'Dialysis',
                'Dressing/undressing',
                'Emergency Procedures/Reporting',
                'Feeding, Special Issues',
                '-Tray service',
                '-Dining Program',
                'Feeding Tubes',
                '-Gastric',
                '-Jejunostomy',
                '-Nasogastric',
                'Fluid Restrictions, Dot system',
                'Grooming',
                'Hand Washing',
                'Incontinence Care/Perineal Care',
                'Infection Control, waste',
                'Linen Handling',
                'Mechanical Lift',
                'Oral Hygiene',
                'Ostomy protocol review',
                'Oxygen, CPAP, BiPAP Tubing Care',
                'Tracheostomy-ADL care (CNA scope of practice)',
                'Pain Identification/Management',
                'Protective Devices',
                'Post-mortem care',
                'Range of motion',
                'Restraint Devices',
                'Scales, weighing',
                'Shaving',
                'Shower / Bathing',
                'Specimen Collection',
                'Splints/Orthosis',
                'Standard Precautions',
                'Use of Cane',
                '-Walker',
                '-Prosthetic devices',
                '-Bed controls',
                '-Wheelchair',
                'Vital signs',
                '-Temperature, axilla',
                '-Temperature, ear',
                '-Temperature, oral',
                '-Temperature, rectal',
                '-Pulse Rate',
                '-Respiratory Rate',
                '-Blood Pressure',
                'Documentation:',
                '-RFPR',
                '--Bed mobility',
                '--Transfers',
                '--Eating',
                '--Toileting',
                '-Meal Monitoring',
                '-Intake/Output, measurement',
                '-STOP and WATCH',
                '-Shower Skin Sheet',
                '-RNA Form (for RNAs)',
                'Other:',
            ],
            'PERINEAL CARE' => [
                '-OBSERVATIONS',
                '--Equipment are properly set up: gloves, washcloths, clean basin, mild soap, bath towel, bath blanket, incontinent pad, toilet tissue, linen saver pad, trash bag.',
                '--Optional: bedpan, peri--bottle, antiseptic soap, petroleum jelly, or zinc oxide cream, or Vitamin A and D ointment, and an ABD pad.',
                '--Obtain ointment or cream, as needed.',
                '--Fill basin two--thirds full of warm water (or fill peri--bottle with warm water).',
                '--Assemble equipment and provide privacy.',
                '--Wash hands and put on gloves.',
                '--Explain the procedure to the resident.',
                '--Adjust bed to working height and lower head of bed.',
                '-FEMALE RESIDENT:',
                '--Position resident on side to expose perineal area. Place incontinent pad underneath.',
                '--Clean, rinse and dry perineal area, starting at posterior vaginal vault opening and wiping front to back.',
                '--Re--position resident to supine position. Use bath blanket to cover resident while exposing perineum.',
                '--Ask resident to bend knees slightly and spread her legs. Wet clean washcloth.',
                '--Separate labia with one hand and wash with the other, using gentle downward strokes from front to back of perineum.',
                '--Use clean section of washcloth for each stroke.',
                '--Rinse thoroughly from front to back and pat area dry with bath towel.',
                '--Apply ordered ointments or creams.',
                '-MALE RESIDENT:',
                '--Assist to supine position and place incontinent pad under buttocks.',
                '--Drape legs for privacy and expose genital area.',
                '--Hold shaft of penis with one hand and wash with the other, beginning at the tip and working in a circular motion from the center to the periphery.',
                '--Use clean section of washcloth for each stroke.',
                '--Rinse thoroughly, using same circular motion.',
                '--For the uncircumcised resident, gently retract the foreskin and clean beneath it.',
                '--Rinse well but do not dry because moisture provides lubrication and prevents friction when replacing foreskin. Pull foreskin back over glans.',
                '--Wash rest of penis, using downward strokes toward scrotum. Rinse well and pat dry.',
                '--Clean scrotum, rinse well and pat dry.',
                '--Turn resident on side, clean bottom of scrotum and anal area. Rinse and dry.',
                '-AFTER CARE:',
                '--Reposition resident, remove bath blanket and incontinent pad, and replace bed linens.',
                '--Clean equipment; store appropriately; discard gloves; and wash hands.',
            ],
        ];

        $licensedNurseCompetencyItems = [
            'LICENSED NURSE COMPETENCY SKILLS' => [
                '-1. Communication',
                '--Telephone use- Etiquette',
                '--24 hour clinical report',
                '-2. Admission Process',
                '--Patient Data Collection',
                '--Braden Scale',
                '--Weekly Skin Assessment',
                '--Daily Pressure Ulcer Monitoring',
                '--Fall Risk Data Collection',
                '--Pain Evaluation',
                '--Pain Management Flow Sheet',
                '--Weekly Nursing Summary-includes weekly pain/skin evaluation',
                '--Bowel and Bladder Assessment',
                '--Elopement Risk Review',
                '--Physician Orders',
                '--MARs/TARs',
                '--Behavior Monitoring Records',
                '--Kardex',
                '--Faxing to Pharmacy',
                '--Dietary Communication',
                '--Therapy Communication',
                '--Lab Work/ Diagnostics',
                '--Consultation- Dental, Podiatry, Psychiatry, etc.',
                '--Admission Note',
                '--Charting/ Documentation',
                '--Vital Signs/Weights Records',
                '--Interim Care Plan Initiated',
                '--RFPR Initiated/Meal Intake Form',
                '-3. Transfer',
                '--Hospital',
                '--Same unit- Room/bed',
                '--Unit to Unit',
                '--Notification Process',
                '--Transfer form/documents',
                '-4. Policy and Procedure Review',
                '--Manuals',
                '-5. Interdisciplinary Care Planning',
                '--Update careplan per MD orders',
                '--Attendance careplan meetings',
                '--Kardex updating',
                '-6. Discharge Procedure',
                '--Instructions',
                '--Teaching',
                '--Home Evaluation',
                '--Completion of Discharge form and summary',
                '--Meds and Orders for Discharge',
                '-7. Death Procedure',
                '--Notification to RP and MD',
                '--Documentation',
                '--Post Mortem Care',
                '--MD order for release of body',
                '-8. Telephone Orders',
                '--Faxing to pharmacy',
                '-9. MAR - TAR',
                '--Completion/Updates',
                '-10. Unit Monitoring Functions',
                '--CNA Assignments',
                '--In-services',
                '--Chain of Command',
                '-11. Pharmacy',
                '--Ordering/Reordering',
                '--Return Meds',
                '--Narcotic Disposition',
                '--Signing for accountability with controlled meds',
                '--Ordering Procedures',
                '--Ordering IV Supplies',
                '-12. Dietary',
                '--Communication/changes',
                '--Meal monitoring',
                '--Snack monitoring',
                '--Thickened Liquids',
                '--Dysphagia Cautions',
                '--Enteral Orders',
                '--Dietary Restrictions',
                '-13. Weights',
                '--Admission Policy',
                '--Daily/Weekly/Monthly',
                '--Weight Methods (i.e. chair, bed, lift)',
                '--Weight Documentation',
                '-14. Restraints/Adaptive Equipment',
                '--Policy',
                '--Alternatives',
                '--Documentation- Weekly',
                '--Release times',
                '-15. Incidents/Accidents',
                '--Policy',
                '--Reports and Investigation',
                '--Patient/Employee/Visitor',
                '--Notification to RP and MD',
                '--72 hour Documentation in medical record',
                '--Nuero checks per protocol',
                '-16. Infection',
                '--Isolation Precautions',
                '--Documentation',
                '--Notification to RP and MD',
                '-17. Laboratory/Diagnostic Procedures',
                '--Specimen Collection',
                '--MD notification',
                '--Documentation',
                '-18. Gastrostomy Tube (REVIEW OF REINSERTION PROTOCOL)',
                '--Site Care',
                '--HOB elevated as per orders',
                '--Documentation',
                '--Placement Verification',
                '--Residual Check',
                '-19. Medication Pass (may attach Medication Pass checklist)',
                '--Med Pass observation using proper techniques',
                '--Behavior Monitoring Sheets',
                '--Securing Medications and syringes in a locked place',
                '--Oral Meds',
                '--Eye Drop Administration',
                '--SC/IM Administration',
                '--Glucometer Use',
                '--Reporting of Med Errors',
                '--Documentation',
                '--Privacy of Medical Record',
                '--Insulin Administration',
                '-20. Treatment/Procedures (may attach Treatment Skills Check)',
                '--Dressing change',
                '--Foley Catheter insertion/Care',
                '--Colostomy Care',
                '--Weekly Skin Checks',
                '--Documentation on Treatment Record',
                '-21. Respiratory Treatment/Procedures',
                '--Oxygen- nasal cannula, mask(s)',
                '--Oxygen Tanks- storage, use',
                '--Concentrators',
                '--Nebulizer',
                '--BIPAP/CPAP',
                '--Suctioning- trach, nasal, oral',
                '--Tracheostomy Care (may attach Tracheostomy Skills Check)',
                '-22. IV Therapy (may attach IV Skills Check)',
                '-- Certification',
                '-- Peripheral Insertion',
                '-- Line Care/Changing',
                '-- Site Care',
                '-- Hanging fluids',
                '-- Porta Cath',
                '-- Heparin Lock',
                '-- Central Line',
                '-- Flushes',
                '-23. Patient/Responsible party education--',
                '-- Demonstration',
                '-- Documentation',
                '-24. Documentation other than numbers 1-23',
                '-- S-B-A-R',
                '-- COC/Medicare Notes',
                '-- Monthly Psychotropic Medications Notes',
                '-25.  Others',
            ],

            'BLOOD TRANSFUSION COMPETENCY' => [
                '-Consider cultural and religious influences and educational level when administering blood and performing teaching with patients receiving blood and blood products.',
                '-Utilize principles of body substance isolation, explain procedure to patient, and educate patient about transfusion reaction symptoms to report to nurse.',
                '-Type and Screen is required for any red blood cell, whole blood product, platelet, or plasma administration.',
                '-Draw and send this sample to blood bank in accordance with policy. (Cryoprecipitate does not require Type and Screen.)',
                '-Assess the patient for a history of transfusions and transfusion reaction.',
                'Pre-transfusion checks to be performed prior to blood pick up:',
                '-1. Verify there is an ORDER TO TRANFUSE the blood product',
                '-2. Make sure there is a CONSENT FOR TRANSFUSION',
                '-3. Check patency of IV LINE, >22 gauge required, >20 gauge preferred. Establishes IV at KO rate or per physician\'s order.',
                '--a. Prime Y tubing with normal saline solution.',
                '--b. Follow procedure for starting large bore IV, greater than 20 gauge for adults.',
                '-4. Check PRE-TRANSFUSION VITAL SIGNS for acceptability. If the patient has a fever or any other cause for delay of transfusion, resolve prior to blood pick up',
                '-5. Check that the patient is wearing a BLOOD BANK ID BAND for any order to give RBCs',
                '-Check if blood is ready in Powerchart via BB Product Inquiry. Do NOT call the Blood Bank to ask if blood is ready. DO call the Blood Bank if you see the blood is not ready and would like a status update.',
                '-Bring a copy of the order and blood consent to the Blood Bank for blood pick up.',
                'Perform identification and verification checks with another RN/physician/perfusionist at the recipient\'s bedside. Do not start the transfusion if there is any discrepancy. Verify audibly and view concurrently the following:',
                '-a. Blood product with physician\'s written order.',
                '-b. Patient identity by any combination of any two of the following: patient name, date of birth, medical record number, last four digits of Social Security number, photograph identification',
                '-c. Patient name and medical record number on the identification wristband, the blood transfusion administration record (TAR) and the compatibility label on the blood product.',
                '-d. Verifying that the unit number, donor ABO/Rh, Patient ABO/Rh, expiration date and compatibility label are identical for the blood bag, compatibility label and TAR.',
                '-e. The TAR remains with the patient throughout transfusion. Both staff members sign the chart copy of the TAR and place in patient chart',
                '-Blood transfusions must be started as soon as possible after blood product issuance. There is no need to return the blood to the Blood Bank if not started within 30 minutes.',
                '-Blood transfusions must be completed within 4 hours from issuance, regardless of start time.',
                '-RN must stay at the patient\'s bedside for the first 15 minutes of transfusion.',
                '-Obtain vital signs:',
                '--a. Pre-transfusion vital signs are required, including a temperature. Vital signs must be taken within 30 minutes prior to beginning transfusion.',
                '--b. The nurse remains with the patient for the first 15 minutes of the transfusion, monitoring the patient closely for signs/symptoms of transfusion reaction.',
                '--c. Vital signs are taken 15 minutes after the transfusion is initiated, hourly during infusion, and upon completion of each unit.',
                '--d. Post-transfusion, within 2 hours after completion of transfusion',
                'Exception: in critical situation, take vital signs no more than 15 min. prior start of transfusion and at completion of unit.',
                '-Premedicate patient if ordered.',
                '-Attach blood to tubing. Spike the blood bag before hanging it up onto the pole. Do not piggyback blood.',
                '-Upon completion of administration of blood, flush tubing with normal saline unless otherwise ordered.',
                '-Change blood tubing after every 2 units or every 4 hours.',
                '-See blood transfusion policy for usual lengths of transfusion. (for whole blood 2-4 hours, must be infused within 4 hours of leaving Blood Bank)',
                '-If no transfusion reaction noted, dispose of blood bag and tubing in biohazard container.',
                '-If transfusion was documented in Cerner Bridge and the patient has a transfusion reaction after the transfusion has ended, the reaction must be documented in Bridge.',
                '-If the blood transfusion was started on paper, continue documentation on paper.',
                '-Always notify the Blood Bank if there is an emergent need for blood at extension 8315.',
                '-Document patient/family teaching.',
                '-See policy for blood transfusion reaction signs/symptoms and for steps to take if transfusion reaction occurs.',
            ],
            'BLOOD GLUCOSE MONITORING COMPETENCY' => [
                                '-User Assembles Equipment',
                                '--Blood Glucose Monitor',
                                '--Test strips',
                                '--Test solutions',
                                '--Finger stick supplies',
                                '-User Reviews Procedure',
                                '--States when coding is necessary.',
                                '--Turns monitor on and off accordingly.',
                                '--Verifies that the code numbers match.',
                                '-Performs Test Procedure',
                                '--Washes hands and puts on disposable gloves.',
                                '--Properly prepares lancet device.',
                                '--Turns monitor on.',
                                '--Checks expiration date of test strips.',
                                '--Inserts test strip.',
                                '--Obtains blood sample correctly.',
                                '--Applies blood to test strip correctly.',
                                '--Reads result.',
                                '--Documents result.',
                                '--Properly discards used test strip and blood-drawing supplies.',
                                '-Recalls Results from Memory',
                                '--Correctly records results stored in memory.',
                                '-Problem Solving. Refers to User\'s Manual if a problem with testing occurs.',
                                '--Getting a good drop of blood',
                                '--Display Messages',
                                '--Error Messages',
                                '-Quality Control Testing',
                                '--Checks expiration date of control solutions and test strips.',
                                '--Correctly performs control test.',
                                '--Follows proper troubleshooting procedures if control is not in the acceptable range.',
                                '--Is aware of the 24 hour Blood Glucose Customer Care number',
                                '-Cleaning',
                                '--States cleaning frequency for the exterior of the monitor.',
                                '--Properly describes cleaning procedure, including cleaning wipes to be used, for exterior of the monitor.',
                                '-Battery Replacement',
                                '--Demonstrates removal and replacement of batteries.',
            ],
            'TRACHEOSTOMY CARE COMPETENCY' => [
                                '-Equipment/Supplies',
                                '-Correct size & type of tube',
                                '-Suction machine',
                                '-Sterile suction catheter',
                                '-Connecting tubing',
                                '-Applicators',
                                '-Small brush or pipe cleaners',
                                '-Clamp & syringe',
                                '-Ointment for skin protection',
                                '-Hydrogen peroxide',
                                '-Sterile saline or water',
                                '-Tracheostomy ties or collar (Pre-cut ties or Velcro ties are recommended)',
                                '-4x4 gauze pads',
                                '-One set sterile gloves & one set clear gloves',
                                '-Basin',
                                '-Scissors',
                                '-Plastic bag for waste',
                                '-Tissues',
                                '-Emergency tracheostomy tube & reinsertion supplies',
                                '-Resuscitation bag',
                                '-Personal Protective equipment (i.e. face mask, face shield, eyewear)',
            ],

            'TREATMENT NURSE SKILLS COMPETENCY' => [
               '-1.  Ensure that Treatment Cart is adequately stocked.',
                '-2.  Bring Treatment Cart to resident\’s doorway.  Face cart towards doorway.  If you are able to visually see Treatment Cart from resident\’s bedside, it is not necessary to lock cart.  However, if you cannot see the cart, lock cart while you are doing the treatment in the resident\’s room.',
                '-3.  Review treatment order in Treatment Book.  Prepare supplies for treatment.  Pour normal saline into medicine cup.  If the order includes an ointment, do not bring tube into room.  Squirt just enough ointment into medicine cup. May use clean cotton tips or tongue depressors as applicators.  Make sure that you have at least two pairs of gloves.  They do not need to be sterile, unless it is a sterile procedure.',
                '-4.  Place supplies on resident\’s overhead bed table.  A paper plate may be used, plastic bag, etc, as a barrier, to lay supplies on top of.  Arrange dressings, cut tape, etc.',
                '-5.  Pull curtain around resident\’s bed for privacy.',
                '-6.  Introduce yourself to resident, and explain what you are going to do.',
                '-8.  Position resident in an appropriate position, being careful to provide privacy, if possible.',
                '-9.  Go to bathroom and wash hands.',
                '-10.  Put on gloves.',
                '-11.  Remove old dressing and place into plastic bag.  (You may position bag on top of resident\’s bed.)',
                '-12.  Remove gloves and discard into bag.',
                '-13.  Wash hands.',
                '-14.  Apply clean pair of gloves.',
                '-15.  Take a couple of non-sterile 4x4 or 2x2\’s, and saturate with the normal saline.  Clean resident\’s wound.  Note:  Do not wipe over a soiled area a second time with the same 4x4.   Place dressings into plastic bag.',
                '-16.  Remove gloves and place into plastic bag.',
                '-17.  Wash hands again.  (You may not need to wash hands if the wound does not have drainage.  Use your judgment)',
                '-18.  Apply clean pair of gloves to apply the final dressing.  You may be able to grasp the corners of the dressing, being careful not to touch the center of the dressing, or the wound of the resident, without putting on the final pair of gloves.  Again, use your judgment regarding the type of wound you are working with.',
                '-19.  Remove glove, and place into plastic bag.',
                '-20.  Cover resident and position to comfort.',
                '-21.  Wash hands.',
                '-22.  Remove bag, being careful not to touch the inside of the bag.  Place into trash receptacle on Treatment Cart.',
                '-23.  Sign Treatment Book for treatment.',		
            ],

            'MEDICATION ADMINISTRATION COMPETENCY' => [
                '-1. Nurse is wearing ID badge.',
                '-2. Medication Cart prepared for pass',
                '-3. Medication Cart was organized and secured during pass.',
                '-4. MAR covered when out of visual control.',
                '-5. Maintaining proper Infection Control.',
                '-6. Nurse correctly read the order from the medication record and RX label.',
                '-7. Drug ID triple checked before med administration.',
                '-8. Oral liquids measured at eye level.',
                '-9. Oral liquid syringe used for “odd” doses.',
                '-10. Meds crushed only by policy.',
                '-11. Suspensions shake before measurement.',
                '-12. Nurse knocked or announced on resident\’s door before entering.',
                '-13. Resident properly identified before med administration (picture ID or armband).',
                '-14. Nurse informed resident of medications they were giving.',
                '-15. Resident properly positioned before medication administration.',
                '-16. Vital signs (apical pulse and/or blood pressure) were taken if applicable.',
                '-17. Medications via gastric tube were administered correctly (1-placement, 2-residule, 3-flush).',
                '-18. Eye medications administered correctly (handwashing – pre & post).',
                '-19. Inhaler medications administered correctly.',
                '-20. Site for injections properly rotated and show date & initials.',
                '-21. Transdermal patches rotated and show date & initials. Nurses Check patch for placement.',
                '-22. All doses administered by appropriate route (e.g. SL).',
                '-23. Meds properly charted after consumption, including Narcotic charting.',
                '-24. Refused or PRN doses fully documented.',
                '-25. Medication syringes are cleaned Q use. Spacers cleaned daily.',
                '-26. Medication pass was in time compliance.',
                '-27. Adequate fluids given for medications (i.e., Metamucil, NSAIDS, KCl).',
                '-28. Pain assessment done during medication pass.',
            ],
        ];

        $order = 0;
        $this->seedCompetencySet($dsdCompetencyItems, $dsdPositionIds, $order);

        if ($licensedNursePositionIds !== []) {
            $this->seedCompetencySet($licensedNurseCompetencyItems, $licensedNursePositionIds, $order);
        }

        if ($cnaPositionIds !== []) {
            $this->seedCompetencySet($cnaCompetencyItems, $cnaPositionIds, $order);
        }
    }
}