<?php

namespace Database\Seeders;

use App\Models\EmployeeCompetencyItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeCompetencyItemsSeeder extends Seeder
{
    protected function getPositionIdsByTitles(array|string $titles): array
    {
        $titles = array_values(array_filter(array_map('trim', (array) $titles)));

        if ($titles === []) {
            return [];
        }

        return DB::table('positions')
            ->whereIn('title', $titles)
            ->orderBy('id')
            ->pluck('id')
            ->map(fn ($id) => (int) $id)
            ->all();
    }

    protected function seedCompetencySet(array $competencyItems, array $positionIds, int &$order): void
    {
        foreach ($competencyItems as $section => $items) {
            foreach ($items as $item) {
                EmployeeCompetencyItem::query()->updateOrCreate(
                    [
                        'section' => $section,
                        'item' => $item,
                        'order' => $order,
                    ],
                    [
                        'position_ids' => $positionIds,
                    ]
                );

                $order++;
            }
        }
    }

    public function run(): void
    {
        $directorOfStaffDevelopmentPositionIds = $this->getPositionIdsByTitles('Director of Staff Development');
        $dsdPositionIds = $directorOfStaffDevelopmentPositionIds !== [] ? $directorOfStaffDevelopmentPositionIds : ['global'];
        $cnaPositionIds = $this->getPositionIdsByTitles('Certified Nursing Assistant');
        $licensedNursePositionIds = $this->getPositionIdsByTitles([
            'Director of Nursing',
            'Registered Nurse',
            'Licensed Vocational Nurse',
            'Licensed Nurse',
            'Charge Nurse',
            'IP Nurse',
        ]);

        $dsdCompetencyItems = [
            'IN-SERVICE EDUCATION PROGRAM MANAGEMENT' => [
                'Annual In-Service Plan (meets **California Title 22 & CMS requirements)',
                'Mandatory Nursing In-Services (Skills, Clinical Competency)',
                'Mandatory In-Services for ALL Staff (Abuse, Infection Control, Safety, HIPAA)',
                'Survey-Driven Education',
                'Competency Validation (Return Demonstrations)',
                'Education Tracking Logs (Attendance, Make-ups)',
                'CNA 12-hour Annual In-Service Compliance',
                'Nurse Continuing Education Tracking',
            ],
            'ORIENTATION PROGRAM MANAGEMENT' => [
                'New Hire Orientation (All Departments)',
                'General Orientation (Facility Policies, Emergency Preparedness)',
                'Clinical Orientation (Nursing-specific skills validation)',
                'CNA Orientation and Preceptor Program',
                'Agency/Registry Staff Orientation',
                'Orientation Checklist Completion Monitoring',
            ],
            'SKILLS COMPETENCY PROGRAM (ALL DEPARTMENTS)' => [
                'Licensed Nurses Annual Skills',
                'CNA Skills Competency',
                'DON Competency Validation',
                'Infection Preventionist Competency',
                'MDS Coordinator Competency',
                'Dietary Staff Competency',
                'Social Services Competency',
                'Activities Competency',
                'EVS/Maintenance/Laundry',
            ],
            'LICENSES, CERTIFICATIONS TRACKING' => [
                'RN/LVN (including Registry Staff)',
                'CNA (including Registry Staff)',
                'REHAB STAFF-Secure from Bio-Pacific',
                'CPR-RN/LVN and PT/OT/SLP (from Bio-Pacific)',
                'Subacute Ventilator Care Certification (RN/LVN)',
            ],
            'HUMAN RESOURCES COORDINATION' => [
                'Background Checks Verified',
                'Annual Performance Evaluations Completed',
                'Employee Files Audit (completeness)',
                'I-9 Compliance',
                'UKG/Time Clock Correction',
                'Leave of Absence Tracking',
                'Payroll Adjustment Coordination',
            ],
            'STAFFING & PPD MONITORING' => [
                'Daily PPD Monitoring',
                'Staffing Posting Compliance',
                'CNA Schedules (monthly)',
                'Daily Assignments Reviewed',
            ],
            'WORKERS COMP & SAFETY PROGRAM' => [
                'OSHA Log Maintenance',
                'Workmen’s Compensation Tracking',
                'Modified Duty Program Monitoring',
                'Safety Committee Lead',
            ],
            'COMMITTEE PARTICIPATION' => [
                'Infection Control Committee',
                'QAPI Committee',
                'Education Reports to QAPI',
                'PIP Support (Falls, Wounds, Psychotropics)',
            ],
            'CLINICAL OVERSIGHT & EDUCATION ROUNDS' => [
                'Rounds-Daily (Monthly with IP)',
                'Direct Care Observations/On-the-spot In-services',
            ],
            'INFECTION PREVENTION SUPPORT' => [
                'Isolation/Transmission-Based Precautions Education',
                'COVID-19 protocols and reporting requirements',
                'Isolation/Transmission-Based Precautions Education',
                'Outbreak Education Response',
            ],
            'EMPLOYEE HEALTH PROGRAM' => [
                'Initial TB Screening',
                'Annual TB Screening',
                'Annual TB Questionnaire',
                'CXR for Positive PPD + MD Clearance',
                'CXR every 5 years or as MD ordered',
                'Initial Physical Exam',
                'Annual Physical Exam',
                'COVID-19 Vaccination Program',
                'Annual Flu Vaccine',
                'Hepatitis B Vaccine',
                'Childhood Diseases Immunization',
            ],
            'POLICIES AND PROCEDURES MANAGEMENT' => [
                'Emergency/Disaster, Fire Safety- RED Binders',
                'Abuse/Neglect/Grievance Binder',
                'MCN access for ALL P&Ps',
                'Lippincott Nursing Procedures Book',
                'Pharmacy LTC Manual and IV Therapy Manual',
            ],
            'RESTORATIVE NURSING PROGRAM' => [
                'RNA Weekly Meeting and Notes',
                'Updating RNA Orders and Care Plans',
                'RNA Monthly Recap',
            ],
            'EHR / MATRIXCARE COMPETENCY' => [
                'Staff Training/ Order Entry / Clinical Workflow Training',
                'Documentation Audits',
                'Dashboard Monitoring (alerts/compliance)',
            ],
            'SURVEY READINESS' => [],
        ];

        $cnaCompetencyItems = [
            'CNA SKILLS CHECKLIST' => [
                'Ambulation',
                'Back Rub',
                'Bed Bath',
                'Bed Making, Occupied',
                'Bed Making, Unoccupied',
                'Bed Pan, Urinal',
                'Bladder Management/Toileting',
                'Bladder Patterning/Retraining',
                'Body Mechanics- Gen. Rules',
                '-Lifting and Moving',
                '-Positioning',
                '-Transferring',
                'Catheter Care',
                'Choking, Heimlich Maneuver',
                'Dementia Training',
                'Dialysis',
                'Dressing/undressing',
                'Emergency Procedures/Reporting',
                'Feeding, Special Issues',
                '-Tray service',
                '-Dining Program',
                'Feeding Tubes',
                '-Gastric',
                '-Jejunostomy',
                '-Nasogastric',
                'Fluid Restrictions, Dot system',
                'Grooming',
                'Hand Washing',
                'Incontinence Care/Perineal Care',
                'Infection Control, waste',
                'Linen Handling',
                'Mechanical Lift',
                'Oral Hygiene',
                'Ostomy protocol review',
                'Oxygen, CPAP, BiPAP Tubing Care',
                'Tracheostomy-ADL care (CNA scope of practice)',
                'Pain Identification/Management',
                'Protective Devices',
                'Post-mortem care',
                'Range of motion',
                'Restraint Devices',
                'Scales, weighing',
                'Shaving',
                'Shower / Bathing',
                'Specimen Collection',
                'Splints/Orthosis',
                'Standard Precautions',
                'Use of Cane',
                '-Walker',
                '-Prosthetic devices',
                '-Bed controls',
                '-Wheelchair',
                'Vital signs',
                '-Temperature, axilla',
                '-Temperature, ear',
                '-Temperature, oral',
                '-Temperature, rectal',
                '-Pulse Rate',
                '-Respiratory Rate',
                '-Blood Pressure',
                'Documentation:',
                '-RFPR',
                '--Bed mobility',
                '--Transfers',
                '--Eating',
                '--Toileting',
                '-Meal Monitoring',
                '-Intake/Output, measurement',
                '-STOP and WATCH',
                '-Shower Skin Sheet',
                '-RNA Form (for RNAs)',
                'Other:',
            ],
            'PERINEAL CARE' => [
                '-OBSERVATIONS',
                '--Equipment are properly set up: gloves, washcloths, clean basin, mild soap, bath towel, bath blanket, incontinent pad, toilet tissue, linen saver pad, trash bag.',
                '--Optional: bedpan, peri--bottle, antiseptic soap, petroleum jelly, or zinc oxide cream, or Vitamin A and D ointment, and an ABD pad.',
                '--Obtain ointment or cream, as needed.',
                '--Fill basin two--thirds full of warm water (or fill peri--bottle with warm water).',
                '--Assemble equipment and provide privacy.',
                '--Wash hands and put on gloves.',
                '--Explain the procedure to the resident.',
                '--Adjust bed to working height and lower head of bed.',
                '-FEMALE RESIDENT:',
                '--Position resident on side to expose perineal area. Place incontinent pad underneath.',
                '--Clean, rinse and dry perineal area, starting at posterior vaginal vault opening and wiping front to back.',
                '--Re--position resident to supine position. Use bath blanket to cover resident while exposing perineum.',
                '--Ask resident to bend knees slightly and spread her legs. Wet clean washcloth.',
                '--Separate labia with one hand and wash with the other, using gentle downward strokes from front to back of perineum.',
                '--Use clean section of washcloth for each stroke.',
                '--Rinse thoroughly from front to back and pat area dry with bath towel.',
                '--Apply ordered ointments or creams.',
                '-MALE RESIDENT:',
                '--Assist to supine position and place incontinent pad under buttocks.',
                '--Drape legs for privacy and expose genital area.',
                '--Hold shaft of penis with one hand and wash with the other, beginning at the tip and working in a circular motion from the center to the periphery.',
                '--Use clean section of washcloth for each stroke.',
                '--Rinse thoroughly, using same circular motion.',
                '--For the uncircumcised resident, gently retract the foreskin and clean beneath it.',
                '--Rinse well but do not dry because moisture provides lubrication and prevents friction when replacing foreskin. Pull foreskin back over glans.',
                '--Wash rest of penis, using downward strokes toward scrotum. Rinse well and pat dry.',
                '--Clean scrotum, rinse well and pat dry.',
                '--Turn resident on side, clean bottom of scrotum and anal area. Rinse and dry.',
                '-AFTER CARE:',
                '--Reposition resident, remove bath blanket and incontinent pad, and replace bed linens.',
                '--Clean equipment; store appropriately; discard gloves; and wash hands.',
            ],
        ];

        $licensedNurseCompetencyItems = [
            'LICENSED NURSE COMPETENCY SKILLS' => [
                '-1. Communication',
                '--Telephone Use-Etiquette, Answering/Transferring Calls, Paging',
                '--24-Hour Shift Report (Daily Shift Report)',
                '--Change of Shift Rounds (incoming and outgoing shifts)',
                '--E-mail (if applicable)',
                '-2. Policies and Procedures',
                '--MCN Network',
                '--ViewMasteRx (PharMerica)',
                '--Manuals',
                '-3. Admission Process',
                '--Physician Orders-including verification, faxing to Pharmacy or ordering medications via MatrixCare',
                '--eMAR (MARs/TARs)',
                '--Behavior Monitoring Records in MatrixCare',
                '--Consent to Treat',
                '--Informed Consents-use of psychotropics, side rails, restraints',
                '--Bedhold Consent Form',
                '--Dietary Communication',
                '--Therapy Communication',
                '--Laboratory/Diagnostic Orders',
                '--Consults Orders-eye, dental, hearing, podiatry, psychiatry',
                '--Weight and Vital Signs Records',
                '--Resident Data Collection',
                '--Braden Scale-weekly x 4',
                '--If with Wound, Wound Assessment Form',
                '--If with Pressure Injury, Daily Pressure Injury Monitoring',
                '--Pain Evaluation',
                '--Pain Management Flowsheet',
                '--Fall Risk Data Collection',
                '--Bowel and Bladder Assessment',
                '--Bowel and Bladder Patterning-Program',
                '--Elopement Risk Assessment',
                '--If Elopement Risk, Elopement Identification Form',
                '--Side Rail Evaluation-including Risk for Entrapment',
                '--Pre-Restraints Assessment',
                '--Smoking Assessment',
                '--If a Smoker, initiation of Smoking Contract',
                '--Trauma Informed Care',
                '--Tobacco, Alcohol, Prescribed Drugs, Substance Use (TAPS) 1-2',
                '--MDS PHQ 2-9 Mood Screening',
                '--MDS Section E Behavior Monitoring',
                '--Abnormal Involuntary Movement Scale (AIMS) Test',
                '--Self-Administration of Medications Assessment',
                '--Care Plan Essentials (CPE)',
                '--Interim Care Plan',
                '--MatrixCare Documentation and Point of Care-see checklist',
                '-4. Telephone Orders',
                '--Documentation, Faxing to Pharmacy or Ordering through MatrixCare',
                '-5. Medication Administration Record (MAR)/Treatment Administration Record (TAR)',
                '--Completion/Update in MatrixCare',
                '--Paper Form MAR/TAR when MatrixCare is Offline',
                '-6. Pharmacy',
                '--Ordering/Reordering [CA is a “no return of medications” state]',
                '--Controlled Medications Storage and Disposition/Destruction',
                '--Signing for Accountability of Controlled Medications',
                '---Signing the Controlled Medications Declining Sheets',
                '---Counting Procedures',
                '--Ordering IV Supplies',
                '-7. Dietary',
                '--Communication/Changes',
                '--Meal Monitoring',
                '--Snacks Monitoring',
                '--Thickened Liquids',
                '--Dysphagia Cautions',
                '--Enteral Orders',
                '--Dietary Restrictions',
                '--Hydration DOT System',
                '-8. Weights/Hydration',
                '--Policy-Review the Weights/Hydration Pathway',
                '--Admission Weight, then weekly X 4',
                '--Daily/Weekly/Monthly',
                '--Weight Methods (i.e., chair, bed, mechanical lift)',
                '---Mechanical Lift transfers-see checklist',
                '--Weights Documentation',
                '--Weekly Nursing Summary-indicate weight variances, meal intake changes, hydration status, intake and output summary',
                '--Hydration DOT System',
                '--Care Plan',
                '-9. Interdisciplinary Care Planning',
                '--Initiate/Update Care Plan for any Changes of Condition, Physician Orders',
                '--Attendance in Care Conferences',
                '--Care Plan Essentials (CPE)',
                '-10. Transfer (review the checklist)',
                '--Hospital',
                '--Same Nursing Unit-Room/Bed',
                '--Unit to Unit',
                '--Notification Process',
                '--Transfer Form/Documents',
                '--Ombudsman Notification for Hospital Discharge',
                '-11. Discharge (review the checklist)',
                '--Home, Assisted Living, Board and Care',
                '--AMA/AFA',
                '--Instructions',
                '--Completion of Discharge Forms/Documents',
                '--Medications and Orders for Discharge',
                '--Ombudsman Notification by Social Services',
                '-12. Death Procedure',
                '--Notification of Physician, Resident Representative',
                '--Documentation',
                '--Postmortem Care',
                '--Physician Order for release of body',
                '-13. Restraints',
                '--Policy',
                '--Alternatives',
                '--Physician Order with reason for use, release times',
                '--Informed Consent',
                '--Weekly Documentation-Nursing Weekly Summary',
                '-14. Psychotropics',
                '--Policy',
                '--Physician Order-with specific diagnosis, behavior to be monitored',
                '--PRN x 14 days, then reevaluate',
                '--eMAR/MAR with specific behavior and side effects monitoring per medication',
                '--Informed Consents (every 6 months, any increase/decrease of dose with antipsychotic)',
                '--Care Plan',
                '--Gradual Dose Reduction',
                '--Weekly Nursing Summary-response to use',
                '--Monthly Licensed Nurse Psychotropic Notes-one per medication',
                '--Monthly IDT Psychotropic Meeting/Notes',
                '-15. Incidents/Accidents',
                '--Policy',
                '--Reports and Investigation',
                '--If possible abuse/neglect case, follow policy, mandated reporter',
                '--Resident, Employee, Visitor',
                '--Notification of Physician and Resident Representative',
                '--Documentation-SBAR (initial), then COC q 64 more hours, total of q shift x 72 hours (may also document in Progress Notes when indicated)',
                '--Care Plan',
                '--IDT Risk Meeting weekly x 4',
                '-16. Falls/Injury',
                '--Policy-review of the Falls Pathway, Fall Prevention, Falling Stars Program (yellow and red stars), Safety Alarms',
                '--Personal Safety Alarm monitoring q shift',
                '--Documentation-SBAR (initial), then q shift x 64 hours COC; total of q shift x 72 hours (may also document in Progress Notes when indicated)',
                '--Neuro check after every fall incident/accident-witnessed or unwitnessed',
                '--Fall Risk Evaluation on admission, after every fall incident/accident occurrence, quarterly',
                '--Care Plan-after every fall with new interventions',
                '--IDT Risk Meeting-weekly x 4 post incident/accident',
                '-17. Wounds',
                '--Policy-Follow Pathway and Reference Tool',
                '--Initial Skin Assessment on Admission-if with wound or skin issues, initiate the wound assessment form (pressure or non-pressure) on admission, then weekly thereafter until healed.',
                '--For Pressure Ulcer/Injury-Daily Monitoring Form (by 3-11 shift)',
                '--Nursing Weekly Summary-focus on presence of wound(s), turning and positioning monitored, offloading of extremities, toileting assistance, meals assistance',
                '--Care Planning-one site per care plan',
                '--Wound Risk Worksheet-if avoidable or unavoidable',
                '--IDT Risk Meeting-weekly for facility acquired and worsening wounds',
                '-18. Infection Control',
                '--Isolation Protocols-COVID-19, Standard Precautions, Enhanced Barrier Precautions (EBP), Transmission-Based (Droplet, Contact, Airborne); initiating and discontinuing isolation precautions',
                '--Reportable',
                '--Documentation-including McGeer criteria',
                '--Care Planning',
                '--Notification of Physician, Resident Representative',
                '--Hand Hygiene',
                '--Donning/Doffing of Personal Protective Equipment (PPE)',
                '-19. Respiratory Treatment Procedures',
                '--Oxygen-nasal cannula, masks',
                '--Oxygen Tanks-storage, use',
                '--Concentrators',
                '--Nebulizers',
                '--BiPAP/CPAP',
                '--Suctioning-nasal, oral, tracheostomy',
                '--Tracheostomy Care (may attach the Skills Checklist)',
                '--If Subacute Licensed Nurse, attach the specific subacute certification and training',
                '-20. Diagnostic/Laboratory Procedures',
                '--Specimen Collection',
                '--Physician Notification',
                '--Documentation',
                '-21. Enteral Feeding (Nasogastric, Gastrostomy, Jejunostomy)',
                '--Policy',
                '--Placement Verification',
                '--Residual Check',
                '--Site Care',
                '--Reinsertion',
                '--Head of Bed (HOB) elevation as per physician orders',
                '--Documentation',
                '-22. Medication Pass/Administration (may attach the Medication Pass Checklist)',
                '--Medication Pass Observation using proper techniques',
                '--Behavior Monitoring Sheets',
                '--Pain Flowsheets',
                '--Securing Medications and syringes in a locked space',
                '--Double Locking of Controlled Medications',
                '--Proper Labeling and Storage of Medications',
                '--Oral Medications',
                '--Eye Drops Administration',
                '--Ear Drops Administration',
                '--Subcutaneous (SQ)/Intramuscular (IM) Administration',
                '--Insulin Administration-precautionary measures with short acting vs. long acting',
                '--Glucometer Use (may attach the Skills Checklist)',
                '--Medication Cart',
                '--Medication Room and Storage-include temperature logs',
                '--Discarding of Medications-Controlled and Non-Controlled, Fentanyl patch',
                '--Documentation',
                '--Reporting of Medication Errors',
                '--Privacy of Medical Records',
                '-23. Treatment Pass/Administration (may attach the Treatment Skills Checklist)',
                '--Dressing Change',
                '--Foley Catheter Insertion and Care',
                '--Suprapubic Catheter Insertion and Care',
                '--Nephrostomy Tube Insertion (Physician only) and Care',
                '--Colostomy/Ileostomy/Ileal Conduit Care',
                '--Rectal Tube Care',
                '--Weekly Skin Checks-documented in Nursing Weekly Summary',
                '--Documentation on Treatment Record',
                '--Weekly Wound Assessment/Evaluation',
                '-24. Intravenous (IV) Therapy (may attach IV Skills Check)',
                '--Certification',
                '--Peripheral Insertion',
                '--Line Care/Changing',
                '--Site Care',
                '--Hanging IV Fluids',
                '--IV Antibiotics Administration-RN Only',
                '--IV Medications Administration-RN Only',
                '--Porta Catheter',
                '--Heparin Lock',
                '--Central Line, PICC',
                '--Flushes',
                '-25. Direct Care',
                '--Policies',
                '--Turning and Positioning/Repositioning',
                '--Transfers-1, 2 or more person assist, mechanical lift (refer to the skills checklist)',
                '--Assist with Toileting, Bed Bath, Shower, Incontinence Care/Perineal Care',
                '--Assist with Feeding of Resident',
                '-26. Unit Monitoring Functions',
                '--Licensed Nurses’ and Certified Nursing Assistants’ Assignments',
                '--Outgoing/Incoming Shifts’ Reports',
                '--In-services',
                '--Chain of Command',
                '-27. Resident/Resident Representative Education',
                '--Demonstration',
                '--Documentation',
                '-28. MatrixCare and Point of Care (POC) Checklist',
                '--Review Protocols',
                '-29. OTHER',
            ],

            'BLOOD ADMINISTRATION COMPETENCY' => [
                '-Consider cultural and religious influences and educational level when administering blood and performing teaching with patients receiving blood and blood products.',
                '-Utilize principles of body substance isolation, explain procedure to patient, and educate patient about transfusion reaction symptoms to report to nurse.',
                '-Type and Screen is required for any red blood cell, whole blood product, platelet, or plasma administration. Draw and send this sample to blood bank in accordance with policy. (Cryoprecipitate does not require Type and Screen.)',
                '-Assess the patient for a history of transfusions and transfusion reaction.',
                'Pre-transfusion checks to be performed prior to blood pick up:',
                '-1. Verify there is an ORDER TO TRANFUSE the blood product',
                '-2. Make sure there is a CONSENT FOR TRANSFUSION',
                '-3. Check patency of IV LINE, >22 gauge required, >20 gauge preferred. Establishes IV at KO rate or per physician\'s order.',
                '--a. Prime Y tubing with normal saline solution.',
                '--b. Follow procedure for starting large bore IV, greater than 20 gauge for adults.',
                '-4. Check PRE-TRANSFUSION VITAL SIGNS for acceptability. If the patient has a fever or any other cause for delay of transfusion, resolve prior to blood pick up',
                '-5. Check that the patient is wearing a BLOOD BANK ID BAND for any order to give RBCs',
                '-Check if blood is ready in Powerchart via BB Product Inquiry. Do NOT call the Blood Bank to ask if blood is ready. DO call the Blood Bank if you see the blood is not ready and would like a status update.',
                '-Bring a copy of the order and blood consent to the Blood Bank for blood pick up.',
                'Perform identification and verification checks with another RN/physician/perfusionist at the recipient\'s bedside. Do not start the transfusion if there is any discrepancy. Verify audibly and view concurrently the following:',
                '-a. Blood product with physician\'s written order.',
                '-b. Patient identity by any combination of any two of the following: patient name, date of birth, medical record number, last four digits of Social Security number, photograph identification',
                '-c. Patient name and medical record number on the identification wristband, the blood transfusion administration record (TAR) and the compatibility label on the blood product.',
                '-d. Verifying that the unit number, donor ABO/Rh, Patient ABO/Rh, expiration date and compatibility label are identical for the blood bag, compatibility label and TAR.',
                '-e. The TAR remains with the patient throughout transfusion. Both staff members sign the chart copy of the TAR and place in patient chart',
                '-Blood transfusions must be started as soon as possible after blood product issuance. There is no need to return the blood to the Blood Bank if not started within 30 minutes.',
                '-Blood transfusions must be completed within 4 hours from issuance, regardless of start time.',
                '-RN must stay at the patient\'s bedside for the first 15 minutes of transfusion.',
                'Follow Infection Protocol related to Isolation Precautions-Standard, Enhanced Barrier Precautions (EBP), Transmission-Based Precautions (EBP)-airborne, contact, droplet, proper hand hygiene, proper use of PPE.',
                '-Obtain vital signs:',
                '--a. Pre-transfusion vital signs are required, including a temperature. Vital signs must be taken within 30 minutes prior to beginning transfusion.',
                '--b. The nurse remains with the patient for the first 15 minutes of the transfusion, monitoring the patient closely for signs/symptoms of transfusion reaction.',
                '--c. Vital signs are taken 15 minutes after the transfusion is initiated, hourly during infusion, and upon completion of each unit.',
                '--d. Post-transfusion, within 2 hours after completion of transfusion',
                'Exception: in critical situation, take vital signs no more than 15 min. prior start of transfusion and at completion of unit.',
                '-Premedicate patient if ordered.',
                '-Attach blood to tubing. Spike the blood bag before hanging it up onto the pole. Do not piggyback blood.',
                '-Upon completion of administration of blood, flush tubing with normal saline unless otherwise ordered.',
                '-Change blood tubing after every 2 units or every 4 hours.',
                '-See blood transfusion policy for usual lengths of transfusion. (for whole blood 2-4 hours, must be infused within 4 hours of leaving Blood Bank)',
                '-If no transfusion reaction noted, dispose of blood bag and tubing in biohazard container.',
                '-If transfusion was documented in Cerner Bridge and the patient has a transfusion reaction after the transfusion has ended, the reaction must be documented in Bridge.',
                '-If the blood transfusion was started on paper, continue documentation on paper.',
                '-Always notify the Blood Bank if there is an emergent need for blood at extension 8315.',
                '-Document patient/family teaching.',
                '-See policy for blood transfusion reaction signs/symptoms and for steps to take if transfusion reaction occurs.',
            ],
            'BLOOD GLUCOSE SYSTEM SKILLS COMPETENCY' => [
                                '-User Assembles Equipment',
                                '--Blood Glucose Monitor',
                                '--Test strips',
                                '--Test solutions',
                                '--Finger stick supplies',
                                '-User Reviews Procedure',
                                '--States when coding is necessary.',
                                '--Turns monitor on and off accordingly.',
                                '--Verifies that the code numbers match.',
                                '-Performs Test Procedure',
                                '--Performs proper hand hygiene and puts on disposable gloves.',
                                '--Properly prepares lancet device.',
                                '--Turns monitor on.',
                                '--Checks expiration date of test strips.',
                                '--Inserts test strip.',
                                '--Obtains blood sample correctly.',
                                '--Applies blood to test strip correctly.',
                                '--Reads result.',
                                '--Documents result.',
                                '--Properly discards used test strip and blood-drawing supplies.',
                                '--Removes gloves and performs proper hand hygiene.',
                                '-Recalls Results from Memory',
                                '--Correctly records results stored in memory.',
                                '-Problem Solving. Refers to User\'s Manual if a problem with testing occurs.',
                                '--Getting a good drop of blood',
                                '--Display Messages',
                                '--Error Messages',
                                '-Quality Control Testing',
                                '--Checks expiration date of control solutions and test strips.',
                                '--Correctly performs control test.',
                                '--Follows proper troubleshooting procedures if control is not in the acceptable range.',
                                '--Is aware of the 24 hour Blood Glucose Customer Care number',
                                '-Cleaning',
                                '--States cleaning frequency for the exterior of the monitor.',
                                '--Properly describes cleaning procedure, including cleaning wipes to be used, for exterior of the monitor.',
                                '-Battery Replacement',
                                '--Demonstrates removal and replacement of batteries.',
            ],
            
            'TRACHEOSTOMY CARE COMPETENCY' => [
                                '-Equipment/Supplies',
                                '--Correct size & type of tube',
                                '--Suction machine',
                                '--Sterile suction catheter',
                                '--Connecting tubing',
                                '--Applicators',
                                '--Small brush or pipe cleaners',
                                '--Clamp & syringe',
                                '--Ointment for skin protection',
                                '--Hydrogen peroxide',
                                '--Sterile saline or water',
                                '--Tracheostomy ties or collar (Pre-cut ties or Velcro ties are recommended)',
                                '--4x4 gauze pads',
                                '--One set sterile gloves & one set clear gloves',
                                '--Basin',
                                '--Scissors',
                                '--Plastic bag for waste',
                                '--Tissues',
                                '--Emergency tracheostomy tube & reinsertion supplies',
                                '--Resuscitation bag',
                                '--Personal Protective equipment (i.e. face mask, face shield, eyewear)',
                                '-1. Follow Infection Control Protocols and Isolation Protocols-Standard Precautions, Enhanced Barrier Precautions (EBP), Transmission-Based Precautions (TBP)-airborne, contact, droplet.',
                                '-2. Assemble equipment and bring to the bedside.',
                                '-3. Identify and explain procedure to resident and provide privacy.',
                                '-4. Wash hands, put on personal protective equipment-mask, gown, goggles/face shield if appropriate. Follow proper donning of PPE.',
                                '-5. Place resident in semi-Fowler position unless medically contraindicated.',
                                '-6. Open sterile catheter using aseptic technique.',
                                '-7. Put on sterile gloves.',
                                '-8. Using sterile technique, suction tracheostomy tube.',
                                '-9. Using your less dominant hand as your dirty hand, pour peroxide or solution in basin.',
                                '-10. Using your sterile hand unlock inner cannula of tracheostomy tube, remove, place in basin and allow to soak.',
                                '-11. Remove gloves and put on clean gloves.',
                                '-12. Remove tracheostomy dressing.',
                                '-13. Using applicators and peroxide, clean skin around tracheostomy tube, removing all exudate and drainage - DO NOT ALLOW any solution to enter outer tracheostomy tube or opening.',
                                '-14. Using applicators and brush, clean inner cannula well||Note: Avoid touching cannula itself with gloved hand.',
                                '-15. Rinse with sterile saline or water and drain on sterile 4x4.',
                                '-16. Suction resident.',
                                '-17. Insert inner cannula and lock in place.',
                                '-18. If used, fasten pre-cut ties or Velcro ties to the side, 3-4 inches from the tube opening, not behind the neck.||A second individual may be needed to assist.',
                                '-19. Prepare tracheostomy dressing by making a 3" cut down the middle of a 4x4" gauze pad, or use a commercial precut 4x4" gauze, then fit around the tube and underneath the ties.',
                                '-20. Follow proper doffing of PPE (i.e., gloves, mask, gown, goggles/face shield)',
                                '-21. Leave resident in comfortable position with call light within reach.',
                                '-22. Dispose of supplies and linen in designated container.',
                                '-23. Wash hands.',
            ],

            'TREATMENT NURSE SKILLS COMPETENCY' => [
               '-1.  Ensure that Treatment Cart is adequately stocked.',
                '-2.  Bring Treatment Cart to resident\’s doorway.  Face cart towards doorway.  If you are able to visually see Treatment Cart from resident\’s bedside, it is not necessary to lock cart.  However, if you cannot see the cart, lock cart while you are doing the treatment in the resident\’s room.',
                '-3.  Review treatment order in Treatment Book.  Prepare supplies for treatment.  Pour normal saline into medicine cup.  If the order includes an ointment, do not bring tube into room.  Squirt just enough ointment into medicine cup. May use clean cotton tips or tongue depressors as applicators.  Make sure that you have at least two pairs of gloves.  They do not need to be sterile, unless it is a sterile procedure.',
                '-4.  Place supplies on resident\’s overhead bed table.  A paper plate may be used, plastic bag, etc, as a barrier, to lay supplies on top of.  Arrange dressings, cut tape, etc.',
                '-5.  Pull curtain around resident\’s bed for privacy.',
                '-6.  Introduce yourself to resident, and explain what you are going to do.',
                '-8.  Position resident in an appropriate position, being careful to provide privacy, if possible.',
                '-9.  Go to bathroom and wash hands.',
                '-10.  Put on gloves.',
                '-11.  Remove old dressing and place into plastic bag.  (You may position bag on top of resident\’s bed.)',
                '-12.  Remove gloves and discard into bag.',
                '-13.  Wash hands.',
                '-14.  Apply clean pair of gloves.',
                '-15.  Take a couple of non-sterile 4x4 or 2x2\’s, and saturate with the normal saline.  Clean resident\’s wound.  Note:  Do not wipe over a soiled area a second time with the same 4x4.   Place dressings into plastic bag.',
                '-16.  Remove gloves and place into plastic bag.',
                '-17.  Wash hands again.  (You may not need to wash hands if the wound does not have drainage.  Use your judgment)',
                '-18.  Apply clean pair of gloves to apply the final dressing.  You may be able to grasp the corners of the dressing, being careful not to touch the center of the dressing, or the wound of the resident, without putting on the final pair of gloves.  Again, use your judgment regarding the type of wound you are working with.',
                '-19.  Remove glove, and place into plastic bag.',
                '-20.  Cover resident and position to comfort.',
                '-21.  Wash hands.',
                '-22.  Remove bag, being careful not to touch the inside of the bag.  Place into trash receptacle on Treatment Cart.',
                '-23.  Sign Treatment Book for treatment.',		
            ],

            'MEDICATION ADMINISTRATION COMPETENCY' => [
                '-1. Nurse is wearing ID badge.',
                '-2. Medication Cart prepared for pass',
                '-3. Medication Cart was organized and secured during pass.',
                '-4. MAR covered when out of visual control.',
                '-5. Maintaining proper Infection Control.',
                '-6. Nurse correctly read the order from the medication record and RX label.',
                '-7. Drug ID triple checked before med administration.',
                '-8. Oral liquids measured at eye level.',
                '-9. Oral liquid syringe used for “odd” doses.',
                '-10. Meds crushed only by policy.',
                '-11. Suspensions shake before measurement.',
                '-12. Nurse knocked or announced on resident\’s door before entering.',
                '-13. Resident properly identified before med administration (picture ID or armband).',
                '-14. Nurse informed resident of medications they were giving.',
                '-15. Resident properly positioned before medication administration.',
                '-16. Vital signs (apical pulse and/or blood pressure) were taken if applicable.',
                '-17. Medications via gastric tube were administered correctly (1-placement, 2-residule, 3-flush).',
                '-18. Eye medications administered correctly (handwashing – pre & post).',
                '-19. Inhaler medications administered correctly.',
                '-20. Site for injections properly rotated and show date & initials.',
                '-21. Transdermal patches rotated and show date & initials. Nurses Check patch for placement.',
                '-22. All doses administered by appropriate route (e.g. SL).',
                '-23. Meds properly charted after consumption, including Narcotic charting.',
                '-24. Refused or PRN doses fully documented.',
                '-25. Medication syringes are cleaned Q use. Spacers cleaned daily.',
                '-26. Medication pass was in time compliance.',
                '-27. Adequate fluids given for medications (i.e., Metamucil, NSAIDS, KCl).',
                '-28. Pain assessment done during medication pass.',
            ],
        ];

        $order = 0;
        $this->seedCompetencySet($dsdCompetencyItems, $dsdPositionIds, $order);

        if ($licensedNursePositionIds !== []) {
            $this->seedCompetencySet($licensedNurseCompetencyItems, $licensedNursePositionIds, $order);
        }

        if ($cnaPositionIds !== []) {
            $this->seedCompetencySet($cnaCompetencyItems, $cnaPositionIds, $order);
        }
    }
}