<?php

namespace Database\Seeders;

use App\Models\EmployeeCompetencyItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmployeeCompetencyItemsSeeder extends Seeder
{
    protected function getPositionIdsByTitles(array|string $titles): array
    {
        $titles = array_values(array_filter(array_map('trim', (array) $titles)));

        if ($titles === []) {
            return [];
        }

        return DB::table('positions')
            ->whereIn('title', $titles)
            ->orderBy('id')
            ->pluck('id')
            ->map(fn ($id) => (int) $id)
            ->all();
    }

    protected function seedCompetencySet(array $competencyItems, array $positionIds, int &$order): void
    {
        foreach ($competencyItems as $section => $items) {
            foreach ($items as $item) {
                EmployeeCompetencyItem::query()->updateOrCreate(
                    [
                        'section' => $section,
                        'item' => $item,
                        'order' => $order,
                    ],
                    [
                        'position_ids' => $positionIds,
                    ]
                );

                $order++;
            }
        }
    }

    public function run(): void
    {
        $exportedDataPath = database_path('seeders/data/employee_competency_items.php');
        if (is_file($exportedDataPath)) {
            $items = require $exportedDataPath;
            if (is_array($items)) {
                $this->seedExportedCatalog($items);

                return;
            }
        }

        $directorOfStaffDevelopmentPositionIds = $this->getPositionIdsByTitles('Director of Staff Development');
        $dsdPositionIds = $directorOfStaffDevelopmentPositionIds !== [] ? $directorOfStaffDevelopmentPositionIds : ['global'];
        $sharedNurseAndCnaPositionTitles = [
            'Certified Nursing Assistant',
            'Director of Nursing',
            'Registered Nurse',
            'Licensed Vocational Nurse',
            'Licensed Nurse',
            'Charge Nurse',
            'IP Nurse',
        ];
        $cnaPositionIds = $this->getPositionIdsByTitles('Certified Nursing Assistant');
        $licensedNursePositionIds = $this->getPositionIdsByTitles([
            'Director of Nursing',
            'Registered Nurse',
            'Licensed Vocational Nurse',
            'Licensed Nurse',
            'Charge Nurse',
            'IP Nurse',
        ]);

        $dsdCompetencyItems = [
            'IN-SERVICE EDUCATION PROGRAM MANAGEMENT' => [
                'Annual In-Service Plan (meets **California Title 22 & CMS requirements)',
                'Mandatory Nursing In-Services (Skills, Clinical Competency)',
                'Mandatory In-Services for ALL Staff (Abuse, Infection Control, Safety, HIPAA)',
                'Survey-Driven Education',
                'Competency Validation (Return Demonstrations)',
                'Education Tracking Logs (Attendance, Make-ups)',
                'CNA 12-hour Annual In-Service Compliance',
                'Nurse Continuing Education Tracking',
            ],
            'ORIENTATION PROGRAM MANAGEMENT' => [
                'New Hire Orientation (All Departments)',
                'General Orientation (Facility Policies, Emergency Preparedness)',
                'Clinical Orientation (Nursing-specific skills validation)',
                'CNA Orientation and Preceptor Program',
                'Agency/Registry Staff Orientation',
                'Orientation Checklist Completion Monitoring',
            ],
            'SKILLS COMPETENCY PROGRAM (ALL DEPARTMENTS)' => [
                'Licensed Nurses Annual Skills',
                'CNA Skills Competency',
                'DON Competency Validation',
                'Infection Preventionist Competency',
                'MDS Coordinator Competency',
                'Dietary Staff Competency',
                'Social Services Competency',
                'Activities Competency',
                'EVS/Maintenance/Laundry',
            ],
            'LICENSES, CERTIFICATIONS TRACKING' => [
                'RN/LVN (including Registry Staff)',
                'CNA (including Registry Staff)',
                'REHAB STAFF-Secure from Bio-Pacific',
                'CPR-RN/LVN and PT/OT/SLP (from Bio-Pacific)',
                'Subacute Ventilator Care Certification (RN/LVN)',
            ],
            'HUMAN RESOURCES COORDINATION' => [
                'Background Checks Verified',
                'Annual Performance Evaluations Completed',
                'Employee Files Audit (completeness)',
                'I-9 Compliance',
                'UKG/Time Clock Correction',
                'Leave of Absence Tracking',
                'Payroll Adjustment Coordination',
            ],
            'STAFFING & PPD MONITORING' => [
                'Daily PPD Monitoring',
                'Staffing Posting Compliance',
                'CNA Schedules (monthly)',
                'Daily Assignments Reviewed',
            ],
            'WORKERS COMP & SAFETY PROGRAM' => [
                'OSHA Log Maintenance',
                'Workmen’s Compensation Tracking',
                'Modified Duty Program Monitoring',
                'Safety Committee Lead',
            ],
            'COMMITTEE PARTICIPATION' => [
                'Infection Control Committee',
                'QAPI Committee',
                'Education Reports to QAPI',
                'PIP Support (Falls, Wounds, Psychotropics)',
            ],
            'CLINICAL OVERSIGHT & EDUCATION ROUNDS' => [
                'Rounds-Daily (Monthly with IP)',
                'Direct Care Observations/On-the-spot In-services',
            ],
            'INFECTION PREVENTION SUPPORT' => [
                'Isolation/Transmission-Based Precautions Education',
                'COVID-19 protocols and reporting requirements',
                'Isolation/Transmission-Based Precautions Education',
                'Outbreak Education Response',
            ],
            'EMPLOYEE HEALTH PROGRAM' => [
                'Initial TB Screening',
                'Annual TB Screening',
                'Annual TB Questionnaire',
                'CXR for Positive PPD + MD Clearance',
                'CXR every 5 years or as MD ordered',
                'Initial Physical Exam',
                'Annual Physical Exam',
                'COVID-19 Vaccination Program',
                'Annual Flu Vaccine',
                'Hepatitis B Vaccine',
                'Childhood Diseases Immunization',
            ],
            'POLICIES AND PROCEDURES MANAGEMENT' => [
                'Emergency/Disaster, Fire Safety- RED Binders',
                'Abuse/Neglect/Grievance Binder',
                'MCN access for ALL P&Ps',
                'Lippincott Nursing Procedures Book',
                'Pharmacy LTC Manual and IV Therapy Manual',
            ],
            'RESTORATIVE NURSING PROGRAM' => [
                'RNA Weekly Meeting and Notes',
                'Updating RNA Orders and Care Plans',
                'RNA Monthly Recap',
            ],
            'EHR / MATRIXCARE COMPETENCY' => [
                'Staff Training/ Order Entry / Clinical Workflow Training',
                'Documentation Audits',
                'Dashboard Monitoring (alerts/compliance)',
            ],
            'SURVEY READINESS' => [],
        ];

        $cnaCompetencyItems = [
            'CNA SKILLS' => [
                'Ambulation',
                'Back Rub',
                'Bed Bath',
                'Bed Making, Occupied',
                'Bed Making, Unoccupied',
                'Bed Pan, Urinal',
                'Bladder Management/Toileting',
                'Bladder Patterning/Retraining',
                'Body Mechanics- Gen. Rules',
                '-Lifting and Moving',
                '-Positioning',
                '-Transferring',
                'Catheter Care',
                'Choking, Heimlich Maneuver',
                'Dementia Training',
                'Dialysis',
                'Dressing/undressing',
                'Emergency Procedures/Reporting',
                'Feeding, Special Issues',
                '-Tray service',
                '-Dining Program',
                'Feeding Tubes',
                '-Gastric',
                '-Jejunostomy',
                '-Nasogastric',
                'Fluid Restrictions, Dot system',
                'Grooming',
                'Hand Washing',
                'Incontinence Care/Perineal Care',
                'Infection Control, waste',
                'Linen Handling',
                'Mechanical Lift',
                'Oral Hygiene',
                'Ostomy protocol review',
                'Oxygen, CPAP, BiPAP Tubing Care',
                'Tracheostomy-ADL care (CNA scope of practice)',
                'Pain Identification/Management',
                'Protective Devices',
                'Post-mortem care',
                'Range of motion',
                'Restraint Devices',
                'Scales, weighing',
                'Shaving',
                'Shower / Bathing',
                'Specimen Collection',
                'Splints/Orthosis',
                'Standard Precautions',
                'Use of Cane',
                '-Walker',
                '-Prosthetic devices',
                '-Bed controls',
                '-Wheelchair',
                'Vital signs',
                '-Temperature, axilla',
                '-Temperature, ear',
                '-Temperature, oral',
                '-Temperature, rectal',
                '-Pulse Rate',
                '-Respiratory Rate',
                '-Blood Pressure',
                'Documentation:',
                '-RFPR',
                '--Bed mobility',
                '--Transfers',
                '--Eating',
                '--Toileting',
                '-Meal Monitoring',
                '-Intake/Output, measurement',
                '-STOP and WATCH',
                '-Shower Skin Sheet',
                '-RNA Form (for RNAs)',
                'Other:',
            ],
            'PERINEAL CARE' => [
                '-OBSERVATIONS',
                '--Equipment are properly set up: gloves, washcloths, clean basin, mild soap, bath towel, bath blanket, incontinent pad, toilet tissue, linen saver pad, trash bag.',
                '--Optional: bedpan, peri--bottle, antiseptic soap, petroleum jelly, or zinc oxide cream, or Vitamin A and D ointment, and an ABD pad.',
                '--Obtain ointment or cream, as needed.',
                '--Fill basin two--thirds full of warm water (or fill peri--bottle with warm water).',
                '--Assemble equipment and provide privacy.',
                '--Wash hands and put on gloves.',
                '--Explain the procedure to the resident.',
                '--Adjust bed to working height and lower head of bed.',
                '-FEMALE RESIDENT:',
                '--Position resident on side to expose perineal area. Place incontinent pad underneath.',
                '--Clean, rinse and dry perineal area, starting at posterior vaginal vault opening and wiping front to back.',
                '--Re--position resident to supine position. Use bath blanket to cover resident while exposing perineum.',
                '--Ask resident to bend knees slightly and spread her legs. Wet clean washcloth.',
                '--Separate labia with one hand and wash with the other, using gentle downward strokes from front to back of perineum.',
                '--Use clean section of washcloth for each stroke.',
                '--Rinse thoroughly from front to back and pat area dry with bath towel.',
                '--Apply ordered ointments or creams.',
                '-MALE RESIDENT:',
                '--Assist to supine position and place incontinent pad under buttocks.',
                '--Drape legs for privacy and expose genital area.',
                '--Hold shaft of penis with one hand and wash with the other, beginning at the tip and working in a circular motion from the center to the periphery.',
                '--Use clean section of washcloth for each stroke.',
                '--Rinse thoroughly, using same circular motion.',
                '--For the uncircumcised resident, gently retract the foreskin and clean beneath it.',
                '--Rinse well but do not dry because moisture provides lubrication and prevents friction when replacing foreskin. Pull foreskin back over glans.',
                '--Wash rest of penis, using downward strokes toward scrotum. Rinse well and pat dry.',
                '--Clean scrotum, rinse well and pat dry.',
                '--Turn resident on side, clean bottom of scrotum and anal area. Rinse and dry.',
                '-AFTER CARE:',
                '--Reposition resident, remove bath blanket and incontinent pad, and replace bed linens.',
                '--Clean equipment; store appropriately; discard gloves; and wash hands.',
            ],
        ];

        $licensedNurseCompetencyItems = [
            'LICENSED NURSE COMPETENCY SKILLS' => [
                '-1. Communication',
                '--Telephone Use-Etiquette, Answering/Transferring Calls, Paging',
                '--24-Hour Shift Report (Daily Shift Report)',
                '--Change of Shift Rounds (incoming and outgoing shifts)',
                '--E-mail (if applicable)',
                '-2. Policies and Procedures',
                '--MCN Network',
                '--ViewMasteRx (PharMerica)',
                '--Manuals',
                '-3. Admission Process',
                '--Physician Orders-including verification, faxing to Pharmacy or ordering medications via MatrixCare',
                '--eMAR (MARs/TARs)',
                '--Behavior Monitoring Records in MatrixCare',
                '--Consent to Treat',
                '--Informed Consents-use of psychotropics, side rails, restraints',
                '--Bedhold Consent Form',
                '--Dietary Communication',
                '--Therapy Communication',
                '--Laboratory/Diagnostic Orders',
                '--Consults Orders-eye, dental, hearing, podiatry, psychiatry',
                '--Weight and Vital Signs Records',
                '--Resident Data Collection',
                '--Braden Scale-weekly x 4',
                '--If with Wound, Wound Assessment Form',
                '--If with Pressure Injury, Daily Pressure Injury Monitoring',
                '--Pain Evaluation',
                '--Pain Management Flowsheet',
                '--Fall Risk Data Collection',
                '--Bowel and Bladder Assessment',
                '--Bowel and Bladder Patterning-Program',
                '--Elopement Risk Assessment',
                '--If Elopement Risk, Elopement Identification Form',
                '--Side Rail Evaluation-including Risk for Entrapment',
                '--Pre-Restraints Assessment',
                '--Smoking Assessment',
                '--If a Smoker, initiation of Smoking Contract',
                '--Trauma Informed Care',
                '--Tobacco, Alcohol, Prescribed Drugs, Substance Use (TAPS) 1-2',
                '--MDS PHQ 2-9 Mood Screening',
                '--MDS Section E Behavior Monitoring',
                '--Abnormal Involuntary Movement Scale (AIMS) Test',
                '--Self-Administration of Medications Assessment',
                '--Care Plan Essentials (CPE)',
                '--Interim Care Plan',
                '--MatrixCare Documentation and Point of Care-see checklist',
                '-4. Telephone Orders',
                '--Documentation, Faxing to Pharmacy or Ordering through MatrixCare',
                '-5. Medication Administration Record (MAR)/Treatment Administration Record (TAR)',
                '--Completion/Update in MatrixCare',
                '--Paper Form MAR/TAR when MatrixCare is Offline',
                '-6. Pharmacy',
                '--Ordering/Reordering [CA is a “no return of medications” state]',
                '--Controlled Medications Storage and Disposition/Destruction',
                '--Signing for Accountability of Controlled Medications',
                '---Signing the Controlled Medications Declining Sheets',
                '---Counting Procedures',
                '--Ordering IV Supplies',
                '-7. Dietary',
                '--Communication/Changes',
                '--Meal Monitoring',
                '--Snacks Monitoring',
                '--Thickened Liquids',
                '--Dysphagia Cautions',
                '--Enteral Orders',
                '--Dietary Restrictions',
                '--Hydration DOT System',
                '-8. Weights/Hydration',
                '--Policy-Review the Weights/Hydration Pathway',
                '--Admission Weight, then weekly X 4',
                '--Daily/Weekly/Monthly',
                '--Weight Methods (i.e., chair, bed, mechanical lift)',
                '---Mechanical Lift transfers-see checklist',
                '--Weights Documentation',
                '--Weekly Nursing Summary-indicate weight variances, meal intake changes, hydration status, intake and output summary',
                '--Hydration DOT System',
                '--Care Plan',
                '-9. Interdisciplinary Care Planning',
                '--Initiate/Update Care Plan for any Changes of Condition, Physician Orders',
                '--Attendance in Care Conferences',
                '--Care Plan Essentials (CPE)',
                '-10. Transfer (review the checklist)',
                '--Hospital',
                '--Same Nursing Unit-Room/Bed',
                '--Unit to Unit',
                '--Notification Process',
                '--Transfer Form/Documents',
                '--Ombudsman Notification for Hospital Discharge',
                '-11. Discharge (review the checklist)',
                '--Home, Assisted Living, Board and Care',
                '--AMA/AFA',
                '--Instructions',
                '--Completion of Discharge Forms/Documents',
                '--Medications and Orders for Discharge',
                '--Ombudsman Notification by Social Services',
                '-12. Death Procedure',
                '--Notification of Physician, Resident Representative',
                '--Documentation',
                '--Postmortem Care',
                '--Physician Order for release of body',
                '-13. Restraints',
                '--Policy',
                '--Alternatives',
                '--Physician Order with reason for use, release times',
                '--Informed Consent',
                '--Weekly Documentation-Nursing Weekly Summary',
                '-14. Psychotropics',
                '--Policy',
                '--Physician Order-with specific diagnosis, behavior to be monitored',
                '--PRN x 14 days, then reevaluate',
                '--eMAR/MAR with specific behavior and side effects monitoring per medication',
                '--Informed Consents (every 6 months, any increase/decrease of dose with antipsychotic)',
                '--Care Plan',
                '--Gradual Dose Reduction',
                '--Weekly Nursing Summary-response to use',
                '--Monthly Licensed Nurse Psychotropic Notes-one per medication',
                '--Monthly IDT Psychotropic Meeting/Notes',
                '-15. Incidents/Accidents',
                '--Policy',
                '--Reports and Investigation',
                '--If possible abuse/neglect case, follow policy, mandated reporter',
                '--Resident, Employee, Visitor',
                '--Notification of Physician and Resident Representative',
                '--Documentation-SBAR (initial), then COC q 64 more hours, total of q shift x 72 hours (may also document in Progress Notes when indicated)',
                '--Care Plan',
                '--IDT Risk Meeting weekly x 4',
                '-16. Falls/Injury',
                '--Policy-review of the Falls Pathway, Fall Prevention, Falling Stars Program (yellow and red stars), Safety Alarms',
                '--Personal Safety Alarm monitoring q shift',
                '--Documentation-SBAR (initial), then q shift x 64 hours COC; total of q shift x 72 hours (may also document in Progress Notes when indicated)',
                '--Neuro check after every fall incident/accident-witnessed or unwitnessed',
                '--Fall Risk Evaluation on admission, after every fall incident/accident occurrence, quarterly',
                '--Care Plan-after every fall with new interventions',
                '--IDT Risk Meeting-weekly x 4 post incident/accident',
                '-17. Wounds',
                '--Policy-Follow Pathway and Reference Tool',
                '--Initial Skin Assessment on Admission-if with wound or skin issues, initiate the wound assessment form (pressure or non-pressure) on admission, then weekly thereafter until healed.',
                '--For Pressure Ulcer/Injury-Daily Monitoring Form (by 3-11 shift)',
                '--Nursing Weekly Summary-focus on presence of wound(s), turning and positioning monitored, offloading of extremities, toileting assistance, meals assistance',
                '--Care Planning-one site per care plan',
                '--Wound Risk Worksheet-if avoidable or unavoidable',
                '--IDT Risk Meeting-weekly for facility acquired and worsening wounds',
                '-18. Infection Control',
                '--Isolation Protocols-COVID-19, Standard Precautions, Enhanced Barrier Precautions (EBP), Transmission-Based (Droplet, Contact, Airborne); initiating and discontinuing isolation precautions',
                '--Reportable',
                '--Documentation-including McGeer criteria',
                '--Care Planning',
                '--Notification of Physician, Resident Representative',
                '--Hand Hygiene',
                '--Donning/Doffing of Personal Protective Equipment (PPE)',
                '-19. Respiratory Treatment Procedures',
                '--Oxygen-nasal cannula, masks',
                '--Oxygen Tanks-storage, use',
                '--Concentrators',
                '--Nebulizers',
                '--BiPAP/CPAP',
                '--Suctioning-nasal, oral, tracheostomy',
                '--Tracheostomy Care (may attach the Skills Checklist)',
                '--If Subacute Licensed Nurse, attach the specific subacute certification and training',
                '-20. Diagnostic/Laboratory Procedures',
                '--Specimen Collection',
                '--Physician Notification',
                '--Documentation',
                '-21. Enteral Feeding (Nasogastric, Gastrostomy, Jejunostomy)',
                '--Policy',
                '--Placement Verification',
                '--Residual Check',
                '--Site Care',
                '--Reinsertion',
                '--Head of Bed (HOB) elevation as per physician orders',
                '--Documentation',
                '-22. Medication Pass/Administration (may attach the Medication Pass Checklist)',
                '--Medication Pass Observation using proper techniques',
                '--Behavior Monitoring Sheets',
                '--Pain Flowsheets',
                '--Securing Medications and syringes in a locked space',
                '--Double Locking of Controlled Medications',
                '--Proper Labeling and Storage of Medications',
                '--Oral Medications',
                '--Eye Drops Administration',
                '--Ear Drops Administration',
                '--Subcutaneous (SQ)/Intramuscular (IM) Administration',
                '--Insulin Administration-precautionary measures with short acting vs. long acting',
                '--Glucometer Use (may attach the Skills Checklist)',
                '--Medication Cart',
                '--Medication Room and Storage-include temperature logs',
                '--Discarding of Medications-Controlled and Non-Controlled, Fentanyl patch',
                '--Documentation',
                '--Reporting of Medication Errors',
                '--Privacy of Medical Records',
                '-23. Treatment Pass/Administration (may attach the Treatment Skills Checklist)',
                '--Dressing Change',
                '--Foley Catheter Insertion and Care',
                '--Suprapubic Catheter Insertion and Care',
                '--Nephrostomy Tube Insertion (Physician only) and Care',
                '--Colostomy/Ileostomy/Ileal Conduit Care',
                '--Rectal Tube Care',
                '--Weekly Skin Checks-documented in Nursing Weekly Summary',
                '--Documentation on Treatment Record',
                '--Weekly Wound Assessment/Evaluation',
                '-24. Intravenous (IV) Therapy (may attach IV Skills Check)',
                '--Certification',
                '--Peripheral Insertion',
                '--Line Care/Changing',
                '--Site Care',
                '--Hanging IV Fluids',
                '--IV Antibiotics Administration-RN Only',
                '--IV Medications Administration-RN Only',
                '--Porta Catheter',
                '--Heparin Lock',
                '--Central Line, PICC',
                '--Flushes',
                '-25. Direct Care',
                '--Policies',
                '--Turning and Positioning/Repositioning',
                '--Transfers-1, 2 or more person assist, mechanical lift (refer to the skills checklist)',
                '--Assist with Toileting, Bed Bath, Shower, Incontinence Care/Perineal Care',
                '--Assist with Feeding of Resident',
                '-26. Unit Monitoring Functions',
                '--Licensed Nurses’ and Certified Nursing Assistants’ Assignments',
                '--Outgoing/Incoming Shifts’ Reports',
                '--In-services',
                '--Chain of Command',
                '-27. Resident/Resident Representative Education',
                '--Demonstration',
                '--Documentation',
                '-28. MatrixCare and Point of Care (POC) Checklist',
                '--Review Protocols',
                '-29. OTHER',
            ],

            'BLOOD ADMINISTRATION' => [
                '-Consider cultural and religious influences and educational level when administering blood and performing teaching with patients receiving blood and blood products.',
                '-Utilize principles of body substance isolation, explain procedure to patient, and educate patient about transfusion reaction symptoms to report to nurse.',
                '-Type and Screen is required for any red blood cell, whole blood product, platelet, or plasma administration. Draw and send this sample to blood bank in accordance with policy. (Cryoprecipitate does not require Type and Screen.)',
                '-Assess the patient for a history of transfusions and transfusion reaction.',
                'Pre-transfusion checks to be performed prior to blood pick up:',
                '-1. Verify there is an ORDER TO TRANFUSE the blood product',
                '-2. Make sure there is a CONSENT FOR TRANSFUSION',
                '-3. Check patency of IV LINE, >22 gauge required, >20 gauge preferred. Establishes IV at KO rate or per physician’s order.',
                '--a. Prime Y tubing with normal saline solution.',
                '--b. Follow procedure for starting large bore IV, greater than 20 gauge for adults.',
                '-4. Check PRE-TRANSFUSION VITAL SIGNS for acceptability. If the patient has a fever or any other cause for delay of transfusion, resolve prior to blood pick up',
                '-5. Check that the patient is wearing a BLOOD BANK ID BAND for any order to give RBCs',
                '-Check if blood is ready in Powerchart via BB Product Inquiry. Do NOT call the Blood Bank to ask if blood is ready. DO call the Blood Bank if you see the blood is not ready and would like a status update.',
                '-Bring a copy of the order and blood consent to the Blood Bank for blood pick up.',
                'Perform identification and verification checks with another RN/physician/perfusionist at the recipient’s bedside. Do not start the transfusion if there is any discrepancy. Verify audibly and view concurrently the following:',
                '-a. Blood product with physician’s written order.',
                '-b. Patient identity by any combination of any two of the following: patient name, date of birth, medical record number, last four digits of Social Security number, photograph identification',
                '-c. Patient name and medical record number on the identification wristband, the blood transfusion administration record (TAR) and the compatibility label on the blood product.',
                '-d. Verifying that the unit number, donor ABO/Rh, Patient ABO/Rh, expiration date and compatibility label are identical for the blood bag, compatibility label and TAR.',
                '-e. The TAR remains with the patient throughout transfusion. Both staff members sign the chart copy of the TAR and place in patient chart',
                '-Blood transfusions must be started as soon as possible after blood product issuance. There is no need to return the blood to the Blood Bank if not started within 30 minutes.',
                '-Blood transfusions must be completed within 4 hours from issuance, regardless of start time.',
                '-RN must stay at the patient’s bedside for the first 15 minutes of transfusion.',
                'Follow Infection Protocol related to Isolation Precautions-Standard, Enhanced Barrier Precautions (EBP), Transmission-Based Precautions (EBP)-airborne, contact, droplet, proper hand hygiene, proper use of PPE.',
                '-Obtain vital signs:',
                '--a. Pre-transfusion vital signs are required, including a temperature. Vital signs must be taken within 30 minutes prior to beginning transfusion.',
                '--b. The nurse remains with the patient for the first 15 minutes of the transfusion, monitoring the patient closely for signs/symptoms of transfusion reaction.',
                '--c. Vital signs are taken 15 minutes after the transfusion is initiated, hourly during infusion, and upon completion of each unit.',
                '--d. Post-transfusion, within 2 hours after completion of transfusion',
                'Exception: in critical situation, take vital signs no more than 15 min. prior start of transfusion and at completion of unit.',
                '-Premedicate patient if ordered.',
                '-Attach blood to tubing. Spike the blood bag before hanging it up onto the pole. Do not piggyback blood.',
                '-Upon completion of administration of blood, flush tubing with normal saline unless otherwise ordered.',
                '-Change blood tubing after every 2 units or every 4 hours.',
                '-See blood transfusion policy for usual lengths of transfusion. (for whole blood 2-4 hours, must be infused within 4 hours of leaving Blood Bank)',
                '-If no transfusion reaction noted, dispose of blood bag and tubing in biohazard container.',
                '-If transfusion was documented in Cerner Bridge and the patient has a transfusion reaction after the transfusion has ended, the reaction must be documented in Bridge.',
                '-If the blood transfusion was started on paper, continue documentation on paper.',
                '-Always notify the Blood Bank if there is an emergent need for blood at extension 8315.',
                '-Document patient/family teaching.',
                '-See policy for blood transfusion reaction signs/symptoms and for steps to take if transfusion reaction occurs.',
            ],
            
            'BLOOD GLUCOSE SYSTEM SKILLS' => [
                                '-User Assembles Equipment',
                                '--Blood Glucose Monitor',
                                '--Test strips',
                                '--Test solutions',
                                '--Finger stick supplies',
                                '-User Reviews Procedure',
                                '--States when coding is necessary.',
                                '--Turns monitor on and off accordingly.',
                                '--Verifies that the code numbers match.',
                                '-Performs Test Procedure',
                                '--Performs proper hand hygiene and puts on disposable gloves.',
                                '--Properly prepares lancet device.',
                                '--Turns monitor on.',
                                '--Checks expiration date of test strips.',
                                '--Inserts test strip.',
                                '--Obtains blood sample correctly.',
                                '--Applies blood to test strip correctly.',
                                '--Reads result.',
                                '--Documents result.',
                                '--Properly discards used test strip and blood-drawing supplies.',
                                '--Removes gloves and performs proper hand hygiene.',
                                '-Recalls Results from Memory',
                                '--Correctly records results stored in memory.',
                                '-Problem Solving. Refers to User’s Manual if a problem with testing occurs.',
                                '--Getting a good drop of blood',
                                '--Display Messages',
                                '--Error Messages',
                                '-Quality Control Testing',
                                '--Checks expiration date of control solutions and test strips.',
                                '--Correctly performs control test.',
                                '--Follows proper troubleshooting procedures if control is not in the acceptable range.',
                                '--Is aware of the 24 hour Blood Glucose Customer Care number',
                                '-Cleaning',
                                '--States cleaning frequency for the exterior of the monitor.',
                                '--Properly describes cleaning procedure, including cleaning wipes to be used, for exterior of the monitor.',
                                '-Battery Replacement',
                                '--Demonstrates removal and replacement of batteries.',
            ],
            
            'TRACHEOSTOMY CARE' => [
                                '-Equipment/Supplies',
                                '--Correct size & type of tube',
                                '--Suction machine',
                                '--Sterile suction catheter',
                                '--Connecting tubing',
                                '--Applicators',
                                '--Small brush or pipe cleaners',
                                '--Clamp & syringe',
                                '--Ointment for skin protection',
                                '--Hydrogen peroxide',
                                '--Sterile saline or water',
                                '--Tracheostomy ties or collar (Pre-cut ties or Velcro ties are recommended)',
                                '--4x4 gauze pads',
                                '--One set sterile gloves & one set clear gloves',
                                '--Basin',
                                '--Scissors',
                                '--Plastic bag for waste',
                                '--Tissues',
                                '--Emergency tracheostomy tube & reinsertion supplies',
                                '--Resuscitation bag',
                                '--Personal Protective equipment (i.e. face mask, face shield, eyewear)',
                                '-1. Follow Infection Control Protocols and Isolation Protocols-Standard Precautions, Enhanced Barrier Precautions (EBP), Transmission-Based Precautions (TBP)-airborne, contact, droplet.',
                                '-2. Assemble equipment and bring to the bedside.',
                                '-3. Identify and explain procedure to resident and provide privacy.',
                                '-4. Wash hands, put on personal protective equipment-mask, gown, goggles/face shield if appropriate. Follow proper donning of PPE.',
                                '-5. Place resident in semi-Fowler position unless medically contraindicated.',
                                '-6. Open sterile catheter using aseptic technique.',
                                '-7. Put on sterile gloves.',
                                '-8. Using sterile technique, suction tracheostomy tube.',
                                '-9. Using your less dominant hand as your dirty hand, pour peroxide or solution in basin.',
                                '-10. Using your sterile hand unlock inner cannula of tracheostomy tube, remove, place in basin and allow to soak.',
                                '-11. Remove gloves and put on clean gloves.',
                                '-12. Remove tracheostomy dressing.',
                                '-13. Using applicators and peroxide, clean skin around tracheostomy tube, removing all exudate and drainage - DO NOT ALLOW any solution to enter outer tracheostomy tube or opening.',
                                '-14. Using applicators and brush, clean inner cannula well||Note: Avoid touching cannula itself with gloved hand.',
                                '-15. Rinse with sterile saline or water and drain on sterile 4x4.',
                                '-16. Suction resident.',
                                '-17. Insert inner cannula and lock in place.',
                                '-18. If used, fasten pre-cut ties or Velcro ties to the side, 3-4 inches from the tube opening, not behind the neck.||A second individual may be needed to assist.',
                                '-19. Prepare tracheostomy dressing by making a 3" cut down the middle of a 4x4" gauze pad, or use a commercial precut 4x4" gauze, then fit around the tube and underneath the ties.',
                                '-20. Follow proper doffing of PPE (i.e., gloves, mask, gown, goggles/face shield)',
                                '-21. Leave resident in comfortable position with call light within reach.',
                                '-22. Dispose of supplies and linen in designated container.',
                                '-23. Wash hands.',
            ],

            'NURSE TREATMENT SKILLS' => [
               	'-1. Ensure that Treatment Cart is adequately stocked.',
                '-2. Follow Isolation Protocols-Enhanced Barrier Precautions (EBP), Standard Precautions, Transmission-Based Precautions-Airborne, Contact, Droplet; Use of proper PPE',
                '-3. Bring Treatment Cart to resident’s doorway. Face cart towards doorway. If you are able to visually see Treatment Cart from resident’s bedside, it is not necessary to lock cart. However, if you cannot see the cart, lock cart while you are doing the treatment in the resident’s room.',
                '-4. Review treatment order in eMAR/TAR. Prepare supplies for treatment. Pour normal saline or substitute into medicine cup. If the order includes an ointment, do not bring tube into room. Squirt just enough ointment into medicine cup. May use clean cotton tips or tongue depressors as applicators. Make sure that you have at least two pairs of gloves. They do not need to be sterile, unless it is a sterile procedure.',
                '-5. Place supplies on resident’s overhead bed table. A paper plate may be used, plastic bag, etc, as a barrier, to lay supplies on top of. Arrange dressings, cut tape, etc.',
                '-6. Pull curtain around resident’s bed for privacy.',
                '-7. Introduce yourself to resident and explain what you are going to do.',
                '-8. Position resident in an appropriate position, being careful to provide privacy, if possible.',
                '-9. Go to bathroom sink and wash hands.',
                '-10. Put on gloves.',
                '-11. Remove old dressing and place it into plastic bag. (You may position bag on top of resident’s bed.)',
                '-12. Remove gloves and discard into bag.',
                '-13. Wash hands.',
                '-14. Apply clean pair of gloves.',
                '-15. Take a couple of non-sterile 4x4 or 2x2’s and saturate with the normal saline or substitute. Clean resident’s wound. Note: Do not wipe over a soiled area a second time with the same 4x4.  Place dressings into plastic bag.',
                '-16. Remove gloves and place into plastic bag.',
                '-17. Wash hands again. (You may not need to wash hands if the wound does not have drainage. Use your judgment.)',
                '-18. Apply a clean pair of gloves to apply the final dressing. You may be able to grasp the corners of the dressing, being careful not to touch the center of the dressing, or the wound of the resident, without putting on the final pair of gloves. Again, use your judgment regarding the type of wound you are working with.',
                '-19. Remove gloves, and place into plastic bag.',
                '-20. Cover resident and position for comfort.',
                '-21. Wash hands.',
                '-22. Remove bag, being careful not to touch the inside of the bag. Place into trash receptacle on Treatment Cart.',
                '-23. Sign eMAR/Treatment Book for treatment provided.',
            ],

            'HAND HYGIENE SKILLS' => [
                '-1. Ensure that Treatment Cart is adequately stocked.',
                '-2. Follow Isolation Protocols-Enhanced Barrier Precautions (EBP), Standard Precautions, Transmission-Based Precautions-Airborne, Contact, Droplet; Use of proper PPE',
                '-3. Bring Treatment Cart to resident’s doorway. Face cart towards doorway. If you are able to visually see Treatment Cart from resident’s bedside, it is not necessary to lock cart. However, if you cannot see the cart, lock cart while you are doing the treatment in the resident’s room.',
                '-4. Review treatment order in eMAR/TAR. Prepare supplies for treatment. Pour normal saline or substitute into medicine cup. If the order includes an ointment, do not bring tube into room. Squirt just enough ointment into medicine cup. May use clean cotton tips or tongue depressors as applicators. Make sure that you have at least two pairs of gloves. They do not need to be sterile, unless it is a sterile procedure.',
                '-5. Place supplies on resident’s overhead bed table. A paper plate may be used, plastic bag, etc, as a barrier, to lay supplies on top of. Arrange dressings, cut tape, etc.',
                '-6. Pull curtain around resident’s bed for privacy.',
                '-7. Introduce yourself to resident and explain what you are going to do.',
                '-8. Position resident in an appropriate position, being careful to provide privacy, if possible.',
                '-9. Go to bathroom sink and wash hands.',
                '-10. Put on gloves.',
                '-11. Remove old dressing and place it into plastic bag. (You may position bag on top of resident’s bed.)',
                '-12. Remove gloves and discard into bag.',
                '-13. Wash hands.',
                '-14. Apply clean pair of gloves.',
                '-15. Take a couple of non-sterile 4x4 or 2x2’s and saturate with the normal saline or substitute. Clean resident’s wound. Note: Do not wipe over a soiled area a second time with the same 4x4. Place dressings into plastic bag.',
                '-16. Remove gloves and place into plastic bag.',
                '-17. Wash hands again. (You may not need to wash hands if the wound does not have drainage. Use your judgment.)',
                '-18. Apply a clean pair of gloves to apply the final dressing. You may be able to grasp the corners of the dressing, being careful not to touch the center of the dressing, or the wound of the resident, without putting on the final pair of gloves. Again, use your judgment regarding the type of wound you are working with.',
                '-19. Remove gloves, and place into plastic bag.',
                '-20. Cover resident and position for comfort.',
                '-21. Wash hands.',
                '-22. Remove bag, being careful not to touch the inside of the bag. Place into trash receptacle on Treatment Cart.',
                '-23. Sign eMAR/Treatment Book for treatment provided.',
            ],

            'VENTILATOR MANAGEMENT SKILLS' => [
                'VENTILATOR',
                '-Mode:',
                '--AC (Assist Control)',
                '--SIMV (Synchronous Intermittent Mandatory Ventilation',
                '--Spontaneous',
                '-Respiratory Rate',
                '-FIO2 (Percentage of Oxygen)',
                '-Tidal Volume (VT)',
                '-PEEP/CPAP',
                '-Pressure Support',
                '-Alarms:',
                '--Low Pressure (intermittent sound)-check for disconnection, leakage',
                '--High Pressure (constant sound)-presence of secretions, bronchospasm, kinking of the tube',
                '--Apnea',
                '--Low Power',
                'NON-VENTILATOR',
                '-Continuous Aerosol',
                '--Setting a patient on aerosol with oxygen supplement',
                '--Circuit set up',
                '--Indications and Contraindications',
                '-Coolmist',
                '-T-piece',
                'OXYGEN USAGE',
                '-High flow-precise FIO2-ventilator devices',
                '--Wall Oxygen',
                '--Oxygen Tank (H-tank: big; E-tank: small)',
                '-Low flow-L/M-Bleed in Devices',
                '--Oxygen Concentrator',
                '-Hazards of Oxygen Therapy',
                '-Inline Medication Delivery on Ventilator',
                '-Physician Orders',
                '-Equipment Set Up',
                '-Position Treatment',
                '-Emergency Situations',
                'SUCTIONING',
                '-Oral',
                '-Tracheal',
                '--Close suction catheter',
                '--Single-use catheter',
                '-Nasotracheal',
                'INFECTION CONTROL',
                '-Equipment Change Out Routine',
                '-Types of Infections and Isolation Required',
                '-Personal Protective Equipment (PPE)',
                'RESPIRATORY ASSESSMENT (RN)/DATA GATHERING (LVN)',
                '-Breath Sounds',
                '--Normal',
                '--Abnormal-rhonchi, wheezes, rales/crackles',
                '-Sputum',
                '--Color',
                '--Consistency',
                '--Amount'
            ],

            'PERSONAL PROTECTIVE EQUIPMENT (PPE)' => [
                'Demonstrate the ability to put on Personal Protective Equipment',
                '-1. Hand hygiene:  demonstrates ability to perform hand hygiene',
                '--Handwashing and/or Alcohol Based Hand Rub (ABHR)',
                '-2. Gown',
                '--a. Fully cover torso from neck to knees, arms to end of wrists, and wrap around the back.',
                '--b. Fasten in back of neck and waist',
                '-3. Mask or Respirator or Both (N95 Respirators can be re-used for crisis situation ONLY as determined by CDC). Mask only:  Secure ties or elastic bands at middle of head and neck.  Fix flexible band to nose bridge and fit snug to face and below chin. Respirator only:  See separate skills check (fit check). Both Mask and Respirator:  Follow respirator donning first before the mask.   ',
                '-4. Goggles or Face Shield',
                '--a. Place over face and eyes and adjust to fit',
                '-5. Gloves',
                '--a. Extend to cover wrist of isolation gown',
                'Demonstrate the ability to remove Personal Protective Equipment',
                '-1. Gloves (Cannot be re-used)',
                '--a. Outside of gloves are contaminated.',  
                '-Using a gloved hand, grasp the palm area of the other gloved hand and peel off first glove',
                '--b. Hold removed glove in gloved hand',
                '--c. Slide fingers of ungloved hand under remaining glove at wrist and peel off second glove over first glove',
                '--d. Discard gloves in a waste container.',
                '-2. Goggles or Face Shield (Re-usable)',
                '--a. Outside face shield is contaminated. Remove goggles or face shield from the back by lifting head band or earpieces.',
                '--b. If the item is going to be re-used, place in designated receptacle for reprocessing. Otherwise, discard in a waste container.',
                '-3. Gown (Washable; disposable but re-usable)',
                '--a. Outside gown and sleeves are contaminated.  Unfasten gown ties, taking care that sleeves don’t contact your body when reaching your ties.',
                '--b. Pull gown away from neck and shoulders, touching inside of gown only.',
                '--c. Turn gown inside out.  Fold or roll into a bundle and: If washable - place in designated container; If disposable and not soiled and will still be re-used - place in designated receptacle; If disposable and visibly soiled or will not be re-used - discard in a waste container.',
                '-4. Mask or Respirators or Both (N95 Respirators can be re-used fro crisis situation ONLY as determined by CDC). Mask only: Front of mask is contaminated – DO NOT TOUCH!  Grasp bottom ties or elastics of the mask, then untie and/or remove without touching the front.  Discard in a waste container. Respirator only:  See separate skills check. Both Mask and Respirator:  Follow mask doffing first before respirator doffing. If re-using N95 Respirator (ONLY as determined by CDC):  Store N95 respirator in a breathable paper bag.  Make sure to label all paper bags with employee name.  Paper bags can only be used once to store any PPE and discarded after.',
                '-5. Hand hygiene: Demonstrates ability to perform hand hygiene after removal of PPEs.',
                '--Handwashing and/or Alcohol Based Hand Rub (ABHR)',
                '-6. Employee verbalizes that re-using of PPE is allowed only in a crisis situation as allowed by CDC.',
            ],

            'MEDICATION ADMINISTRATION' => [
                '--1. Nurse is wearing ID badge.',
                '--2. Medication Cart prepared for pass.',
                '--3. Medication Cart was clean, organized and secured during pass.',
                '--4. MAR/eMAR covered when out of visual control.',
                '--5. Maintaining proper Infection Control-Isolation Precautions with proper donning/doffing of PPE, hand hygiene',
                '--6. Nurse correctly read the order from the medication record and RX label.',
                '--7. Drug identification triple checked before med administration.',
                '--8. Oral liquids measured at eye level. No spills.',
                '--9. Oral liquid syringe used for “odd” doses.',
                '--10. Meds crushed only by policy.',
                '--11. Suspensions shake before measurement.      			',
                '--12. Nurse knocked or announced on resident\’s door before entering.',
                '--13. Resident properly identified before med administration (picture ID or armband).',
                '--14. Nurse informed resident of medications they were giving.',
                '--15. Resident properly positioned before medication administration.',
                '--16. Vital signs (apical pulse and/or blood pressure) were taken if applicable.',
                '--17. Medications via gastric/nasogastric tube were administered correctly (1-placement, 2-residual, 3-flush).',
                '--18. No “cocktailing” of medications when administered via enteral tubes.',
                '--19. Eye medications administered correctly (hand hygiene – pre & post).',
                '--20. Inhaler medications administered correctly.',
                '--21. Site for injections properly rotated and show date & initials.',
                '--22. Transdermal patches rotated and showed date & initials. Nurses Check patch for placement.',
                '--23. All doses administered by appropriate route (e.g. SL).',
                '--24. Properly follows procedures if medication(s) is not available during medication pass.',
                '--25. Meds properly charted after consumption, including Narcotic charting (declining sheet and MAR/eMAR)',
                '--26. Refused or PRN doses fully documented. Contacted Physician/Nurse Practitioner for refusal of medication(s).',
                '--27. Medication syringes are cleaned Q use. Spacers cleaned daily.',
                '--28. Medication pass was in time compliance.',
                '--29. Adequate fluids given for medications (i.e., Metamucil, NSAIDS, KCl).',
                '--30. Open date and Expiration date on multidose vials or over-the-counter multidose oral medications',
                '--31. Pain Assessment completed prior to and at least 30 minutes after administration of pain medication(s).',
                '--32. Privacy curtain maintained while administering medications, taking vital signs.',
                '--33. Proper discarding of medication(s)-i.e., removed fentanyl patch, loose pills.',
            ],

            'LICENSED NURSE eMAR COMPETENCY' => [
                '-1. Census',
                '--Admit/Discharge Residents – must becompleted in real time.',
                '-2. Viewing Administrations',
                '--Resident Messages – Notice Alerts',
                '-3. Select Work List Page Components',
                '--Date/Time, Unit Filter, Status, Walk Away ',
                '--Facility Specific Worklists:',
                '--CMA versus Licensed NurseWorklists.',
                '-4. Order Verification',
                '-5. Order Administration',
                '-Select Resident',
                '-Order Status – Late, Due, Tasks, Stat, PRN in Process',
                '--Order Administration: “Real Time”. Complete Tasks, Prep, Walk Away, Not Adm, Confirm and Next, Confirm and Save',
                '--Administration History – 14 day, Amend',
                '--Shift Change: At shift change check the order status for any late, due, tasks that have NOT been completed.',
                '--Vital Signs – any Vital Signs entered in the eMAR must also be entered under the Resident TAB - VITALS section',
                '-6. Orders',
                '--Administration Time Override: Must select when you will be administering the first dose.',
                '--Prior to discontinuing any orders, check the status of the order and complete as indicated',
                '-7. Resident Reports',
                '--Administration History',
                '-8. Facility Reports',
                '--Administration Compliance',
                '-9. Downtime Process',
                '--eMAR Offline Report'
            ],

            'LICENSED NURSE POINT OF CARE COMPETENCY' => [
                '-1. Logging In/Off Point of Care/Matrix',
                '--Security/HIPAA',
                '-2. Resident Census-for UNIT MANAGER AND UNIT COORDINATOR ONLY',
                '--Adding a Resident (Face Sheet)',
                '--Admitting/Discharging(Census)',
                '--Midnight Census',
                '-3. Resident Profile',
                '--Review and advise if any updates are needed',
                '-4. POC – Tablet or Matrix',
                '--MDS Tracking- When categories are red “documentation required.” Skin checks and Stop and Watch to be documented on paper',
                '-5. Vitals - Daily Documentation',
                '--Meal/Fluid Intake, Elimination',
                '-6. Vitals',
                '--Weights',
                '--Vital Signs – TPR, B/P',
                '--Configure Individual Resident Vitals Alerts',
                '--Mark Invalid Vitals',
                '-7. Management',
                '--Running the Vitals Report',
                '--Monitoring “Resident Messages”',
                '-8. Running the Physician Progress Note',
                '-9. Downtime Procedures',
                '--If system down, you must complete paper documentation.',
                '-10. Other (please specify)',
            ],

            'MATRIXCARE PHYSICIAN ORDER AND DOCUMENTATION' => [
                '-eLearning',
                '--Admission and Census, Physician Orders, Observations, Resident Care',
                '-The Matrix Medical Record',
                '--Location of Information',
                '--Resident Documents',
                '-POC – Kiosk or Matrix',
                '--MDS Tracking- When categories are red "documentation" required.',
                '-Resident Messages',
                '--Reviewing Messages',
                '--Archiving',
                '-Resident Face Sheet - Updating',
                '--Advanced Directives',
                '--Providers',
                '--Allergies',
                '--Diagnosis',
                '-Resident Census',
                '--Add/Admit Resident',
                '--Discharging Residents',
                '--Midnight Census',
                '--Discontinuing Medication upon Discharge (do this when ADMITTED to hospital only)',
                '-Orders',
                '--Order Entry – Prescription, General, Lab, X-Ray, Standing Orders',
                '--Nursing Orders versus Physician Orders',
                '--VTO Process',
                '--Electronic Signatures (Physician/NP/PA)',
                '--Resident Profile (Standing POC Orders)',
                '-Observations/Progress Notes',
                '--Adding/Marking Invalid',
                '-Vitals/Vitals POC',
                '--Adding/Marking Invalid',
                '--Reports',
                '--Vitals Alerts',
                '-Facility Process Review',
                '--24 Hour Report',
                '--Care Planning',
                '-System Downtime',
                '--Downtime Binder',
                '--eMAR Offline Report',

            ]
        ];

        $sharedNurseAndCnaCompetencyItems = [
            'USE OF HOYER LIFT' => [
                '-1. Caregiver Safety Tips',
                '--Use lifts for these activities to avoid sustaining a back injury:',
                '---Lifting from floor',
                '---Bed-chair transfer',
                '---Lateral transfer',
                '---Lifting limbs',
                '---Toileting/bathing',
                '---Repositioning',
                '--Do NOT push, pull, or lift while:',
                '---Off balance or leaning forward',
                '---Twisting and/or reaching',
                '---Entrapped in a confined space',
                '--Tip: Work as close to the patient as possible to avoid stress of leaning.',
                '-2. Know Your Lift',
                '--Tip:  knowing the lift and how to use it correctly can prevent patient falls from lifts- which may cause injuries, including head trauma, fractures, and death.',
                '-3. Before Using a Lift, Check the Patient’s Condition',
                '--Before using a patient lift, check:',
                '---Patient’s physical capabilities',
                '----Check to see if patient can assist with transfer.',
                '----Check patient’s weight and physical condition; use manufacturer’s guidelines to make sure lift is appropriate.',
                '----Determine how many caregivers are required to safely lift the patient.',
                '---Patient’s medical condition',
                '----Make sure you have correct lift and sling for patient’s condition.',
                '----Ensure the lift will not make the patient’s condition worse.',
                '---Patient’s mental status',
                '----If alert, ensure patient is able to understand and follow instructions.',
                '----Make sure patient is ready to be placed in a lift.',
                '----The use of a patient lift should be avoided if the patient is agitated, resistant or combative.',
                '-4. Selecting a Patient’s Sling Size',
                '--1. Assess patient’s size, weight, and hip measurement.',
                '--2. Choose size of sling based on manufacturer recommendation for patient’s measurements. Choosing correct sling size is critical for safe patient transfer.',
                'SLING TOO LARGE: Patient may slip out. SLING TOO SMALL: Patient may fall out. Sling may worsen patient’s condition. IF BETWEEN SIZES: Smaller size may keep patient more secure.',
                '-5. Choose Sling and Sling Bar',
                '--To increase patient safety, use the correct type and size of sling for your patient. Select sling and sling bar based on manufacturer recommendations for the following criteria:',
                '---Type of transfer task',
                '---Patient’s medical condition',
                '---Patient’s size and weight',
                '---Pressure sensitivity Sling Bars',
                '---Use a sling bar that is appropriate for the patient’s size.',
                '---Choose sling bar/sling combination that will place patient at a safe angle.',
                '---Only use sling with correct clip or loop attachment type for the sling bar.',
                '---Need for full back support',
                '--Need for head support',
                '---Need for padding',
                '---Patient’s preferred or medical need',
                '--Some medical conditions such as stroke, orthopedic conditions, amputations, or certain wounds may affect sling choice.',
                '--Sling Bars',
                '---Use a sling bar that is appropriate for the patient’s size.',
                '---Choose sling bar/sling combination that will place patient at a safe angle.',
                '---Only use sling with correct clip or loop attachment type for the sling bar.',
                '-6. Prepare Environment',
                '--Determine number of caregivers needed:',
                '---Most lifts require two or more caregivers to safely operate lift and handle patient.',
                '--Position lift and receiving surface:',
                '---Move lift base legs near or around patient’s device.',
                '---Base legs are usually more stable in fully open position.',
                '---Position lift and receiving surface at correct height to transfer patient easily.',
                '--Clear path for lift:',
                '---Ensure there is space for lift to pivot and move freely to receiving area.',
                '---Ensure lift is able to fit under or around receiving surface and through doorways.',
                '-7. Prepare Equipment',
                '--Ensure battery is charged for transfer.',
                '--Test lift controls before bringing lift to patient.',
                '--Make sure the emergency release feature works.',
                '--Ensure receiving surface is stable and locked.',
                '--Ensure slings, hooks, chains, straps, and supports are available, appropriate, and correctly sized.',
                '--Check lift and sling weight limits.',
                '--Ensure patient’s weight does not exceed the limits.',
                '--Examine sling and attachment areas for tears, holes, and frayed seams.',
                '--DO NOT USE slings with any signs of wear.',
                '-8. Place Patient in Sling',
                '--1. Place patient in sling.',
                '---Position center of sling under patient’s spine.',
                '---Place leg straps flat under patient; do not let material fold.',
                '---Make sure sling opening is not large enough to let patient slip out or too small to let patient fall out.',
                '--2. Lower sling bar down to patient. Do not let sling bar hit patient.',
                '--3. Attach sling straps to sling bar as directed by manufacturer.',
                '---Use matching loops from each side to ensure sling is balanced.',
                '---Choose loops that provide best angle and position for patient.',
                '---Ensure all clips or loops are secure and will stay attached as patient is lifted.',
                '---Ensure straps are not twisted.',
                '---Ensure patient’s head and/or back is supported, if needed.',
                '-9. Perform Safety Check',
                '--Before lifting the patient, perform safety check:',
                '---1. Examine all hooks and fasteners to ensure they will not unhook during use.',
                '---2. Double-check position and stability of straps and other equipment before lifting patient.',
                '---3. Ensure clips, latches and bars are securely fastened and structurally sound.',
                '---4. For electric lifts, make sure batteries are always charged',
                '-10. Lift the Patient',
                '--1. Lift patient two inches off the surface to make sure patient is secure. Check the following:',
                '---Sling straps are confined by guard on sling bar and will not disengage.',
                '---Weight is spread evenly between straps.',
                '---Patient will not slide out of sling or tip backward or forward.',
                '--2. Check patient’s comfort:',
                '---Make sure sling does not pinch or pull patient’s skin.',
                '---Ask if patient is comfortable.',
                '---Look for non-verbal signs of discomfort.',
                '--3. Slowly lift patient, only as high as necessary to complete transfer. Check the following:',
                '---Patient is still comfortable.',
                '---Sling will not hurt patient’s skin.',
                '-11. Lower the Patient',
                '--1. Use gentle hands-on pressure to guide patient as you slowly move lift toward receiving surface.',
                '--2. Slowly lower patient toward receiving surface. Move patient’s body into correct position on receiving surface before releasing patient’s weight.',
                '--3. Release patient’s weight. Do not let sling bar hit patient.',
                '--4. Detach sling from lift using manufacturer’s instructions.',
                '--5. Carefully remove slings from patient’s body, if necessary.',
                '---Be careful not to hurt patient’s skin.',
                '---Ensure that seated patients do not fall forward as sling is removed.',
                '--If power fails, use the emergency release to lower patient manually.',
                '-12. Sling Care',
                '--Do not share slings between patients unless slings are properly washed and disinfected.',
                '--Disinfect and scrub areas that contact patient’s skin.',
                '--Do not bleach. Do not iron. Air dry only. Do not machine dry.',
                '--Throw away used disposable slings.',
                '--Follow manufacturer sanitation and wash instructions.',
                '--Remove metal or plastic reinforcements if required.',
                '--Sling Care Disinfect slings after every use.',
                '--Do not use slings that are frayed, ripped, or have holes. If sling shows signs of wear, replace it immediately.',
                '-13. Patient Lift Care',
                '--Follow manufacturer instructions to clean and disinfect lift.',
                '--Always clean lift before and after each patient use.',
                '--Disinfect all lift surfaces.',
                '--Wipe off traces of disinfectant.',
                '--Clean motor casings and ceiling tracks if using an overhead lift.',
            ],
        ];

        $order = 0;
        $this->seedCompetencySet($dsdCompetencyItems, $dsdPositionIds, $order);

        $sharedNurseAndCnaPositionIds = $this->getPositionIdsByTitles($sharedNurseAndCnaPositionTitles);
        // If no positions found, fallback to global so items are always seeded
        if (empty($sharedNurseAndCnaPositionIds)) {
            $sharedNurseAndCnaPositionIds = ['global'];
        }
        $this->seedCompetencySet($sharedNurseAndCnaCompetencyItems, $sharedNurseAndCnaPositionIds, $order);

        if ($licensedNursePositionIds !== []) {
            $this->seedCompetencySet($licensedNurseCompetencyItems, $licensedNursePositionIds, $order);
        }

        if ($cnaPositionIds !== []) {
            $this->seedCompetencySet($cnaCompetencyItems, $cnaPositionIds, $order);
        }
    }

    /**
     * @param  list<array<string, mixed>>  $items
     */
    protected function seedExportedCatalog(array $items): void
    {
        $positionIdsByTitle = DB::table('positions')
            ->orderBy('id')
            ->pluck('id', 'title');

        foreach ($items as $index => $row) {
            $section = trim((string) ($row['section'] ?? ''));
            $item = (string) ($row['item'] ?? '');
            if ($section === '' || $item === '') {
                continue;
            }

            $positionTitles = (array) ($row['position_titles'] ?? ['global']);
            $positionIds = in_array('global', $positionTitles, true)
                ? ['global']
                : collect($positionTitles)
                    ->map(fn ($title) => $positionIdsByTitle->get((string) $title))
                    ->filter()
                    ->map(fn ($id) => (int) $id)
                    ->unique()
                    ->values()
                    ->all();

            if ($positionIds === []) {
                $positionIds = ['global'];
            }

            EmployeeCompetencyItem::query()->updateOrCreate(
                [
                    'section' => $section,
                    'item' => $item,
                    'order' => (int) ($row['order'] ?? $index),
                ],
                [
                    'position_ids' => $positionIds,
                ]
            );
        }

        $this->command?->info('Seeded '.count($items).' exported employee competency items.');
    }
}