<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\Facility;
use App\Models\FacilityValue;

class FacilitySeeder extends Seeder
{
    public function run(): void
    {
        // Complete facilities data
        $items = [
            [
                'name' => 'Almaden Healthcare and Rehabilitation Center',
                'tagline' => 'Compassion and Care You Can Trust',
                'headline' => 'Delivering Excellence in Skilled Nursing and Rehabilitation',
                'subheadline' => 'Providing compassionate rehabilitation and skilled nursing care you can trust.',
                'address' => '2065 LOS GATOS-ALMADEN ROAD',
                'phone' => '4083779275',
                'city' => 'SAN JOSE',
                'state' => 'CA',
                'zip' => '95124',
                'beds' => 77,
                'color_scheme_id' => 6,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Almaden+Health+and+Rehabilitation++Center,2065+LOS+GATOS-ALMADEN+ROAD%2CSAN+JOSE%2CCA+95124&output=embed',
                'domain' => 'almadenhealthandrehabilitationcenter.com',
                'subdomain' => 'almadenhrc.com',
                'years' => '20',
                'facility_image' => 'almadenhcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'uLhPSFyuhbE',
                'hero_image_url' => 'hero1.jpg',
                'region' => 'seb',
                'facility_number' => '35463',
                'legal_name' => 'Almaden Operating Company LP',
                'administrator' => 'Newud Habtom',
                'don' => 'Seema Shresta',
                'dsd' => 'Aanshu Pal',
                'staffer' => 'Adrienne Ambrocio',
                'latitude' => 37.24437,
                'longitude' => -121.93338,
            ],
            [
                'name' => 'Autumn Hills Healthcare Center',
                'tagline' => 'Comfort, Dignity, and Healing Every Day',
                'headline' => 'Dedicated to care that uplifts, comforts, and heals',
                'subheadline' => 'Proudly serving our community with dedication, compassion, and respect.',
                'address' => '430 N. GLENDALE AVE',
                'phone' => '8182465677',
                'city' => 'GLENDALE',
                'state' => 'CA',
                'zip' => '91206',
                'beds' => 92,
                'color_scheme_id' => 27,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://www.google.com/maps?q=Autumn+Hills+Health+Care+Center,430+N.GLENDALE+AVE%2CGLENDALE%2CCA+91206&output=embed',
                'domain' => 'autumnhillshealthcarecenter.com',
                'subdomain' => 'autumnhillshcc.com',
                'years' => '20',
                'facility_image' => 'autumnhillshcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero2.png',
                'region' => 'socal',
                'facility_number' => '35460',
                'legal_name' => 'Autumn Hills Operating Company LP',
                'administrator' => 'Shushan Petrosyan',
                'don' => 'Jackie Moon',
                'dsd' => 'Miranda Burcham',
                'staffer' => 'Joyce Alejandro',
                'latitude' => 34.15310,
                'longitude' => -118.24320,
            ],
            [
                'name' => 'Creekside Healthcare Center',
                'tagline' => 'Where Community and Care Come Together.',
                'headline' => 'A vibrant, welcoming place for healing, hope, and connection',
                'subheadline' => 'Dedicated to bringing together community support and compassionate nursing.',
                'address' => '1900 CHURCH LANE',
                'phone' => '5102355514',
                'city' => 'SAN PABLO',
                'state' => 'CA',
                'zip' => '94806',
                'beds' => 80,
                'color_scheme_id' => 22,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Creekside+Healthcare+Center,1900+CHURCH+LANE%2CSAN+PABLO%2CCA+94806&output=embed',
                'domain' => 'creeksidehealthcarecenter.com',
                'subdomain' => 'creeksidehcc.com',
                'years' => '20',
                'facility_image' => 'creeksidehcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero3.png',
                'region' => 'esb',
                'facility_number' => '35489',
                'legal_name' => 'Creekside Operating Company, LP',
                'administrator' => 'Janet C.Rotich',
                'don' => 'Huang, Phi Hoang',
                'dsd' => 'Saras Prakash',
                'staffer' => 'Priya Vandni',
                'latitude' => 37.95701,
                'longitude' => -122.34054,
            ],
            [
                'name' => 'Driftwood Healthcare Center- Hayward',
                'tagline' => 'Restoring Health, Rebuilding Lives',
                'headline' => 'Rebuilding Lives, One Step at a Time',
                'subheadline' => 'Offering skilled nursing and rehabilitation designed to restore health and independence.',
                'address' => '19700 HESPERIAN BOULEVARD',
                'phone' => '5107852880',
                'city' => 'HAYWARD',
                'state' => 'CA',
                'zip' => '94541',
                'beds' => 88,
                'color_scheme_id' => 28,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Driftwood+Healthcare+Center+-+Hayward,19700+HESPERIAN+BOULEVARD%2CHAYWARD%2CCA+94541&output=embed',
                'domain' => 'driftwoodhealthcarecenter-hayward.com',
                'subdomain' => 'driftwoodhcc-hayward.com',
                'years' => '20',
                'facility_image' => 'driftwood-hayward.jpeg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero4.png',
                'region' => 'esb',
                'facility_number' => '35462',
                'legal_name' => 'Driftwood Hayward Operating Company LP',
                'administrator' => 'Erika Agapay',
                'don' => 'Patricia Martinez',
                'dsd' => 'Nieves Antonina',
                'staffer' => 'Joan Garcia',
                'latitude' => 37.66876,
                'longitude' => -122.11867,
            ],
            [
                'name' => 'Driftwood Healthcare Center-Santa Cruz',
                'tagline' => 'Guided by Faith, Committed to Compassion',
                'headline' => 'Where Every Resident Feels at Home',
                'subheadline' => 'Delivering dignified care and trusted support for Santa Cruz families.',
                'address' => '675 24TH AVENUE',
                'phone' => '8314756323',
                'city' => 'SANTA CRUZ',
                'state' => 'CA',
                'zip' => '95062',
                'beds' => 92,
                'color_scheme_id' => 14,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Driftwood+Healthcare+Center+-+Santa+Cruz,675+24TH+AVENUE%2CSANTA+CRUZ%2CCA+95062&output=embed',
                'domain' => 'driftwoodhealthcarecenter-santacruz.com',
                'subdomain' => 'driftwoodhcc-santacruz.com',
                'years' => '20',
                'facility_image' => 'driftwood-santacruz.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero5.png',
                'region' => 'esb',
                'facility_number' => '35464',
                'legal_name' => 'Driftwood Santa Cruz Operating Company LP',
                'administrator' => 'Fitzgerald Gaines',
                'don' => 'Navdeep Kaur ',
                'dsd' => 'Daljit Bhullar',
                'staffer' => 'Mariela Onofre',
                'latitude' => 36.96521,
                'longitude' => -121.98001,
            ],
            [
                'name' => 'Fremont Healthcare Center',
                'tagline' => 'Dedicated to Excellence in Every Step',
                'headline' => 'Excellence in Every Journey of Care',
                'subheadline' => 'Skilled professionals dedicated to recovery and wellness.',
                'address' => '39022 PRESIDIO WAY',
                'phone' => '5107923743',
                'city' => 'FREMONT',
                'state' => 'CA',
                'zip' => '94538',
                'beds' => 115,
                'color_scheme_id' => 1,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Fremont+Healthcare+Center,39022+PRESIDIO+WAY%2CFREMONT%2CCA+94538&output=embed',
                'domain' => 'fremonthealthcarecenter.com',
                'subdomain' => 'fremonthcc.com',
                'years' => '20',
                'facility_image' => 'fremonthcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero7.png',
                'region' => 'seb',
                'facility_number' => '35461',
                'legal_name' => 'Fremont Operating Company LP',
                'administrator' => 'Espinito "Jay" Caramba',
                'don' => 'Julius Ubando',
                'dsd' => 'Paul Michael Garma',
                'staffer' => 'Jeverlyn Prince',
                'latitude' => 37.54461,
                'longitude' => -121.99094,
            ],
            [
                'name' => 'Fruitvale Healthcare Center',
                'tagline' => 'Healing Hands, Caring Hearts',
                'headline' => 'Restoring strength and hope through compassionate service',
                'subheadline' => 'Providing quality healthcare for generations, rooted in dignity and compassion.',
                'address' => '3020 EAST 15TH STREET',
                'phone' => '5102615613',
                'city' => 'OAKLAND',
                'state' => 'CA',
                'zip' => '94601',
                'beds' => 140,
                'color_scheme_id' => 18,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Fruitvale+Healthcare+Center,3020+EAST+15TH+STREET%2COAKLAND%2CCA+94601&output=embed',
                'domain' => 'fruitvalehealthcarecenter.com',
                'subdomain' => 'fruitvalehcc.com',
                'years' => '20',
                'facility_image' => 'fruitvalehcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero7.png',
                'region' => 'esb',
                'facility_number' => '35456',
                'legal_name' => 'Fruitvale Operating Company LP',
                'administrator' => 'Nicholas Persinger',
                'don' => 'Sheila Lubag',
                'dsd' => 'Brigette Najjar',
                'staffer' => 'Sarina Wixson',
                'latitude' => 37.77986,
                'longitude' => -122.22682,
            ],
            [
                'name' => 'Glendale Transitional Care Center',
                'tagline' => 'Guiding Recovery With Compassion and Expertise',
                'headline' => 'Guided by Faith, Committed to Compassion',
                'subheadline' => 'Providing personalized transitional care and rehabilitation services to restore independence and quality of life.',
                'address' => '1509 Wilson Terrace, North Tower, 2nd Floor',
                'phone' => '8184098072',
                'city' => 'GLENDALE',
                'state' => 'CA',
                'zip' => '91206',
                'beds' => 92,
                'color_scheme_id' => 7,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Glendale+Transitional+Care+Center,1509+Wilson+Terrace%2C+North+Tower%2C+2nd+Floor%2CGLENDALE%2CCA+91206&output=embed',
                'domain' => 'glendaletransitionalcarecenter.com',
                'subdomain' => 'glendaletcc.com',
                'years' => '20',
                'facility_image' => 'glendaletransitionalcarecenter.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero8.png',
                'region' => 'socal',
                'facility_number' => '35490',
                'legal_name' => 'Glendale Operating Company LP',
                'administrator' => 'Sona Isayan',
                'don' => 'Norelyn Cantos',
                'dsd' => 'Josephine Lina',
                'staffer' => '',
                'latitude' => 34.15057,
                'longitude' => -118.23013,
            ],
            [
                'name' => 'Hayward Hills Healthcare Center',
                'tagline' => 'Compassionate Care, Close to Home',
                'headline' => 'Faithful Service Through Every Stage of Care',
                'subheadline' => 'Delivering personalized skilled nursing and rehabilitation services designed to support recovery, dignity, and independence',
                'address' => '1768 B Street',
                'phone' => '5105384424',
                'city' => 'HAYWARD',
                'state' => 'CA',
                'zip' => '94541',
                'beds' => 92,
                'color_scheme_id' => 9,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Hayward+Hills+Health+Care+Center,1768+B+Street%2CHAYWARD%2CCA+94541&output=embed',
                'domain' => 'haywardhillshealthcarecenter.com',
                'subdomain' => 'haywardhillshcc.com',
                'years' => '20',
                'facility_image' => 'haywardhillshcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero9.png',
                'region' => 'seb',
                'facility_number' => '35471',
                'legal_name' => 'Hayward Hills Operating Company LP',
                'administrator' => 'Kathleen Lovato',
                'don' => 'Edwinda Yap',
                'dsd' => 'Sela N. Mola',
                'staffer' => 'Leila Bustamante ',
                'latitude' => 37.68227,
                'longitude' => -122.06927,
            ],
            [
                'name' => 'Inglewood Healthcare Center',
                'tagline' => 'Caring for Life, Caring for You',
                'headline' => 'Redefining Senior Living Through Compassionate Care',
                'subheadline' => 'Delivering trusted long-term care and rehabilitation for your loved ones.',
                'address' => '100 S. HILLCREST BLVD',
                'phone' => '3106779114',
                'city' => 'INGLEWOOD',
                'state' => 'CA',
                'zip' => '90301',
                'beds' => 99,
                'color_scheme_id' => 10,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Inglewood+Health+Care+Center,100+S.+HILLCREST+BLVD%2CINGLEWOOD%2CCA+90301&output=embed',
                'domain' => 'inglewoodhealthcarecenter.com',
                'subdomain' => 'inglewoodhcc.com',
                'years' => '20',
                'facility_image' => 'inglewoodhcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero10.png',
                'region' => 'socal',
                'facility_number' => '35472',
                'legal_name' => 'Inglewood Operating Company LP',
                'administrator' => 'Kiana Moten',
                'don' => 'Firehiwot Yirgetu',
                'dsd' => 'Mary Morales',
                'staffer' => 'Laura Gutierrez ',
                'latitude' => 33.96244,
                'longitude' => -118.34851,
            ],
            [
                'name' => 'La Crescenta Healthcare',
                'tagline' => 'Trusted Care, Close to Home',
                'headline' => 'Your trusted partner in long-term and post-acute recovery.',
                'subheadline' => 'Nurturing lives through personalized care and genuine compassion.',
                'address' => '3050 MONTROSE AVE',
                'phone' => '8189570850',
                'city' => 'LA CRESCENTA',
                'state' => 'CA',
                'zip' => '91214',
                'beds' => 92,
                'color_scheme_id' => 3,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=La+Crescenta+Healthcare+Center,3050+MONTROSE+AVE%2CLA+CRESCENTA%2CCA+91214&output=embed',
                'domain' => 'lacrescentahealthcarecenter.com',
                'subdomain' => 'lacrescentahcc.com',
                'years' => '20',
                'facility_image' => 'lacrescentahcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero7.png',
                'region' => 'socal',
                'facility_number' => '35485',
                'legal_name' => 'Verdugo Vista Operating Company LP',
                'administrator' => 'Jenny Rimando',
                'don' => 'Alex Dela Cuadra',
                'dsd' => 'Zenaida Agito',
                'staffer' => 'Patricia Moreno',
                'latitude' => 34.21963,
                'longitude' => -118.24627,
            ],
            [
                'name' => 'Monterey Palms Healthcare Center',
                'tagline' => 'Healing With Warmth Under the Palms.',
                'headline' => 'Together We Heal, Together We Thrive',
                'subheadline' => 'Offering healing warmth, skilled nursing, and rehabilitation under the palms.',
                'address' => '44610 MONTEREY AVENUE',
                'phone' => '7607767700',
                'city' => 'PALM DESERT',
                'state' => 'CA',
                'zip' => '92260',
                'beds' => 99,
                'color_scheme_id' => 28,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Monterey+Palms+Health+Care+Center,44610+MONTEREY+AVENUE%2CPALM+DESERT%2CCA+92260&output=embed',
                'domain' => 'montereypalmshealthcarecenter.com',
                'subdomain' => 'montereypalmshcc.com',
                'years' => '20',
                'facility_image' => 'montereypalms.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero12.png',
                'region' => 'socal',
                'facility_number' => '35459',
                'legal_name' => 'Monterey Palms Operating Company LP',
                'administrator' => 'John Black',
                'don' => 'Claudia Olvera',
                'dsd' => 'Paloma Ysiano',
                'staffer' => 'Claudia Martinez',
                'latitude' => 33.72491,
                'longitude' => -116.38747,
            ],
            [
                'name' => 'Palm Springs Healthcare & Rehabilitation Center',
                'tagline' => 'Where Compassion Meets Quality Care',
                'headline' => 'Your Trusted Partner in Health and Healing',
                'subheadline' => 'A vibrant, welcoming place for healing, hope, and connection.',
                'address' => '277 S SUNRISE WAY',
                'phone' => '7603278541',
                'city' => 'PALM SPRINGS',
                'state' => 'CA',
                'zip' => '92262',
                'beds' => 99,
                'color_scheme_id' => 1,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Palm+Springs+Healthcare++and++Rehabilitation+Center,277+S+SUNRISE+WAY%2CPALM+SPRINGS%2CCA+92262&output=embed',
                'domain' => 'palmspringshealthandrehabilitationcenter.com',
                'subdomain' => 'palmspringshrc.com',
                'years' => '20',
                'facility_image' => 'palmspringshrc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero13.png',
                 'region' => 'socal',
                'facility_number' => '35487',
                'legal_name' => 'Palm Springs Operating Company LP',
                'administrator' => 'Dennise Pottroff',
                'don' => 'Pamela Carcamo',
                'dsd' => 'Helen Kinney',
                'staffer' => 'Rhoda Lucas',
                'latitude' => 33.82032,
                'longitude' => -116.52869,
            ],
            [
                'name' => 'Pine Ridge Healthcare Center',
                'tagline' => 'Strong Roots in Compassionate Care',
                'headline' => 'Guided by Faith, Committed to Compassion',
                'subheadline' => 'Supporting health, dignity, and independence with every resident we serve.',
                'address' => '45 PROFESSIONAL CENTER PKWY',
                'phone' => '4154793610',
                'city' => 'SAN RAFAEL',
                'state' => 'CA',
                'zip' => '94903',
                'beds' => 101,
                'color_scheme_id' => 7,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Pine+Ridge+Care+Center,45+PROFESSIONAL+CENTER+PKWY%2CSAN+RAFAEL%2CCA+94903&output=embed',
                'domain' => 'pineridgecarecenter.com',
                'subdomain' => 'pineridgehcc.com',
                'years' => '20',
                'facility_image' => 'pineridgehcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero6a.png',
                'region' => 'esb',
                'facility_number' => '35494',
                'legal_name' => 'San Rafael Operating Company LP',
                'administrator' => 'Michael Monroe ',
                'don' => 'Melijoy Adan',
                'dsd' => 'Stella Veloz',
                'staffer' => 'Candy Letatau',
                'latitude' => 38.01058,
                'longitude' => -122.53970,
            ],
            [
                'name' => 'Santa Monica Healthcare Center',
                'tagline' => 'Nurturing Health, Enriching Lives.',
                'headline' => 'Faithful Service Through Every Stage of Care',
                'subheadline' => 'Providing nurturing care and enriching lives with dignity and compassion.',
                'address' => '1320 20TH STREET',
                'phone' => '3102552800',
                'city' => 'SANTA MONICA',
                'state' => 'CA',
                'zip' => '90404',
                'beds' => 59,
                'color_scheme_id' => 27,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Santa+Monica+Health+Care+Center,1320+20TH+STREET%2CSANTA+MONICA%2CCA+90404&output=embed',
                'domain' => 'santamonicahealthcarecenter.com',
                'subdomain' => 'santamonicahcc.com',
                'years' => '20',
                'facility_image' => 'santamonicahcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero6a.png',
                 'region' => 'socal',
                'facility_number' => '35479',
                'legal_name' => 'Santa Monica Operating Company LP',
                'administrator' => 'Belinda Torres',
                'don' => 'Mary Jane Gornet',
                'dsd' => 'Maorjely Cadenas',
                'staffer' => 'Eric Trujillo',
                'latitude' => 34.02953,
                'longitude' => -118.48115,
            ],
            [
                'name' => 'Skyline Healthcare Center-San Jose',
                'tagline' => 'Compassion Rising Above the Rest',
                'headline' => 'Rising With Compassionate Care',
                'subheadline' => 'Delivering skilled nursing and rehabilitation that elevates quality of life.',
                'address' => '2065 FOREST AVENUE',
                'phone' => '4082802500',
                'city' => 'SAN JOSE',
                'state' => 'CA',
                'zip' => '95128',
                'beds' => 253,
                'color_scheme_id' => 7,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Skyline+Healthcare+Center+-+San+Jose,2065+FOREST+AVENUE%2CSAN+JOSE%2CCA+95128&output=embed',
                'domain' => 'skylinehealthcarecenter-sanjose.com',
                'subdomain' => 'skylinehcc.com',
                'years' => '20',
                'facility_image' => 'skylinehcc.jpeg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero13.png',
                'region' => 'seb',
                'facility_number' => '35481',
                'legal_name' => 'Skyline San Jose Operating Company LP',
                'administrator' => 'Mark Penyacsek',
                'don' => 'Alexine Azores',
                'dsd' => 'Madeline Webster',
                'staffer' => 'Nikki Wallace',
                'latitude' => 37.32750,
                'longitude' => -121.93523,
            ],
            [
                'name' => 'Vale Healthcare Center',
                'tagline' => 'A Legacy of Care, A Promise of Hope',
                'headline' => 'Exceptional Care in a Warm, Elegant Setting',
                'subheadline' => 'Providing skilled nursing and rehabilitation built on trust, compassion, and excellence.',
                'address' => '13484 SAN PABLO AVENUE',
                'phone' => '5102325945',
                'city' => 'SAN PABLO',
                'state' => 'CA',
                'zip' => '94806',
                'beds' => 202,
                'color_scheme_id' => 14,
                'about_image_url' => 'about-people1.png',
                'location_map' => 'https://maps.google.com/maps?q=Vale+Healthcare+Center,13484+SAN+PABLO+AVENUE%2CSAN+PABLO%2CCA+94806&output=embed',
                'domain' => 'valehealthcarecenter.com',
                'subdomain' => 'valehcc.com',
                'years' => '20',
                'facility_image' => 'valehcc.jpg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero10.png',
                'region' => 'esb',
                'facility_number' => '35486',
                'legal_name' => 'Vale Operating Company LP',
                'administrator' => 'Prarthana Chib',
                'don' => 'Germaine Carter',
                'dsd' => 'Chimere Randell',
                'staffer' => 'Yvonne Robles',
                'latitude' => 37.95584,
                'longitude' => -122.33502,
            ],
            [
                'name' => 'Village Square Healthcare Center',
                'tagline' => 'Caring Together, Growing Stronger',
                'headline' => 'Together We Heal, Together We Thrive',
                'subheadline' => 'Supporting families with skilled care that fosters strength and independence.',
                'address' => '1586 W. SAN MARCOS BLVD',
                'phone' => '7604712986',
                'city' => 'SAN MARCOS',
                'state' => 'CA',
                'zip' => '92078',
                'beds' => 118,
                'color_scheme_id' => 26,
                'about_image_url' => 'about-people.png',
                'location_map' => 'https://maps.google.com/maps?q=Village+Square+Healthcare+Center,1586+W.+SAN+MARCOS+BLVD%2CSAN+MARCOS%2CCA+92078&output=embed',
                'domain' => 'villagesquarehealthcarecenter.com',
                'subdomain' => 'villagesquarehcc.com',
                'years' => '20',
                'facility_image' => 'villagesquarehcc.jpeg',
                'hours' => '8:30 AM - 7:30 PM',
                'hero_video_id' => 'u31qwQUeGuM',
                'hero_image_url' => 'hero18.png',
                'region' => 'socal',
                'facility_number' => '35467',
                'legal_name' => 'San Marcos Operating Company LP',
                'administrator' => 'Phil Padilla',
                'don' => 'Laura Currey',
                'dsd' => 'Briahna Alexander',
                'staffer' => 'Rilen Robinson',
                'latitude' => 33.13229,
                'longitude' =>  -117.20316,
            ],
        ];

        // Seed the database
        foreach ($items as $i) {
            $facility = Facility::create([
                'color_scheme_id' => $i['color_scheme_id'] ?? 1,
                'name' => $i['name'],
                'tagline' => $i['tagline'],
                'slug' => Str::slug($i['name']),
                'logo_url' => 'bplogo.png',
                'hero_image_url' => $i['hero_image_url'] ?? 'default-hero.jpg',
                'facility_image' => $i['facility_image'] ?? 'default-facility.jpg',
                'headline' => $i['headline'],
                'subheadline' => $i['subheadline'],
                'hero_video_id' => $i['hero_video_id'] ?? null,
                'about_image_url' => $i['about_image_url'] ?? 'about-people.png',
                'about_text' => $i['name'] . ' provides personalized care and support for seniors, ensuring comfort, dignity, and quality of life.',
                'address' => ucwords(strtolower($i['address'])),
                'city' => ucwords(strtolower($i['city'])),
                'state' => $i['state'],
                'zip' => $i['zip'],
                'beds' => $i['beds'],
                'hours' => $i['hours'],
                'domain' => $i['domain'],
                'subdomain' => $i['subdomain'],
                'phone' => $i['phone'],
                'email' => 'info@example.com',
                'facebook' => 'https://facebook.com',
                'twitter' => 'https://twitter.com',
                'instagram' => 'https://instagram.com',
                'location_map' => $i['location_map'],
                'years' => $i['years'],
                'is_active' => true,
                'facility_number' => $i['facility_number'] ?? null,
                'legal_name' => $i['legal_name'] ?? null,
                'administrator' => $i['administrator'] ?? null,
                'don' => $i['don'] ?? null,
                'dsd' => $i['dsd'] ?? null,
                'staffer' => $i['staffer'] ?? null,
                'region' => $i['region'] ?? null,
                'hipaa_flags' => ['npp_page' => true, 'tls_hsts' => true, 'forms_secure' => true, 'baa_vendors' => true],
                'latitude' => $i['latitude'] ?? 34.052235,
                'longitude' => $i['longitude'] ?? -118.243683,
            ]);

            foreach (['Compassion', 'Integrity', 'Respect', 'Excellence'] as $v) {
                FacilityValue::create(['facility_id' => $facility->id, 'value' => $v]);
            }
        }
    }
}
