<?php

namespace Database\Seeders;

use App\Models\DocType;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class OrientationChecklistItemsSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $administratorPositionIds = [DB::table('positions')->where('title', 'Administrator')->value('id') ?? 1];
        $donPositionIds = [DB::table('positions')->where('title', 'Director of Nursing')->value('id') ?? 2];
        $dsdPositionIds = [DB::table('positions')->where('title', 'Director of Staff Development')->value('id') ?? 41];
        $administratorOrientationDocTypeId = $this->resolveOrientationDocTypeId('Administrator');
        $donOrientationDocTypeId = $this->resolveOrientationDocTypeId('Director of Nursing');
        $dsdOrientationDocTypeId = $this->resolveOrientationDocTypeId('Director of Staff Development');

        $AdminOrientationChecklistItems = [
            'Facility Tour',
            'Corporate Integrity Agreement (CIA) Training',
            'Mandatory Orientation Topics',
            '-Abuse/Neglect',
            '-Infection Control',
            '-Hazard Communication',
            '-Fire/Safety and Emergency Disaster Preparedness',
            'Review of Foundation Concepts',
            '-Purpose, Beliefs and Values',
            '-Organizational Structure (Divisional/Regional, Facility)',
            '-Job Description',
            '-Super Systems Introduction',
            '--Morning Meeting/Ambassador Rounds',
            '--Mini/Thorough Utilization Review',
            '--Risk Meetings',
            '-Nursing Model/Staffing',
            '-Reporting Mechanism for Unusual Occurrences/Reportable Events',
            '-Job Description',
            '-Computer/Communications Systems',
            '--Computer software and available reports',
            '--Voicemail',
            '--Paging system',
            '--E-mail',
            '--Electronic Risk Management Assistant (ERMA)',
            '--Omniview',
            '--MatrixCare/POC',
            'Introduction to Key Personnel',
            '-Facility Personnel',
            '--Department Managers',
            '--Staff',
            '--Medical Directors, Physicians, Consultants',
            '-Divisional/Regional Personnel',
            '--Executive VP of Operations (EVPO)',
            '--Chief Compliance/Risk Officer (CCO)',
            '--VP of Clinical Operations (VPCO)',
            '--VP of Finance (VPF)',
            '--Regional Director of Clinical Operations (RDCO)',
            '--Regional Director of Clinical Reimbursement (RDCR)',
            '--Regional VP of Operations (RVPO)',
            '--Regional Director of Patient Care Advocacy (RDPCA)',
            '--Regional Human Resources Director (RHRD)',
            '--Regional Director of AR/AP (RDARAP)',
            '--Regional Director of Marketing/Census Development (RDBD)/Regional Director of Case Management (RDCM)',
            '--Regional Director of Maintenance (RDM)',
            '--Regional Director of Payroll (RDP)',
            '--Regional Director of Workman\'s Comp. (RDWC)',
            '--BioPacific-VP of Rehab/Regional Rehab Director',
            '-Other Resource Personnel',
            '-Review Of Facility\'s Phone List',
            '-Review job descriptions of all staff reporting to the Administrator',
            'Review of Policy and Procedure Manuals',
            '-Resident Care Manuals (RC 1, RC 2, RC 3)',
            '-Infection Control',
            '-Updated Clinical Manual',
            '-Lippincott Nursing Procedures Book',
            '-Dietary P&P and Manual',
            '-Operations Manuals (Ops 1, Ops 2, Ops 3, Ops 4, Ops 5)',
            '-Anderson\'s Medical Records Manual',
            '-Omnicare Policy and Procedure Manual for Skilled Nursing',
            '-Omnicare IV Policy and Procedure Manual',
            '-Run for Restorative Manual',
            'MDS 3.0 overview and IDT role/PPS, QM, Star Rating, QASP, PDPM',
            'CMS and State Regulations Manuals',
            'Administrator Required Reports',
            'Survey Preparation Checklists Review',
            '-Annual',
            '-Title 22',
            '-Life Safety Code',
            '-PPD/Staffing Audit',
            'Review of Committee and Meetings',
            '-Risk-at least weekly',
            '-Falling Stars Program-weekly',
            '-Pharmacy/Psychotropics-monthly',
            '-Infection Control-monthly, with sub-committee at least quarterly',
            '-QA&A/QAPI-monthly',
            '-Policy and Procedure-annually and whenever necessary',
            '-Safety Committee-monthly',
            '-Administrative/Staff Meetings-monthly',
            '-Daily Morning Meeting with mini-UR',
            '-Weekly thorough UR',
            '-Restorative Nursing Program Meeting-weekly/monthly',
            '-Care Planning-Baseline within 48 hours, within 7 days of admission, at least quarterly thereafter following MDS schedule',
            '-Resident Council-monthly',
            'Actual Attendance of Committee and Meetings',
            '-Governing Body',
            '-Infection Control-monthly, with sub-committee at least quarterly',
            '-QA&A/QAPI-monthly',
            '-Policy and Procedure-annually and whenever necessary',
            '-Safety Committee-monthly',
            '-Administrative/Staff Meetings-monthly',
            '-Daily Morning Meeting with mini-UR',
            '-Weekly thorough UR',
            '-Resident Council-monthly (if invited)',
            'Actual Ambassador/Clinical Rounds',
            'Review of last annual survey findings and other survey deficiencies with plans of corrections',
            'Admission Process and Forms',
            'Business Development Strategies',
            'Abuse/Neglect/Exploitation Reporting and Investigation',
            'Grievances, Ombudsman Notification, Trauma Informed Care',
            'Facility Assessment',
            'Personnel Issues',
            '-Recruitment/Retention Strategies',
            '-Interviews, Qualifications, Guides, Reference Checks',
            '-Counseling and Discipline Policies',
            '-Contracted Professional Services',
            '--Laboratory',
            '--Pharmacy',
            '--Radiology',
            '--Rehabilitation',
            '--Respiratory',
            '--Disposal',
            '--Other:',
            '-Performance Evaluations-including competency/skills check',
            '-Worker\'s Compensation',
            'Fiscal Issues',
            '-Expense Budget',
            '-Capital Expense',
            '-Staffing Budget',
            '--Calculating PPDs',
            '--Allocated PPDs',
            '--Calculating FTEs',
            '--Nursing Costs',
            '-P&L Reports (Certified and Non-Certified)',
            '-Supplies and Charges',
            '-Reimbursement',
            '--Medicare/PPS ',
            '--Certified Beds',
            '--Allocating Costs',
            '--Medical',
            '--Private Pay',
            '--Insurance',
            '-Payroll/Employee Benefits',
            'Staffing Schedules',
            '-Master Schedule/Staffing Patterns',
            '-Nursing Hours/PPD',
            '-Care Assignments',
            '-Vacation/Holidays',
            '-Managing Unanticipated Absences',
            'Staff Development',
            '-Orientation',
            '-In-service Education Calendar',
            '-Professional Licenses',
            '-CPR',
            'Scheduled Exposure to Nursing Unit Experience',
            '-Day Shift',
            '-Afternoon Shift',
            '-Night Shift',
            '-Weekend Shift',
            'Scavenger Hunt (see separate checklist)',
        ];

        $dsdOrientationChecklistItems = [
            'IN-SERVICE EDUCATION:',
            '-Mandatory for ALL STAFF',
            '-Mandatory for ALL Nursing Staff',
            '-Survey-related Topics',
            '-Other topics as directed by Admin/DON',
            'ORIENTATION OF ALL NEW EMPLOYEES',
            'NEW HIRE AND ANNUAL SKILLS CHECKLISTS PER DEPARTMENT:',
            '-Licensed Nurses (RP: DON)',
            '-Certified Nursing Assistants (RP: DSD)',
            '-Director of Nursing (RP: RDCO/Administrator)',
            '-Director of Staff Development (RP: DON/RDCO)',
            '-MDS Coordinator (RP: RDMDSUR)',
            '-Dietary Staff (RP: Dietary Manager/RD)',
            '-Social Services Staff (RP: Administrator)',
            '-Other:',
            'LICENSES, CERTIFICATIONS TRACKING',
            '-RN/LVN',
            '-CNA',
            '-REHAB STAFF-Secure from Bio-Pacific',
            '-CPR-RN/LVN and PT/OT/SLP (from Bio-Pacific)',
            '-Subacute Ventilator Care Certification (RN/LVN)',
            'BACKGROUND CHECK',
            'ANNUAL MERIT EVALUATION',
            'EMPLOYEE FILES [RP: HR Assistant]',
            'I-9 FORM [RP: HR Assistant]',
            'KRONOS [RP: HR Assistant]',
            '-Time Clock Correction',
            '-Time Request',
            '-Leave of Absence',
            'HUMAN RESOURCES [RP: HR Assistant]',
            '-Historical Edit',
            '-New Hire Form',
            '-Job Data Form',
            '-Termination Form',
            '-Payroll Adjustment Form',
            '-Daily Time Correction Form',
            'DAILY PPD [RP: HR Assistant]',
            '-Licensed Nurses and Certified Nursing Assistants',
            '-Staffing Posting',
            '-Daily PPD Reports per CMS',
            'STAFFING',
            '-Daily Assignments',
            '-Monthly CNA Schedules',
            'WORKERS\' COMPENSATION Regional WC',
            'OSHA REPORTING/LOG Regional WC',
            'MODIFIED DUTY WEEKLY LOG Regional WC',
            'SAFETY MEETING Regional WC',
            'INFECTION CONTROL',
            '-Rounds-Daily/Weekly',
            '-Infection Control Surveillance Forms',
            '-Infection Control Log',
            '-Monthly/Quarterly Infection Control Reports',
            '-Care Planning',
            '-Risk Meeting',
            'IMMUNIZATION LOG',
            '-Residents\' Immunization Logs',
            '-Employees\' Immunization Logs',
            'EMPLOYEE HEALTH',
            '-Initial TB Screening',
            '-Annual TB Screening',
            '-CXR for Positive PPD + MD Clearance',
            '-Initial Physical Exam',
            '-Annual Physical Exam',
            '-Annual TB Questionnaire',
            '-Annual Flu Vaccine',
            '-Hepatitis B Vaccine',
            '-CXR every 5 years or as MD ordered',
            'POLICIES AND PROCEDURES',
            '-Infection Control Manual',
            '-Updated Surveillance Manual',
            '-Clinical Manual',
            '-Resident Care Manuals 1-3',
            '-Operations Manuals 1-5',
            '-Human Resources Manual',
            '-Dietary Manual',
            '-Anderson Medical Records Manual',
            '-Lippincott Nursing Procedures Book',
            '-Omnicare LTC Manual and IV Therapy Manual',
            'RESTORATIVE NURSING PROGRAM (Facility-specific)',
            '-RNA Weekly Meeting and Notes',
            '-Updating RNA Orders and Care Plans',
            '-RNA Monthly Recap',
            'MatrixCare (including Point Of Care-POC)',
            'OTHER:',
        ];

        $DonOrientationChecklistItems = [
            'Opportunities for staff to welcome and meet the Director of Nursing',
            'Facility Tour',
            'Corporate Integrity Agreement (CIA) Training',
            '**see separate specific training documentation',
            'Mandatory Orientation Topics (Abuse/Neglect, Infection Control, Hazard Communication, Fire/Safety and Emergency Disaster Preparedness, etc.)',
            '**see separate orientation checklist',
            'Review of Foundation Concepts',
            '-Purpose, Beliefs and Values',
            '-Organizational Structure (Divisional/Regional, Facility)',
            '-Job Description',
            '-Super Systems Introduction',
            '--Morning Meeting/Ambassador Rounds',
            '--Mini/Thorough Utilization Review',
            '--Risk Meetings',
            '-Nursing Model/Staffing',
            '-Reporting Mechanism for Unusual Occurrences/Reportable Events',
            '-Job Description',
            '-Computer/Communications Systems',
            '--Computer software and available reports',
            '--Voicemail',
            '--Paging system',
            '--E--mail',
            '--Electronic Risk Management Assistant (ERMA)',
            '--Omniview',
            '--MatrixCare/POC',
            'Introduction to key personnel',
            '-Facility personnel',
            '--Department managers',
            '--Staff',
            '--Medical Director, Physicians, Consultants',
            '-Divisional/Regional Personnel-- include directory',
            '--Executive VP of Operations (EVPO)',
            '--Chief Compliance/Risk Officer (CCO)',
            '--VP of Clinical Operations (VPCO)',
            '--VP of Finance (VPF)',
            '--Regional Director of Clinical Operations (RDCO)',
            '--Regional Director of MDS/UR (RDMDSUR)',
            '--Regional VP of Operations (RVPO)',
            '--Regional Director of Patient Care Advocacy (RDPCA)',
            '--Regional Human Resources Director (RHRD)',
            '--Regional Director of AR/AP (RDARAP)',
            '--Regional Director of Marketing/Census Development',
            '--Regional Director of Maintenance',
            '--Regional Director of Payroll',
            '--Regional Director of Workman\'s Comp.',
            '--BioPacific--VP of Rehab/Regional Rehab Director',
            '-Other resource personnel (specify)',
            '-Review of facility\'s phone list',
            '-Review job descriptions of all staff reporting to the DON',
            'Review of Policy and Procedure Manuals',
            '-Resident Care Manuals (RC 1, RC 2, RC 3)',
            '-Infection Control',
            '-Updated Clinical Manual',
            '-Lippincott Nursing Procedures Book',
            '-Dietary P&P and Manual',
            '-Operations Manuals (Ops 1, Ops 2, Ops 3, Ops 4, Ops 5)',
            '-Anderson\'s Medical Records Manual',
            '-Omnicare Policy and Procedure Manual for Skilled Nursing',
            '-Omnicare IV Policy and Procedure Manual',
            '-Run for Restorative Manual',
            'MDS 3.0 overview and IDT role/PPS. Star Rating. QASP.',
            'CMS and State Regulations Manuals',
            'DON Reports',
            '-Weekly',
            '-Monthly',
            'Survey Preparation Checklists Review',
            '-Annual',
            '-Title 22',
            '-Life Safety Code',
            'Review of Committee and Meetings',
            '-Risk--at least weekly',
            '-Pharmacy/Psychotropics--monthly',
            '-Infection Control--monthly, with sub--committee at least quarterly',
            '-QA&A--monthly',
            '-Policy and Procedure--annually and whenever necessary',
            '-Safety Committee--monthly',
            '-Administrative/staff meetings--monthly',
            '-Daily Morning Meeting with mini--UR',
            '-Weekly thorough UR',
            '-Restorative Nursing Program Meeting--weekly/monthly',
            '-Care Planning--Baseline within 48 hours, within 7 days of admission, at least quarterly thereafter following MDS schedule',
            '-Resident Council--monthly',
            '-Family Council--monthly or as indicated (when available)',
            'Actual Attendance of Committee and Meetings',
            '-Risk--at least weekly',
            '-Pharmacy/Psychotropics--monthly',
            '-Infection Control--monthly, with sub--committee at least quarterly',
            '-QA&A/QAPI--monthly',
            '-Policy and Procedure--annually and whenever necessary',
            '-Safety Committee--monthly',
            '-Administrative/staff meetings--monthly',
            '-Daily Morning Meeting with mini--UR',
            '-Weekly thorough UR',
            '-Restorative Nursing Program Meeting--weekly/monthly',
            '-Care Planning--within 7 days of admission, at least quarterly thereafter following MDS schedule',
            '-Resident Council--monthly',
            '-Family Council--monthly or as indicated',
            'Actual Ambassador/Clinical Rounds',
            'Review of last annual survey findings and other survey deficiencies with plans of corrections',
            'Admission Process and Forms',
            'Abuse/Neglect investigation, Grievances',
            'Personnel Issues',
            '-Recruitment/Retention Strategies',
            '-Interviews, Qualifications, Guides, Reference Checks',
            '-Counseling and Discipline Policies',
            '-Contracted Professional Services',
            '--Laboratory',
            '--Pharmacy',
            '--Radiology',
            '--Rehabilitation',
            '--Respiratory',
            '--Disposal',
            '--Other',
            '-Worker\'s Compensation',
            '-Performance Evaluations--including competency/skills check',
            'Fiscal Issues',
            '-Expense Budget',
            '-Capital Expense',
            '-Staffing Budget',
            '--Calculating PPDs',
            '--Allocated PPDs',
            '--Calculating FTEs',
            '--Nursing Costs',
            '-P&L Reports (Certified and Non--Certified)',
            '-Supplies and Charges',
            '-Reimbursement',
            '--Medicare/PPS ',
            '--Certified Beds',
            '--Allocating Costs',
            '--Medical',
            '--Private Pay',
            '--Insurance',
            '-Payroll/Employee Benefits',
            'Staffing Schedules',
            '-Master Schedule/Staffing Patterns',
            '-Nursing Hours/PPD',
            '-Care Assignments',
            '-Vacation/Holidays',
            '-Managing Unanticipated Absences',
            'Staff Development',
            '-Orientation',
            '-In--service Education Calendar',
            '-Professional Licenses',
            '-CPR',
            'Scheduled Exposure to Nursing Unit Experience',
            '-Day Shift',
            '-Afternoon Shift',
            '-Night Shift',
            '-Weekend Shift',
            'Scavenger Hunt (see separate checklist)',
        ];

        $items = [
            ...array_map(static fn (string $name): array => [
                'name' => $name,
                'section' => 'PART E',
                'doc_type_id' => $administratorOrientationDocTypeId,
                'position_ids' => $administratorPositionIds,
            ], $AdminOrientationChecklistItems),
            ...array_map(static fn (string $name): array => [
                'name' => $name,
                'section' => 'PART E',
                'doc_type_id' => $donOrientationDocTypeId,
                'position_ids' => $donPositionIds,
            ], $DonOrientationChecklistItems),
            ...array_map(static fn (string $name): array => [
                'name' => $name,
                'section' => 'PART E',
                'doc_type_id' => $dsdOrientationDocTypeId,
                'position_ids' => $dsdPositionIds,
            ], $dsdOrientationChecklistItems),
        ];

        $order = (int) DB::table('checklist_items')->max('order') + 1;

        foreach ($items as $item) {
            DB::table('checklist_items')->insert([
                'name' => $item['name'],
                'section' => $item['section'],
                'doc_type_id' => $item['doc_type_id'],
                'position_ids' => json_encode($item['position_ids']),
                'order' => $order,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
            $order++;
        }
    }

    private function resolveOrientationDocTypeId(string $positionName): int
    {
        $docTypeName = match (true) {
            stripos($positionName, 'administrator') !== false => 'Administrator Orientation',
            stripos($positionName, 'director of nursing') !== false,
            stripos($positionName, 'don') !== false => 'DON Orientation Checklist',
            stripos($positionName, 'staff development') !== false,
            stripos($positionName, 'dsd') !== false => 'New DSD Orientation Checklist',
            default => throw new \InvalidArgumentException("Unsupported orientation position: {$positionName}"),
        };

        $docTypeId = DocType::query()->where('name', $docTypeName)->value('id');

        if (!$docTypeId) {
            throw new \RuntimeException("Missing doc type for orientation seeder: {$docTypeName}");
        }

        return (int) $docTypeId;
    }
}