<?php

namespace App\Services;

use App\Models\EmployeeTrainingItem;
use App\Models\Position;
use Illuminate\Support\Carbon;

class EmployeeTrainingItemsSeederExporter
{
    public function dataFilePath(): string
    {
        return database_path('seeders/data/employee_training_items.php');
    }

    /**
     * @return array{count: int, path: string}
     */
    public function writeSeederFile(): array
    {
        $trainings = $this->collectTrainingData();
        $path = $this->dataFilePath();

        if (! is_dir(dirname($path))) {
            throw new \RuntimeException('Seeders data directory not found.');
        }

        if (file_put_contents($path, $this->buildDataFileContents($trainings)) === false) {
            throw new \RuntimeException('Could not write the employee training items seeder data file.');
        }

        return [
            'count' => count($trainings),
            'path' => $path,
        ];
    }

    /**
     * @return list<array{
     *     name: string,
     *     description: ?string,
     *     content_url: ?string,
     *     provider_label: ?string,
     *     frequency: string,
     *     position_titles: list<string>,
     *     order: int,
     *     is_active: bool
     * }>
     */
    public function collectTrainingData(): array
    {
        $positionTitles = Position::query()
            ->orderBy('id')
            ->pluck('title', 'id');

        return EmployeeTrainingItem::query()
            ->orderBy('order')
            ->orderBy('name')
            ->get()
            ->map(function (EmployeeTrainingItem $training) use ($positionTitles): array {
                $positionIds = (array) ($training->position_ids ?? []);
                $appliesToEveryone = $positionIds === []
                    || in_array('global', $positionIds, true);

                $titles = $appliesToEveryone
                    ? ['global']
                    : collect($positionIds)
                        ->map(fn ($id) => $positionTitles->get((int) $id))
                        ->filter()
                        ->map(fn ($title) => (string) $title)
                        ->unique()
                        ->values()
                        ->all();

                return [
                    'name' => (string) $training->name,
                    'description' => filled($training->description) ? (string) $training->description : null,
                    'content_url' => filled($training->content_url) ? (string) $training->content_url : null,
                    'provider_label' => filled($training->provider_label) ? (string) $training->provider_label : null,
                    'frequency' => (string) $training->frequency,
                    'position_titles' => $titles,
                    'order' => (int) $training->order,
                    'is_active' => (bool) $training->is_active,
                ];
            })
            ->values()
            ->all();
    }

    /**
     * @param  list<array<string, mixed>>  $trainings
     */
    protected function buildDataFileContents(array $trainings): string
    {
        $exportedAt = Carbon::now()->toDateTimeString();
        $export = var_export($trainings, true);

        return <<<PHP
<?php

/**
 * Employee training catalog.
 *
 * Position assignments use titles so they remain valid after database IDs are
 * regenerated by migrate:fresh.
 *
 * Auto-generated from Training Configuration → Update seeder on {$exportedAt}.
 *
 * @return list<array{
 *     name: string,
 *     description: ?string,
 *     content_url: ?string,
 *     provider_label: ?string,
 *     frequency: string,
 *     position_titles: list<string>,
 *     order: int,
 *     is_active: bool
 * }>
 */
return {$export};

PHP;
    }
}
