<?php

namespace App\Services;

use App\Models\EmployeeCompetencyItem;
use App\Models\Position;
use Illuminate\Support\Carbon;

class EmployeeCompetencyItemsSeederExporter
{
    public function dataFilePath(): string
    {
        return database_path('seeders/data/employee_competency_items.php');
    }

    /**
     * @return array{count: int, path: string}
     */
    public function writeSeederFile(): array
    {
        $items = $this->collectCompetencyData();
        $path = $this->dataFilePath();

        if (! is_dir(dirname($path))) {
            throw new \RuntimeException('Seeders data directory not found.');
        }

        if (file_put_contents($path, $this->buildDataFileContents($items)) === false) {
            throw new \RuntimeException('Could not write the employee competency items seeder data file.');
        }

        return [
            'count' => count($items),
            'path' => $path,
        ];
    }

    /**
     * @return list<array{
     *     section: string,
     *     item: string,
     *     position_titles: list<string>,
     *     order: int
     * }>
     */
    public function collectCompetencyData(): array
    {
        $positionTitles = Position::query()
            ->orderBy('id')
            ->pluck('title', 'id');

        return EmployeeCompetencyItem::query()
            ->orderBy('section')
            ->orderBy('order')
            ->orderBy('id')
            ->get()
            ->map(function (EmployeeCompetencyItem $row) use ($positionTitles): array {
                $positionIds = (array) ($row->position_ids ?? []);
                $appliesToEveryone = $positionIds === []
                    || in_array('global', $positionIds, true);

                $titles = $appliesToEveryone
                    ? ['global']
                    : collect($positionIds)
                        ->map(fn ($id) => $positionTitles->get((int) $id))
                        ->filter()
                        ->map(fn ($title) => (string) $title)
                        ->unique()
                        ->values()
                        ->all();

                return [
                    'section' => (string) $row->section,
                    'item' => (string) $row->item,
                    'position_titles' => $titles,
                    'order' => (int) $row->order,
                ];
            })
            ->values()
            ->all();
    }

    /**
     * @param  list<array<string, mixed>>  $items
     */
    protected function buildDataFileContents(array $items): string
    {
        $exportedAt = Carbon::now()->toDateTimeString();
        $export = var_export($items, true);

        return <<<PHP
<?php

/**
 * Employee competency catalog (Part G).
 *
 * Position assignments use titles so they remain valid after database IDs are
 * regenerated by migrate:fresh.
 *
 * Auto-generated from Competencies Management → Update seeder on {$exportedAt}.
 *
 * @return list<array{
 *     section: string,
 *     item: string,
 *     position_titles: list<string>,
 *     order: int
 * }>
 */
return {$export};

PHP;
    }
}
