<?php

/**
 * Employee training catalog.
 *
 * Position assignments use titles so they remain valid after database IDs are
 * regenerated by migrate:fresh.
 *
 * Auto-generated from Training Configuration → Update seeder on 2026-07-23 15:34:55.
 *
 * @return list<array{
 *     name: string,
 *     description: ?string,
 *     content_url: ?string,
 *     provider_label: ?string,
 *     frequency: string,
 *     position_titles: list<string>,
 *     order: int,
 *     is_active: bool
 * }>
 */
return array (
  0 => 
  array (
    'name' => 'California Required Sexual Harassment Training for ALL Employees',
    'description' => 'Relias code: REL-ALL-0-CRSHTE. Mandatory California sexual harassment training for all employees. Provide for new hires within 6 months of hire, then every 2 years.',
    'content_url' => NULL,
    'provider_label' => 'Relias (REL-ALL-0-CRSHTE)',
    'frequency' => 'biennial',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 1,
    'is_active' => true,
  ),
  1 => 
  array (
    'name' => 'Understanding Sexual Harassment for Supervisors CA',
    'description' => 'Relias code: REL-ALL-0-CRSHTS. California sexual harassment training for supervisors. Provide within 6 months of assuming supervisory duties, then every 2 years.',
    'content_url' => NULL,
    'provider_label' => 'Relias (REL-ALL-0-CRSHTS)',
    'frequency' => 'biennial',
    'position_titles' => 
    array (
      0 => 'Administrator',
      1 => 'Director of Nursing',
      2 => 'Director of Staff Development',
      3 => 'Staff Development Coordinator',
      4 => 'Business Office Manager',
      5 => 'Social Services Director',
      6 => 'Food Services Director',
      7 => 'Maintenance Director',
      8 => 'Housekeeping Supervisor',
      9 => 'Activities Director',
      10 => 'Rehab Manager',
      11 => 'Medical Records Director',
      12 => 'Marketing Director',
    ),
    'order' => 2,
    'is_active' => true,
  ),
  2 => 
  array (
    'name' => 'Workplace Violence Prevention in CA',
    'description' => 'Relias code: REL-PAC-0-WVPC. Completed upon hire and every year, and whenever new hazards are introduced. Required for all employees.',
    'content_url' => NULL,
    'provider_label' => 'Relias (REL-PAC-0-WVPC)',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 3,
    'is_active' => true,
  ),
  3 => 
  array (
    'name' => 'Ethics and Corporate Compliance',
    'description' => 'Relias code: REL-ALL-0-ETHCC. Completed upon hire and every year. Required for all employees.',
    'content_url' => NULL,
    'provider_label' => 'Relias (REL-ALL-0-ETHCC)',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 4,
    'is_active' => true,
  ),
  4 => 
  array (
    'name' => 'HIPAA: Basics',
    'description' => 'Relias code: REL-ALL-0-HBAS. Completed upon hire and every year. Required for all employees.',
    'content_url' => NULL,
    'provider_label' => 'Relias (REL-ALL-0-HBAS)',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 5,
    'is_active' => true,
  ),
  5 => 
  array (
    'name' => 'Caring for LGBTQIA+ Residents in California',
    'description' => 'Relias code: REL-PAC-0-CLFBRC. Completed upon hire and every year. Required for all employees, including the Medical Director for each facility.',
    'content_url' => NULL,
    'provider_label' => 'Relias (REL-PAC-0-CLFBRC)',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 6,
    'is_active' => true,
  ),
  6 => 
  array (
    'name' => 'WVPP (Workplace Violence Prevention Plan)',
    'description' => 'Facility Workplace Violence Prevention Plan acknowledgement/training. Completed upon hire and every year. Required for all employees.',
    'content_url' => NULL,
    'provider_label' => 'Internal',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 7,
    'is_active' => true,
  ),
  7 => 
  array (
    'name' => 'SB 294: California Workplace – Know Your Rights',
    'description' => 'California SB 294 workplace Know Your Rights training. Completed upon hire and every year. Required for all employees.',
    'content_url' => NULL,
    'provider_label' => 'Internal / State Compliance',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 8,
    'is_active' => true,
  ),
  8 => 
  array (
    'name' => 'CNA: Problem Needs of the Aged',
    'description' => 'CDPH CNA in-service — 2 hours. Problem and care needs of the aged.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 9,
    'is_active' => true,
  ),
  9 => 
  array (
    'name' => 'CNA: Prevention and Control of Infection',
    'description' => 'CDPH CNA in-service — 2 hours. Prevention and control of infection.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 10,
    'is_active' => true,
  ),
  10 => 
  array (
    'name' => 'CNA: Fire Prevention / Disaster Preparedness',
    'description' => 'CDPH CNA in-service — 4 hours. Fire prevention and disaster preparedness.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 11,
    'is_active' => true,
  ),
  11 => 
  array (
    'name' => 'CNA: Accident Prevention and Safety',
    'description' => 'CDPH CNA in-service — 2 hours. Accident prevention and safety.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 12,
    'is_active' => true,
  ),
  12 => 
  array (
    'name' => 'CNA: Residents’ Rights',
    'description' => 'CDPH CNA in-service — 2 hours. Residents’ rights.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 13,
    'is_active' => true,
  ),
  13 => 
  array (
    'name' => 'CNA: Bloodborne Pathogens',
    'description' => 'CDPH CNA in-service — 2 hours. Bloodborne pathogens.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 14,
    'is_active' => true,
  ),
  14 => 
  array (
    'name' => 'CNA: Choking Prevention',
    'description' => 'CDPH CNA in-service — 2 hours. Choking prevention.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 15,
    'is_active' => true,
  ),
  15 => 
  array (
    'name' => 'CNA: Theft and Loss',
    'description' => 'CDPH CNA in-service — 2 hours. Theft and loss prevention/reporting.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 16,
    'is_active' => true,
  ),
  16 => 
  array (
    'name' => 'CNA: TB Facts',
    'description' => 'CDPH CNA in-service — 1 hour. Tuberculosis facts.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 17,
    'is_active' => true,
  ),
  17 => 
  array (
    'name' => 'CNA: HIPAA',
    'description' => 'CDPH CNA in-service — 1 hour. HIPAA privacy for CNAs.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 18,
    'is_active' => true,
  ),
  18 => 
  array (
    'name' => 'CNA: Hazard Communication / SDS / PPE',
    'description' => 'CDPH CNA in-service — 1 hour. Hazard communication, SDS, and PPE.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 19,
    'is_active' => true,
  ),
  19 => 
  array (
    'name' => 'CNA: Interpersonal Relationships / Communication Skills',
    'description' => 'CDPH CNA in-service — 1 hour. Interpersonal relationships and communication skills.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 20,
    'is_active' => true,
  ),
  20 => 
  array (
    'name' => 'CNA: Advance Directives',
    'description' => 'CDPH CNA in-service — 1 hour. Advance directives.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 21,
    'is_active' => true,
  ),
  21 => 
  array (
    'name' => 'CNA: Bowel and Bladder Retraining',
    'description' => 'CDPH CNA in-service — 1 hour. Bowel and bladder (B&B) retraining.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 22,
    'is_active' => true,
  ),
  22 => 
  array (
    'name' => 'CNA: Wandering Resident / Elopement',
    'description' => 'CDPH CNA in-service — 1 hour. Wandering resident and elopement prevention.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 23,
    'is_active' => true,
  ),
  23 => 
  array (
    'name' => 'CNA: Elder Abuse and Neglect',
    'description' => 'CDPH CNA in-service — 4 hours. Resident abuse training required every 2 years (each renewal period).',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'biennial',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 24,
    'is_active' => true,
  ),
  24 => 
  array (
    'name' => 'CNA: Fall Prevention',
    'description' => 'CDPH CNA in-service — 2 hours. Fall prevention.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 25,
    'is_active' => true,
  ),
  25 => 
  array (
    'name' => 'CNA: Pressure Ulcer Prevention',
    'description' => 'CDPH CNA in-service — 2 hours. Pressure ulcer prevention.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 26,
    'is_active' => true,
  ),
  26 => 
  array (
    'name' => 'CNA: Nutrition and Hydration',
    'description' => 'CDPH CNA in-service — 1 hour. Nutrition and hydration.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 27,
    'is_active' => true,
  ),
  27 => 
  array (
    'name' => 'CNA: Dementia',
    'description' => 'CDPH CNA in-service — 5 hours. Dementia-specific training required every year.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 28,
    'is_active' => true,
  ),
  28 => 
  array (
    'name' => 'CNA: Multiple Sclerosis',
    'description' => 'CDPH CNA in-service — 1 hour. Multiple sclerosis care awareness.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 29,
    'is_active' => true,
  ),
  29 => 
  array (
    'name' => 'CNA: Dignity and Privacy',
    'description' => 'CDPH CNA in-service — 1 hour. Dignity and privacy.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 30,
    'is_active' => true,
  ),
  30 => 
  array (
    'name' => 'CNA: How to Deal with Combative Residents',
    'description' => 'CDPH CNA in-service — 1 hour. Working with combative residents.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 31,
    'is_active' => true,
  ),
  31 => 
  array (
    'name' => 'CNA: Care of Residents with CVA and Diabetes',
    'description' => 'CDPH CNA in-service — 1 hour. Care of residents with CVA and diabetes.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 32,
    'is_active' => true,
  ),
  32 => 
  array (
    'name' => 'CNA: Restraint Reduction / ROM',
    'description' => 'CDPH CNA in-service — 1 hour. Restraint reduction and range of motion (ROM).',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 33,
    'is_active' => true,
  ),
  33 => 
  array (
    'name' => 'CNA: Signs/Symptoms of Cardiopulmonary Disease',
    'description' => 'CDPH CNA in-service — 1 hour. Signs and symptoms of cardiopulmonary disease.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 34,
    'is_active' => true,
  ),
  34 => 
  array (
    'name' => 'CNA: Turning and Repositioning (Actual Demo)',
    'description' => 'CDPH CNA in-service — 1 hour. Turning and repositioning with actual demonstration.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 35,
    'is_active' => true,
  ),
  35 => 
  array (
    'name' => 'CNA: Safe Transfers',
    'description' => 'CDPH CNA in-service — 2 hours. Safe transfers.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 36,
    'is_active' => true,
  ),
  36 => 
  array (
    'name' => 'CNA: Sexual Harassment',
    'description' => 'CDPH CNA in-service — 1 hour. Sexual harassment training for CNAs (facility in-service program).',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 37,
    'is_active' => true,
  ),
  37 => 
  array (
    'name' => 'CNA: Pain Management',
    'description' => 'CDPH CNA in-service — 1 hour. Pain management.',
    'content_url' => NULL,
    'provider_label' => 'CDPH 278B / CNA In-Service',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 38,
    'is_active' => true,
  ),
  38 => 
  array (
    'name' => 'New Hire Orientation & Facility Tour',
    'description' => 'Facility orientation covering mission, chain of command, emergency exits, and resident rights overview.',
    'content_url' => '/trainings/new-hire-orientation',
    'provider_label' => 'Internal',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 39,
    'is_active' => false,
  ),
  39 => 
  array (
    'name' => 'HIPAA Privacy & Security Awareness',
    'description' => 'Protected health information (PHI), minimum necessary standard, and breach reporting.',
    'content_url' => 'https://lms.example.com/modules/hipaa-privacy',
    'provider_label' => 'LMS Provider',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 40,
    'is_active' => false,
  ),
  40 => 
  array (
    'name' => 'Abuse, Neglect & Exploitation Reporting',
    'description' => 'Mandated reporting, recognition of abuse/neglect, and immediate notification procedures (SNF compliance).',
    'content_url' => 'https://lms.example.com/modules/abuse-neglect-reporting',
    'provider_label' => 'LMS Provider',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 41,
    'is_active' => false,
  ),
  41 => 
  array (
    'name' => 'Infection Prevention Basics (Standard Precautions)',
    'description' => 'Hand hygiene, PPE, transmission-based precautions, and bloodborne pathogens overview.',
    'content_url' => '/trainings/infection-prevention-basics',
    'provider_label' => 'Internal',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 42,
    'is_active' => false,
  ),
  42 => 
  array (
    'name' => 'Emergency Preparedness & Fire Safety',
    'description' => 'RACE/PASS, evacuation routes, disaster roles, and facility emergency codes.',
    'content_url' => '/trainings/emergency-preparedness',
    'provider_label' => 'Internal',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 43,
    'is_active' => false,
  ),
  43 => 
  array (
    'name' => 'Corporate Compliance & Code of Conduct',
    'description' => 'Fraud/waste/abuse awareness, false claims, and how to report compliance concerns.',
    'content_url' => 'https://lms.example.com/modules/corporate-compliance',
    'provider_label' => 'LMS Provider',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 44,
    'is_active' => false,
  ),
  44 => 
  array (
    'name' => 'Workplace Violence Prevention',
    'description' => 'De-escalation, reporting workplace violence, and staff safety expectations.',
    'content_url' => 'https://lms.example.com/modules/workplace-violence',
    'provider_label' => 'LMS Provider',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 45,
    'is_active' => false,
  ),
  45 => 
  array (
    'name' => 'Annual HIPAA Refresher',
    'description' => 'Annual privacy/security refresher required for all workforce members with PHI access.',
    'content_url' => 'https://lms.example.com/modules/hipaa-annual',
    'provider_label' => 'LMS Provider',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 46,
    'is_active' => false,
  ),
  46 => 
  array (
    'name' => 'Annual Abuse Prevention & Mandated Reporting',
    'description' => 'Annual refresher on abuse prevention, elder justice, and reporting timelines.',
    'content_url' => 'https://lms.example.com/modules/abuse-prevention-annual',
    'provider_label' => 'LMS Provider',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 47,
    'is_active' => false,
  ),
  47 => 
  array (
    'name' => 'Annual Infection Control & Bloodborne Pathogens',
    'description' => 'OSHA bloodborne pathogens and facility infection prevention annual update.',
    'content_url' => 'https://lms.example.com/modules/infection-control-annual',
    'provider_label' => 'LMS Provider',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 48,
    'is_active' => false,
  ),
  48 => 
  array (
    'name' => 'Annual Fire Safety & Disaster Drill Acknowledgement',
    'description' => 'Document participation/acknowledgement of annual fire and disaster preparedness training.',
    'content_url' => '/trainings/fire-safety-annual',
    'provider_label' => 'Internal',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 49,
    'is_active' => false,
  ),
  49 => 
  array (
    'name' => 'Annual Compliance & Ethics Refresher',
    'description' => 'Annual compliance program training including reporting hotline and non-retaliation.',
    'content_url' => 'https://lms.example.com/modules/compliance-annual',
    'provider_label' => 'LMS Provider',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'global',
    ),
    'order' => 50,
    'is_active' => false,
  ),
  50 => 
  array (
    'name' => 'Resident Rights & Person-Centered Care',
    'description' => 'Dignity, privacy, choice, and person-centered care expectations for clinical staff.',
    'content_url' => '/trainings/resident-rights',
    'provider_label' => 'Internal',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
      2 => 'Licensed Vocational Nurse',
      3 => 'Licensed Nurse',
      4 => 'Registered Nurse',
      5 => 'Charge Nurse',
      6 => 'Director of Nursing',
      7 => 'IP Nurse',
      8 => 'Staff Development Coordinator',
      9 => 'Director of Staff Development',
      10 => 'MDS Coordinator',
      11 => 'Unit Clerk',
    ),
    'order' => 51,
    'is_active' => false,
  ),
  51 => 
  array (
    'name' => 'Fall Prevention & Safe Resident Handling',
    'description' => 'Fall risk interventions, gait belts, and safe patient handling equipment use.',
    'content_url' => 'https://lms.example.com/modules/fall-prevention',
    'provider_label' => 'LMS Provider',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
      2 => 'Licensed Vocational Nurse',
      3 => 'Licensed Nurse',
      4 => 'Registered Nurse',
      5 => 'Charge Nurse',
      6 => 'Director of Nursing',
      7 => 'IP Nurse',
      8 => 'Staff Development Coordinator',
      9 => 'Director of Staff Development',
      10 => 'MDS Coordinator',
      11 => 'Unit Clerk',
    ),
    'order' => 52,
    'is_active' => false,
  ),
  52 => 
  array (
    'name' => 'Pressure Injury Prevention',
    'description' => 'Skin assessment, repositioning, and pressure injury prevention protocols.',
    'content_url' => 'https://lms.example.com/modules/pressure-injury-prevention',
    'provider_label' => 'LMS Provider',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
      2 => 'Licensed Vocational Nurse',
      3 => 'Licensed Nurse',
      4 => 'Registered Nurse',
      5 => 'Charge Nurse',
      6 => 'Director of Nursing',
      7 => 'IP Nurse',
      8 => 'Staff Development Coordinator',
      9 => 'Director of Staff Development',
      10 => 'MDS Coordinator',
      11 => 'Unit Clerk',
    ),
    'order' => 53,
    'is_active' => false,
  ),
  53 => 
  array (
    'name' => 'CNA Skills Competency Orientation',
    'description' => 'Core CNA skills verification orientation (ADL care, vitals assist, documentation basics).',
    'content_url' => '/trainings/cna-skills-orientation',
    'provider_label' => 'Internal / DSD',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 54,
    'is_active' => false,
  ),
  54 => 
  array (
    'name' => 'CNA 12-Hour Annual In-Service',
    'description' => 'California/SNF CNA annual in-service hours tracking acknowledgement.',
    'content_url' => '/trainings/cna-annual-inservice',
    'provider_label' => 'Internal / DSD',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Certified Nursing Assistant',
      1 => 'Nursing Assistant',
    ),
    'order' => 55,
    'is_active' => false,
  ),
  55 => 
  array (
    'name' => 'Medication Administration & eMAR Safety',
    'description' => 'Five/six rights, eMAR documentation, controlled substances, and med error reporting.',
    'content_url' => 'https://lms.example.com/modules/medication-administration',
    'provider_label' => 'LMS Provider',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'Licensed Vocational Nurse',
      1 => 'Licensed Nurse',
      2 => 'Registered Nurse',
      3 => 'Charge Nurse',
      4 => 'Director of Nursing',
      5 => 'IP Nurse',
      6 => 'MDS Coordinator',
    ),
    'order' => 56,
    'is_active' => false,
  ),
  56 => 
  array (
    'name' => 'Antibiotic Stewardship Awareness',
    'description' => 'Appropriate antibiotic use and infection prevention collaboration for licensed nurses.',
    'content_url' => 'https://lms.example.com/modules/antibiotic-stewardship',
    'provider_label' => 'LMS Provider',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Licensed Vocational Nurse',
      1 => 'Licensed Nurse',
      2 => 'Registered Nurse',
      3 => 'Charge Nurse',
      4 => 'Director of Nursing',
      5 => 'IP Nurse',
      6 => 'MDS Coordinator',
    ),
    'order' => 57,
    'is_active' => false,
  ),
  57 => 
  array (
    'name' => 'Change of Condition & SBAR Communication',
    'description' => 'Recognizing change of condition and structured SBAR communication with providers.',
    'content_url' => '/trainings/sbar-change-of-condition',
    'provider_label' => 'Internal',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Licensed Vocational Nurse',
      1 => 'Licensed Nurse',
      2 => 'Registered Nurse',
      3 => 'Charge Nurse',
      4 => 'Director of Nursing',
      5 => 'IP Nurse',
      6 => 'MDS Coordinator',
    ),
    'order' => 58,
    'is_active' => false,
  ),
  58 => 
  array (
    'name' => 'Food Safety & Sanitation (ServSafe Basics)',
    'description' => 'Temperature control, cross-contamination prevention, and dietary sanitation standards.',
    'content_url' => 'https://lms.example.com/modules/food-safety',
    'provider_label' => 'LMS Provider',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'Dietary Manager',
      1 => 'Dietary Aide',
      2 => 'Cook',
      3 => 'Food Services Director',
    ),
    'order' => 59,
    'is_active' => false,
  ),
  59 => 
  array (
    'name' => 'Texture-Modified Diets & Aspiration Precautions',
    'description' => 'IDDSI/texture diets, thickening liquids, and aspiration risk precautions.',
    'content_url' => '/trainings/texture-modified-diets',
    'provider_label' => 'Internal',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Dietary Manager',
      1 => 'Dietary Aide',
      2 => 'Cook',
      3 => 'Food Services Director',
    ),
    'order' => 60,
    'is_active' => false,
  ),
  60 => 
  array (
    'name' => 'Environmental Cleaning & Disinfection Protocols',
    'description' => 'Terminal cleaning, EPA-registered disinfectants, and isolation room cleaning.',
    'content_url' => 'https://lms.example.com/modules/environmental-cleaning',
    'provider_label' => 'LMS Provider',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'Housekeeper',
      1 => 'Housekeeping Supervisor',
      2 => 'Janitor',
      3 => 'Laundry Staff',
      4 => 'Maintenance Director',
      5 => 'Maintenance Technician',
    ),
    'order' => 61,
    'is_active' => false,
  ),
  61 => 
  array (
    'name' => 'Hazard Communication (GHS / SDS)',
    'description' => 'Chemical labeling, Safety Data Sheets, and PPE for facility chemicals.',
    'content_url' => 'https://lms.example.com/modules/hazard-communication',
    'provider_label' => 'LMS Provider',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Housekeeper',
      1 => 'Housekeeping Supervisor',
      2 => 'Janitor',
      3 => 'Laundry Staff',
      4 => 'Maintenance Director',
      5 => 'Maintenance Technician',
    ),
    'order' => 62,
    'is_active' => false,
  ),
  62 => 
  array (
    'name' => 'Resident Rights Advocacy & Grievance Process',
    'description' => 'Grievance procedures, ombudsman role, and psychosocial well-being support.',
    'content_url' => '/trainings/resident-rights-advocacy',
    'provider_label' => 'Internal',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'Social Services Director',
      1 => 'Social Worker',
      2 => 'Resident Liaison',
      3 => 'Case Manager',
      4 => 'Activities Director',
      5 => 'Activity Assistant',
    ),
    'order' => 63,
    'is_active' => false,
  ),
  63 => 
  array (
    'name' => 'Trauma-Informed & Dementia Care Basics',
    'description' => 'Communication strategies for dementia and trauma-informed approaches.',
    'content_url' => 'https://lms.example.com/modules/dementia-care',
    'provider_label' => 'LMS Provider',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Social Services Director',
      1 => 'Social Worker',
      2 => 'Resident Liaison',
      3 => 'Case Manager',
      4 => 'Activities Director',
      5 => 'Activity Assistant',
    ),
    'order' => 64,
    'is_active' => false,
  ),
  64 => 
  array (
    'name' => 'Rehab Documentation & Medicare Compliance Basics',
    'description' => 'Therapy documentation standards and medical necessity awareness for rehab staff.',
    'content_url' => 'https://lms.example.com/modules/rehab-documentation',
    'provider_label' => 'LMS Provider',
    'frequency' => 'hiring',
    'position_titles' => 
    array (
      0 => 'Occupational Therapist',
      1 => 'Physical Therapist',
      2 => 'OT/PT Assistant',
      3 => 'Rehab Manager',
    ),
    'order' => 65,
    'is_active' => false,
  ),
  65 => 
  array (
    'name' => 'QAPI & Survey Readiness Overview',
    'description' => 'Quality Assurance and Performance Improvement roles and survey readiness expectations for leaders.',
    'content_url' => '/trainings/qapi-survey-readiness',
    'provider_label' => 'Internal',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Administrator',
      1 => 'Director of Nursing',
      2 => 'Director of Staff Development',
      3 => 'Staff Development Coordinator',
      4 => 'Business Office Manager',
      5 => 'Social Services Director',
      6 => 'Food Services Director',
      7 => 'Maintenance Director',
      8 => 'Housekeeping Supervisor',
      9 => 'Activities Director',
      10 => 'Rehab Manager',
      11 => 'Medical Records Director',
      12 => 'Marketing Director',
    ),
    'order' => 66,
    'is_active' => false,
  ),
  66 => 
  array (
    'name' => 'Staffing, Payroll Accuracy & Timekeeping Compliance',
    'description' => 'Accurate timekeeping, overtime awareness, and staffing documentation expectations for supervisors.',
    'content_url' => 'https://lms.example.com/modules/staffing-timekeeping',
    'provider_label' => 'LMS Provider',
    'frequency' => 'annual',
    'position_titles' => 
    array (
      0 => 'Administrator',
      1 => 'Director of Nursing',
      2 => 'Director of Staff Development',
      3 => 'Staff Development Coordinator',
      4 => 'Business Office Manager',
      5 => 'Social Services Director',
      6 => 'Food Services Director',
      7 => 'Maintenance Director',
      8 => 'Housekeeping Supervisor',
      9 => 'Activities Director',
      10 => 'Rehab Manager',
      11 => 'Medical Records Director',
      12 => 'Marketing Director',
    ),
    'order' => 67,
    'is_active' => false,
  ),
);
