<?php

return [
    'corporate_facility_slug' => env('CORPORATE_FACILITY_SLUG', 'bio-pacific-corporate'),

    'demo_user_emails' => [
        'rdhr' => 'rdhr@biopacific.com',
        'facility_admin' => 'facilityadmin@biopacific.com',
        'facility_dsd' => 'facilitydsd@biopacific.com',
        'don' => 'don@biopacific.com',
    ],

    'demo_facility_matchers' => [
        'pineridge' => ['facility_number' => '35494'],
        'santa_monica' => ['facility_number' => '35479'],
    ],

    'super_admin_role' => 'super-admin',

    'system_admin_roles' => ['admin', 'super-admin'],

    'corporate_roles' => ['rdhr', 'regional-director'],

    'facility_manager_roles' => ['facility-admin', 'facility-dsd', 'facility-ssd', 'don'],

    'facility_manager_global_route_patterns' => [
        'admin.dashboard.index',
        'member.facility.dashboard',
        'admin.facility.dashboard',
        'hr-portal.*',
        'user.hr-portal',
        'admin.hr-portal.*',
        'settings.*',
        'member.*',
        'pre-employment.*',
        'employment.*',
    ],

    'admin_route_patterns' => [
        'admin.dashboard.*',
        'admin.facilities.*',
        'admin.facility.leadership*',
        'admin.facilities.leadership*',
        'admin.users.*',
        'admin.settings.*',
        'admin.roles.*',
        'admin.permissions.*',
        'admin.role-assignments.*',
        'admin.positions.*',
        'admin.departments.*',
        'admin.arbitration-templates.*',
        'admin.scheduled-report-runs.*',
        'admin.checklist-items.*',
        'admin.import-mapping-presets.*',
        'admin.import-logs.*',
        'admin.upload-types.*',
        'admin.baa-registry.*',
        'admin.hipaa-checklist.*',
        'admin.security.*',
        'admin.events.*',
        'admin.reports.*',
        'admin.scheduled-reports.*',
        'admin.blogs.*',
    ],

    'admin_sidebar_nav' => [
        ['id' => 'admin-dashboard', 'route' => 'admin.dashboard.index', 'icon' => '⚙️', 'label' => 'Dashboard'],
        [
            'id' => 'facilities',
            'route' => 'admin.facilities.index',
            'route_is' => [
                'admin.facilities.index',
                'admin.facilities.create',
                'admin.facilities.edit',
                'admin.facilities.update',
                'admin.facilities.show',
                'admin.facilities.store',
                'admin.facilities.destroy',
                'admin.facilities.leadership*',
                'admin.facility.leadership*',
            ],
            'icon' => '🏢',
            'label' => 'Facilities',
        ],
        [
            'id' => 'facility-leadership',
            'route' => 'admin.facilities.leadership.index',
            'route_is' => ['admin.facilities.leadership*', 'admin.facility.leadership*'],
            'icon' => '👔',
            'label' => 'Facility Leadership',
        ],
        ['id' => 'users', 'route' => 'admin.users.index', 'route_is' => 'admin.users.*', 'icon' => '👥', 'label' => 'Users'],
        ['id' => 'roles', 'route' => 'admin.roles.index', 'route_is' => ['admin.roles.*', 'admin.permissions.*', 'admin.role-assignments.*'], 'icon' => '🛡️', 'label' => 'Roles & Permissions'],
        ['id' => 'settings', 'route' => 'admin.settings.index', 'route_is' => 'admin.settings.*', 'icon' => '🔧', 'label' => 'System Settings'],
        ['id' => 'employee-portal', 'route' => 'dashboard.index', 'icon' => '🏠', 'label' => 'Employee Portal'],
    ],

    'personal_portal_route_patterns' => [
        'settings.profile',
        'member.trainings',
        'member.trainings.*',
        'member.documents',
        'member.documents.*',
        'member.certifications',
        'member.certifications.*',
    ],

    'personal_portal_documents_route_patterns' => [
        'member.documents',
        'member.documents.*',
    ],

    'personal_portal_nav' => [
        [
            'id' => 'profile',
            'route' => 'settings.profile',
            'route_is' => 'settings.profile',
            'label' => 'My Profile',
        ],
        [
            'id' => 'trainings',
            'route' => 'member.trainings',
            'route_is' => ['member.trainings', 'member.trainings.*'],
            'label' => 'My Trainings',
        ],
        [
            'id' => 'documents',
            'route' => 'member.documents',
            'route_is' => ['member.documents', 'member.documents.*'],
            'label' => 'My Documents',
            'badge' => 3,
            'badge_class' => 'bg-amber-400 text-slate-900',
            'children' => [
                [
                    'id' => 'certifications',
                    'route' => 'member.certifications',
                    'route_is' => ['member.certifications', 'member.certifications.*'],
                    'label' => 'Licenses and Certifications',
                ],
            ],
        ],
    ],

    'corporate_dashboard_nav' => [
        ['id' => 'dashboard', 'route' => 'dashboard.index', 'icon' => '🏠', 'label' => 'Dashboard'],
    ],

    'facility_dashboard_nav' => [
        ['id' => 'dashboard', 'route' => 'dashboard.index', 'icon' => '📊', 'label' => 'My work queue'],
        ['id' => 'facility-dashboard', 'route' => 'member.facility.dashboard', 'route_is' => ['member.facility.dashboard', 'admin.facility.dashboard'], 'icon' => '🏢', 'label' => 'Facility Dashboard'],
    ],

    'employee_dashboard_nav' => [
        ['id' => 'dashboard', 'route' => 'dashboard.index', 'icon' => '🏠', 'label' => 'Dashboard'],
        ['id' => 'news', 'route' => 'member.news-events.index', 'icon' => '📰', 'label' => 'News & Events'],
        ['id' => 'pre-employment', 'route' => 'pre-employment.portal', 'route_is' => 'pre-employment.*', 'icon' => '📋', 'label' => 'Pre-Employment'],
        ['id' => 'employment', 'route' => 'employment.portal', 'route_is' => 'employment.*', 'icon' => '💼', 'label' => 'Employment'],
        ['id' => 'messages', 'route' => 'dashboard.index', 'fragment' => 'messages', 'icon' => '💬', 'label' => 'Messages'],
    ],

    /** @deprecated Use corporate_dashboard_nav + personal_portal_nav + management groups */
    'corporate_sidebar_nav' => [],

    /** @deprecated Use facility_dashboard_nav + personal_portal_nav + management groups */
    'facility_sidebar_nav' => [],

    'admin_titles' => [
        'admin.dashboard.*' => 'Admin Dashboard',
        'admin.users.*' => 'Users',
        'admin.settings.*' => 'System Settings',
        'admin.roles.*' => 'Roles',
        'admin.permissions.*' => 'Permissions',
        'admin.role-assignments.*' => 'Role Assignments',
        'admin.positions.*' => 'Positions',
        'admin.departments.*' => 'Departments',
        'admin.arbitration-templates.*' => 'Arbitration Templates',
        'admin.checklist-items.*' => 'Checklist Items',
        'admin.baa-registry.*' => 'BAA Vendor Registry',
        'admin.hipaa-checklist.*' => 'HIPAA Checklist',
        'admin.security.*' => 'Security Monitoring',
        'admin.events.*' => 'Events',
        'admin.reports.*' => 'Reports',
        'admin.scheduled-reports.*' => 'Scheduled Reports',
        'admin.upload-types.*' => 'Documents Management',
    ],

    'corporate_titles' => [
        'admin.positions.*' => 'Positions',
        'admin.reports.*' => 'Reports',
        'admin.scheduled-reports.*' => 'Reports',
        'user.hr-portal' => 'HR Management',
        'hr-portal.*' => 'HR Management',
    ],

    'admin_active_map' => [
        'admin.dashboard.*' => 'admin-dashboard',
        'admin.facilities.leadership*' => 'facility-leadership',
        'admin.facility.leadership*' => 'facility-leadership',
        'admin.facilities.index' => 'facilities',
        'admin.facilities.create' => 'facilities',
        'admin.facilities.edit' => 'facilities',
        'admin.facilities.show' => 'facilities',
        'admin.users.*' => 'users',
        'admin.settings.*' => 'settings',
        'admin.roles.*' => 'roles',
        'admin.permissions.*' => 'roles',
        'admin.role-assignments.*' => 'roles',
        'admin.positions.*' => 'positions',
        'admin.departments.*' => 'roles',
        'admin.arbitration-templates.*' => 'settings',
        'admin.checklist-items.*' => 'settings',
        'admin.import-mapping-presets.*' => 'settings',
        'admin.import-logs.*' => 'settings',
        'admin.upload-types.*' => 'settings',
        'admin.baa-registry.*' => 'admin-baa',
        'admin.hipaa-checklist.*' => 'admin-hipaa',
        'admin.security.*' => 'admin-security',
        'admin.events.*' => 'admin-events',
        'admin.reports.*' => 'admin-reports',
        'admin.scheduled-reports.*' => 'admin-scheduled-reports',
    ],

    'corporate_active_map' => [
        'dashboard.index' => 'dashboard',
        'settings.profile' => 'profile',
        'member.trainings' => 'trainings',
        'member.trainings.*' => 'trainings',
        'member.documents' => 'documents',
        'member.documents.*' => 'documents',
        'member.certifications' => 'certifications',
        'member.certifications.*' => 'certifications',
        'admin.positions.*' => 'facility-positions-management',
        'admin.reports.*' => 'reports',
        'admin.scheduled-reports.*' => 'reports',
        'user.hr-portal' => 'facility-hr-portal',
        'hr-portal.*' => 'facility-hr-portal',
    ],

    'employee_active_map' => [
        'dashboard.index' => 'dashboard',
        'member.news-events.index' => 'news',
        'member.news-events.*' => 'news',
        'pre-employment.*' => 'pre-employment',
        'employment.*' => 'employment',
        'settings.profile' => 'profile',
        'member.trainings' => 'trainings',
        'member.trainings.*' => 'trainings',
        'member.documents' => 'documents',
        'member.documents.*' => 'documents',
        'member.certifications' => 'certifications',
        'member.certifications.*' => 'certifications',
    ],

    'facility_active_map' => [
        'member.facility.dashboard' => 'facility-dashboard',
        'admin.facility.dashboard' => 'facility-dashboard',
        'admin.facility.leadership*' => 'facility-dashboard',
        'admin.facilities.leadership*' => 'facility-dashboard',
        'dashboard.index' => 'dashboard',
        'dashboard.index' => 'dashboard',
        'settings.profile' => 'profile',
        'member.documents' => 'documents',
        'user.hr-portal' => 'hr-portal',
        'hr-portal.*' => 'hr-portal',
        'member.trainings' => 'trainings',
        'member.certifications' => 'certifications',
    ],

    /** @deprecated Use employee_dashboard_nav + personal_portal_nav */
    'sidebar_nav' => [],

    'mobile_nav' => [
        ['id' => 'dashboard', 'route' => 'dashboard.index', 'icon' => '🏠', 'label' => 'Home'],
        ['id' => 'news', 'route' => 'member.news-events.index', 'icon' => '📰', 'label' => 'News'],
        ['id' => 'documents', 'route' => 'member.documents', 'icon' => '📄', 'label' => 'Docs'],
            ['id' => 'certifications', 'route' => 'member.certifications', 'icon' => '🏅', 'label' => 'Licenses'],
        ['id' => 'trainings', 'route' => 'member.trainings', 'icon' => '🎓', 'label' => 'Training'],
        ['id' => 'profile', 'route' => 'settings.profile', 'icon' => '👤', 'label' => 'Profile'],
    ],

    'facility_management_route_patterns' => [
        'user.hr-portal',
        'admin.facility.dashboard',
        'admin.facility.job_openings*',
        'admin.facility.hiring',
        'admin.facility.employees*',
        'admin.employees.*',
        'admin.facility.documents*',
        'admin.facility.reports*',
        'admin.facility.leadership*',
        'admin.facilities.leadership*',
        'admin.reports.*',
        'admin.scheduled-reports.*',
        'admin.scheduled-report-runs.*',
        'admin.hr-portal.reports',
        'admin.facility.uploads*',
        'admin.facility.pre-employment*',
        'admin.facility.document.*',
        'admin.facilities.webcontents.*',
        'facilities.webcontents.*',
        'facilities.news-events.*',
        'admin.galleries.*',
        'admin.news.*',
        'admin.services.*',
        'admin.blogs.*',
        'admin.tour-requests.*',
        'admin.inquiries.*',
        'admin.job-applications.*',
        'admin.email-recipients.*',
        'admin.email-templates.*',
        'admin.communications.employee-email-mappings',
        'admin.upload-types.*',
        'admin.positions.*',
        'admin.training-management.*',
    ],

    'facility_management_web_route_patterns' => [
        'admin.facilities.webcontents.testimonials',
        'admin.facilities.webcontents.faqs',
        'admin.facilities.webcontents.blogs',
        'admin.facilities.webcontents.careers*',
        'facilities.webcontents.testimonials',
        'facilities.webcontents.faqs',
        'facilities.webcontents.blogs',
        'facilities.webcontents.news-events',
        'facilities.news-events.*',
        'admin.galleries.*',
        'admin.news.*',
        'admin.services.*',
        'admin.blogs.*',
    ],

    'facility_management_comm_route_patterns' => [
        'admin.tour-requests.*',
        'admin.inquiries.*',
        'admin.job-applications.*',
        'admin.email-recipients.*',
        'admin.email-templates.*',
        'admin.communications.employee-email-mappings',
    ],

    'facility_management_titles' => [
        'admin.dashboard.index' => 'HR Management',
        'hr-portal.*' => 'HR Management',
        'user.hr-portal' => 'HR Management',
        'admin.facility.dashboard' => 'Facility Dashboard',
        'admin.facility.job_openings*' => 'Job Listings',
        'admin.facility.hiring' => 'Hiring',
        'admin.facility.employees*' => 'Employees',
        'admin.employees.*' => 'Employee',
        'admin.facility.documents*' => 'Documents',
        'admin.facility.reports*' => 'Reports',
        'admin.reports.*' => 'Reports Management',
        'admin.scheduled-reports.*' => 'Scheduled Reports',
        'admin.scheduled-report-runs.*' => 'Report Runs',
        'admin.hr-portal.reports' => 'Reports',
        'admin.facilities.webcontents.testimonials' => 'Testimonials',
        'admin.facilities.webcontents.faqs' => 'FAQs',
        'admin.facilities.webcontents.blogs' => 'Blogs',
        'admin.facilities.webcontents.careers*' => 'Careers',
        'admin.galleries.*' => 'Galleries',
        'admin.news.*' => 'News',
        'admin.services.*' => 'Services',
        'admin.tour-requests.*' => 'Tour Requests',
        'admin.inquiries.*' => 'General Inquiries',
        'admin.job-applications.*' => 'Job Applications',
        'admin.email-recipients.*' => 'Email Recipients',
        'admin.email-templates.*' => 'Email Templates',
        'admin.communications.employee-email-mappings' => 'Employee Email Mappings',
        'admin.upload-types.*' => 'Documents Management',
        'admin.positions.*' => 'Positions Management',
        'admin.training-management.*' => 'Training Management',
    ],

    'facility_management_active_map' => [
        'admin.dashboard.index' => 'facility-hr-portal',
        'hr-portal.*' => 'facility-hr-portal',
        'user.hr-portal' => 'facility-hr-portal',
        'admin.facility.dashboard' => 'facility-dashboard',
        'member.facility.dashboard' => 'facility-dashboard',
        'admin.facility.employees*' => 'facility-hr-portal',
        'admin.employees.*' => 'facility-hr-portal',
        'admin.facility.reports*' => 'facility-hr-portal',
        'admin.reports.*' => 'facility-hr-portal',
        'admin.scheduled-reports.*' => 'facility-hr-portal',
        'admin.scheduled-report-runs.*' => 'facility-hr-portal',
        'admin.hr-portal.reports' => 'facility-hr-portal',
        'admin.facilities.webcontents.testimonials' => 'facility-testimonials',
        'admin.facilities.webcontents.faqs' => 'facility-faqs',
        'admin.facilities.webcontents.blogs' => 'facility-blogs',
        'admin.facilities.webcontents.careers*' => 'facility-careers',
        'admin.galleries.*' => 'facility-galleries',
        'admin.news.*' => 'facility-news',
        'admin.services.*' => 'facility-services',
        'admin.tour-requests.*' => 'facility-tour-requests',
        'admin.inquiries.*' => 'facility-inquiries',
        'admin.job-applications.*' => 'facility-job-applications',
        'admin.email-recipients.*' => 'facility-email-recipients',
        'admin.email-templates.*' => 'facility-email-templates',
        'admin.communications.employee-email-mappings' => 'facility-email-mappings',
        'admin.upload-types.*' => 'facility-documents-management',
        'admin.positions.*' => 'facility-positions-management',
        'admin.training-management.*' => 'facility-training-management',
    ],
];
