<?php

return [
    'super_admin_role' => 'super-admin',

    'system_admin_roles' => ['admin', 'super-admin'],

    'facility_manager_roles' => ['rdhr', 'facility-admin', 'facility-dsd'],

    'facility_manager_global_route_patterns' => [
        'admin.dashboard.index',
        'hr-portal.*',
        'user.hr-portal',
        'admin.hr-portal.*',
        'settings.*',
        'member.*',
        'pre-employment.*',
        'employment.*',
    ],

    'admin_route_patterns' => [
        'admin.dashboard.*',
        'admin.facilities.*',
        'admin.users.*',
        'admin.settings.*',
        'admin.roles.*',
        'admin.permissions.*',
        'admin.role-assignments.*',
        'admin.positions.*',
        'admin.departments.*',
        'admin.arbitration-templates.*',
        'admin.scheduled-report-runs.*',
        'admin.checklist-items.*',
        'admin.import-mapping-presets.*',
        'admin.import-logs.*',
        'admin.baa-registry.*',
        'admin.hipaa-checklist.*',
        'admin.security.*',
        'admin.events.*',
        'admin.reports.*',
        'admin.scheduled-reports.*',
        'admin.blogs.*',
    ],

    'admin_sidebar_nav' => [
        ['id' => 'admin-dashboard', 'route' => 'admin.dashboard.index', 'icon' => '⚙️', 'label' => 'Dashboard'],
        [
            'id' => 'facilities',
            'route' => 'admin.facilities.index',
            'route_is' => [
                'admin.facilities.index',
                'admin.facilities.create',
                'admin.facilities.edit',
                'admin.facilities.update',
                'admin.facilities.show',
                'admin.facilities.store',
                'admin.facilities.destroy',
            ],
            'icon' => '🏢',
            'label' => 'Facilities',
        ],
        ['id' => 'users', 'route' => 'admin.users.index', 'route_is' => 'admin.users.*', 'icon' => '👥', 'label' => 'Users'],
        ['id' => 'roles', 'route' => 'admin.roles.index', 'route_is' => ['admin.roles.*', 'admin.permissions.*', 'admin.role-assignments.*'], 'icon' => '🛡️', 'label' => 'Roles & Permissions'],
        ['id' => 'settings', 'route' => 'admin.settings.index', 'route_is' => 'admin.settings.*', 'icon' => '🔧', 'label' => 'System Settings'],
        ['id' => 'employee-portal', 'route' => 'dashboard.index', 'icon' => '🏠', 'label' => 'Employee Portal'],
    ],

    'admin_titles' => [
        'admin.dashboard.*' => 'Admin Dashboard',
        'admin.users.*' => 'Users',
        'admin.settings.*' => 'System Settings',
        'admin.roles.*' => 'Roles',
        'admin.permissions.*' => 'Permissions',
        'admin.role-assignments.*' => 'Role Assignments',
        'admin.positions.*' => 'Positions',
        'admin.departments.*' => 'Departments',
        'admin.arbitration-templates.*' => 'Arbitration Templates',
        'admin.checklist-items.*' => 'Checklist Items',
        'admin.baa-registry.*' => 'BAA Vendor Registry',
        'admin.hipaa-checklist.*' => 'HIPAA Checklist',
        'admin.security.*' => 'Security Monitoring',
        'admin.events.*' => 'Events',
        'admin.reports.*' => 'Reports',
        'admin.scheduled-reports.*' => 'Scheduled Reports',
    ],

    'admin_active_map' => [
        'admin.dashboard.*' => 'admin-dashboard',
        'admin.facilities.index' => 'facilities',
        'admin.facilities.create' => 'facilities',
        'admin.facilities.edit' => 'facilities',
        'admin.facilities.show' => 'facilities',
        'admin.users.*' => 'users',
        'admin.settings.*' => 'settings',
        'admin.roles.*' => 'roles',
        'admin.permissions.*' => 'roles',
        'admin.role-assignments.*' => 'roles',
        'admin.positions.*' => 'roles',
        'admin.departments.*' => 'roles',
        'admin.arbitration-templates.*' => 'settings',
        'admin.checklist-items.*' => 'settings',
        'admin.import-mapping-presets.*' => 'settings',
        'admin.import-logs.*' => 'settings',
        'admin.baa-registry.*' => 'admin-baa',
        'admin.hipaa-checklist.*' => 'admin-hipaa',
        'admin.security.*' => 'admin-security',
        'admin.events.*' => 'admin-events',
        'admin.reports.*' => 'admin-reports',
        'admin.scheduled-reports.*' => 'admin-scheduled-reports',
    ],

    'sidebar_nav' => [
        ['id' => 'dashboard', 'route' => 'dashboard.index', 'icon' => '🏠', 'label' => 'Dashboard'],
        ['id' => 'schedule', 'route' => 'member.schedule', 'icon' => '📅', 'label' => 'Schedule'],
        ['id' => 'profile', 'route' => 'settings.profile', 'icon' => '👤', 'label' => 'My Profile'],
        ['id' => 'news', 'route' => 'member.news-events.index', 'icon' => '📰', 'label' => 'News & Events'],
        ['id' => 'pre-employment', 'route' => 'pre-employment.portal', 'route_is' => 'pre-employment.*', 'icon' => '📋', 'label' => 'Pre-Employment'],
        ['id' => 'employment', 'route' => 'employment.portal', 'route_is' => 'employment.*', 'icon' => '💼', 'label' => 'Employment'],
        [
            'id' => 'documents',
            'route' => 'member.documents',
            'icon' => '📄',
            'label' => 'Documents',
            'badge' => 3,
            'badge_class' => 'bg-amber-400 text-slate-900',
        ],
        [
            'id' => 'certifications',
            'route' => 'member.certifications',
            'icon' => '🏅',
            'label' => 'Certifications',
        ],
        [
            'id' => 'trainings',
            'route' => 'member.trainings',
            'icon' => '🎓',
            'label' => 'Trainings',
        ],
        ['id' => 'messages', 'route' => 'dashboard.index', 'fragment' => 'messages', 'icon' => '💬', 'label' => 'Messages'],
    ],

    'mobile_nav' => [
        ['id' => 'dashboard', 'route' => 'dashboard.index', 'icon' => '🏠', 'label' => 'Home'],
        ['id' => 'schedule', 'route' => 'member.schedule', 'icon' => '📅', 'label' => 'Schedule'],
        ['id' => 'news', 'route' => 'member.news-events.index', 'icon' => '📰', 'label' => 'News'],
        ['id' => 'documents', 'route' => 'member.documents', 'icon' => '📄', 'label' => 'Docs'],
        ['id' => 'certifications', 'route' => 'member.certifications', 'icon' => '🏅', 'label' => 'Certs'],
        ['id' => 'trainings', 'route' => 'member.trainings', 'icon' => '🎓', 'label' => 'Training'],
        ['id' => 'profile', 'route' => 'settings.profile', 'icon' => '👤', 'label' => 'Profile'],
    ],

    'facility_management_route_patterns' => [
        'user.hr-portal',
        'admin.facility.dashboard',
        'admin.facility.job_openings*',
        'admin.facility.hiring',
        'admin.facility.employees*',
        'admin.employees.*',
        'admin.facility.documents*',
        'admin.facility.reports*',
        'admin.reports.*',
        'admin.scheduled-reports.*',
        'admin.scheduled-report-runs.*',
        'admin.hr-portal.reports',
        'admin.facility.uploads*',
        'admin.facility.pre-employment*',
        'admin.facility.document.*',
        'admin.facilities.webcontents.*',
        'facilities.webcontents.*',
        'facilities.news-events.*',
        'admin.galleries.*',
        'admin.news.*',
        'admin.services.*',
        'admin.blogs.*',
        'admin.tour-requests.*',
        'admin.inquiries.*',
        'admin.job-applications.*',
        'admin.email-recipients.*',
        'admin.email-templates.*',
        'admin.communications.employee-email-mappings',
    ],

    'facility_management_web_route_patterns' => [
        'admin.facilities.webcontents.testimonials',
        'admin.facilities.webcontents.faqs',
        'admin.facilities.webcontents.blogs',
        'admin.facilities.webcontents.careers*',
        'facilities.webcontents.testimonials',
        'facilities.webcontents.faqs',
        'facilities.webcontents.blogs',
        'facilities.webcontents.news-events',
        'facilities.news-events.*',
        'admin.galleries.*',
        'admin.news.*',
        'admin.services.*',
        'admin.blogs.*',
    ],

    'facility_management_comm_route_patterns' => [
        'admin.tour-requests.*',
        'admin.inquiries.*',
        'admin.job-applications.*',
        'admin.email-recipients.*',
        'admin.email-templates.*',
        'admin.communications.employee-email-mappings',
    ],

    'facility_management_titles' => [
        'admin.dashboard.index' => 'HR Portal',
        'hr-portal.*' => 'HR Portal',
        'user.hr-portal' => 'HR Portal',
        'admin.facility.dashboard' => 'Facility Dashboard',
        'admin.facility.job_openings*' => 'Job Listings',
        'admin.facility.hiring' => 'Hiring',
        'admin.facility.employees*' => 'Employees',
        'admin.employees.*' => 'Employee',
        'admin.facility.documents*' => 'Documents',
        'admin.facility.reports*' => 'Reports',
        'admin.reports.*' => 'Reports Management',
        'admin.scheduled-reports.*' => 'Scheduled Reports',
        'admin.scheduled-report-runs.*' => 'Report Runs',
        'admin.hr-portal.reports' => 'Reports',
        'admin.facilities.webcontents.testimonials' => 'Testimonials',
        'admin.facilities.webcontents.faqs' => 'FAQs',
        'admin.facilities.webcontents.blogs' => 'Blogs',
        'admin.facilities.webcontents.careers*' => 'Careers',
        'admin.galleries.*' => 'Galleries',
        'admin.news.*' => 'News',
        'admin.services.*' => 'Services',
        'admin.tour-requests.*' => 'Tour Requests',
        'admin.inquiries.*' => 'General Inquiries',
        'admin.job-applications.*' => 'Job Applications',
        'admin.email-recipients.*' => 'Email Recipients',
        'admin.email-templates.*' => 'Email Templates',
        'admin.communications.employee-email-mappings' => 'Employee Email Mappings',
    ],

    'facility_management_active_map' => [
        'admin.dashboard.index' => 'facility-hr-portal',
        'hr-portal.*' => 'facility-hr-portal',
        'user.hr-portal' => 'facility-hr-portal',
        'admin.facility.dashboard' => 'facility-hr-portal',
        'admin.facility.employees*' => 'facility-hr-portal',
        'admin.employees.*' => 'facility-hr-portal',
        'admin.facility.reports*' => 'facility-hr-portal',
        'admin.reports.*' => 'facility-hr-portal',
        'admin.scheduled-reports.*' => 'facility-hr-portal',
        'admin.scheduled-report-runs.*' => 'facility-hr-portal',
        'admin.hr-portal.reports' => 'facility-hr-portal',
        'admin.facilities.webcontents.testimonials' => 'facility-testimonials',
        'admin.facilities.webcontents.faqs' => 'facility-faqs',
        'admin.facilities.webcontents.blogs' => 'facility-blogs',
        'admin.facilities.webcontents.careers*' => 'facility-careers',
        'admin.galleries.*' => 'facility-galleries',
        'admin.news.*' => 'facility-news',
        'admin.services.*' => 'facility-services',
        'admin.tour-requests.*' => 'facility-tour-requests',
        'admin.inquiries.*' => 'facility-inquiries',
        'admin.job-applications.*' => 'facility-job-applications',
        'admin.email-recipients.*' => 'facility-email-recipients',
        'admin.email-templates.*' => 'facility-email-templates',
        'admin.communications.employee-email-mappings' => 'facility-email-mappings',
    ],
];
